### ISSUE TITLE
Allow finding PDFs from `helm-bibtex-library-path` with user defined file name

### ISSUE THREAD

**Issue by zzjjzzgggg** [tmalsburg/helm-bibtex#100]
The function `helm-bibtex-find-pdf-in-field (key-or-entry)` should also try to find PDFs in directories specified by `helm-bibtex-library-path` when the relative path of a PDF is provided in the `file` field of an entry.

As a JabRef user, this situation is very common. For example, my `helm-bibtex-library-path` is "~/papers", and an entry's `file` field is `file = {:docs/p1087.pdf:PDF}`. The full path of the PDF is `~/papers/docs/p1087.pdf`. I find that helm-bibtex failed finding the PDF if the file name is not the key of current entry.

Consider adding some judgement like 
```
         else if (f-file? (f-full (f-join helm-bibtex-library-path path)))
         collect (f-full (f-join helm-bibtex-library-path path))
```
in the function `helm-bibtex-find-pdf-in-field (key-or-entry)`. Also notice that I simply treat `helm-bibtex-library-path` as a variable not a list, since I don't know how to write a nested loop in elisp, sigh...

**Comment by tmalsburg** [comment]
I think the code for finding PDFs needs a total makeover.  Perhaps we need something like a plug-in architecture that gives users more flexibility.  A user could then for example choose the jabref plugin or even several plugins if they store PDFs in several different ways.

**Comment by tmalsburg** [comment]
This should work now.  Please try the latest version to confirm.

**Comment by tmalsburg** [comment]
Closing for now. Feel free to reopen if it doesn't work.
