### ISSUE TITLE
Unable to open PDF specified by "file" field in bibtex file generated using Mendeley

### ISSUE THREAD

**Issue by shivamkalra** [tmalsburg/helm-bibtex#105]
I use Mendeley for updating the bibtex files.. I've `(setq helm-bibtex-pdf-field "file")` in my configuration but `helm-bibtex` is unable to find PDFs. I've temporarily fixed the issue by changing following code:

https://github.com/tmalsburg/helm-bibtex/blob/master/bibtex-completion.el#L413

to

```
if (f-file? (concat "/" path))
           collect (concat "/" path)
```

It seems like problem is `f-full` as it returns wrong path. I had to replace it with `(concat "/" path)`. Does anyone have similar issue for Mendeley desktop generated bibtex file? I'm on Arch Linux using latest versions of both the programs.

**Comment by tmalsburg** [comment]
I don't use Mendeley so I don't know whether the current code is working properly.  But I haven't received any complaints about it recently. It's slightly weird that your code works because the path separator character on Linux is / not \.  Could you please post a sample BibTeX entry for testing?

**Comment by shivamkalra** [comment]
Titus von der Malsburg <notifications@github.com> writes:

> [..] It's slightly weird that your code works because the path
> separator character on Linux is / not \. Could you please post a
> sample BibTeX entry for testing?

Actually my code also has /, sorry I made mistake before (updated now).
Here is the sample article entry from my bibtex library file.

```
@article{Ellabaan_2009,
author = {Ellabaan, Mostafa M H},
doi = {10.1109/ISDA.2009.115},
file = {:home/skalra/Dropbox/Bibliography/pdfs/2009/Ellabaan. 2009.pdf:pdf},
isbn = {9780769538723},
pages = {1--6},
title = {{Valley-Adaptive Clearing Scheme for Multimodal Optimization Evolutionary Search}},
year = {2009}
}
```

I'm aware that you've already taken care of missing /. However, it seems
like `(f-full home/skalra/Dropbox/Bibliography/pdfs/2009/Ellabaan.
2009.pdf)` is not appending / instead it appends `CWD`.

-- 
Shivam

**Comment by tmalsburg** [comment]
I think I was relying on f-full doing something that isn't really specified, so I should change that.  Thanks for reporting.  In the medium term, I want to rewrite the whole system for finding PDFs.  Currently, the code tries to make everyone happy, but the result is somewhat slow and not always predictable.  I'm thinking about having a plug-in system, where people can choose the Mendeley-plugin for finding PDFs or whatever else plug-in they want.  It would also be possible to activate several plug-ins, which may be useful for people with messier bibliographies.

**Comment by shivamkalra** [comment]
Titus von der Malsburg <notifications@github.com> writes:

> I think I was relying on f-full doing something that isn't really
> specified, so I should change that. Thanks for reporting. In the
> medium term, I want to rewrite the whole system for finding PDFs.
> Currently, the code tries to make everyone happy, but the result is
> somewhat slow and not always predictable. I'm thinking about having a
> plug-in system, where people can choose the Mendeley-plugin for
> finding PDFs or whatever else plug-in they want. It would also be
> possible to activate several plug-ins, which may be useful for people
> with messier bibliographies.

Sounds good. There is one more oddity I noticed with Mendeley. It is
that, when you have `_` in file's path, it tends to escape it like
`{\_}`. May be it is standard way of escaping _ character in bib files.

-- 
Shivam

**Comment by tmalsburg** [comment]
The first issue should be fixed now.  Could you please try https://github.com/tmalsburg/helm-bibtex/commit/3b123d544bf31240d8065c28b896a57923b29165 and tell me if it works?

>  It is that, when you have `_` in file's path, it tends to escape it like `{\_}`.

What do you mean by "it tends"?  Are there also cases were it is not escaped like that?

**Comment by cryoguy** [comment]
In my case, Mendeley always escapes _ like {\_}, and I end up with "no pdf" when trying to open.  Any fix to this?  Thanks.

@article{Fujishima1972,
abstract = {, Nature 238 (1972) 37–38.},
archivePrefix = {arXiv},
arxivId = {arXiv:1011.1669v3},
author = {FUJISHIMA, AKIRA and HONDA, KENICHI},
doi = {10.1038/238037a0},
eprint = {arXiv:1011.1669v3},
file = {:mnt/2nd{\_}BAY/papers/FUJISHIMA, HONDA - 1972 - Electrochemical Photolysis of Water at a Semiconductor Electrode - Nature.pdf:pdf},
isbn = {0028-0836},
issn = {0028-0836},
journal = {Nature},
keywords = {TiO2},
mendeley-tags = {TiO2},
month = {jul},
number = {5358},
pages = {37--38},
pmid = {12635268},
title = {{Electrochemical Photolysis of Water at a Semiconductor Electrode}},
url = {http://www.nature.com/doifinder/10.1038/238037a0},
volume = {238},
year = {1972}
}

**Comment by shivamkalra** [comment]
@tmalsburg Thank you. Latest version fixed the `/` issue.

@cryoguy I believe Mendley uses `{_}` for maths where as `{\_}` for delimiter.

**Comment by cryoguy** [comment]
@shivamkalra  Is this the reason I can not open the pdf file? my pdfs are stored in a path-name with a `{_} `which becomes `{\_} `after Mendeley conversion.  Thanks.

**Comment by tmalsburg** [comment]
The [current code](https://github.com/tmalsburg/helm-bibtex/blob/master/bibtex-completion.el#L408) replaces `{\_}` by `_ ` does that solve your problem?

**Comment by cryoguy** [comment]
@tmalsburg I realize that and still try to figure out why it failed to locate the pdf.  Is it because the file name?  Thanks for you assistance.

**Comment by cryoguy** [comment]
I just figure out that the problem lies in org-ref.    Helm-bibtex opens pdf ok (with pdf-tools in my case) when I disabled org-ref.  Now I need to figure out the problem there.  Thanks for all your assistance.

**Comment by cryoguy** [comment]
It is fixed now.  https://github.com/jkitchin/org-ref/issues/184   Thanks!

**Comment by tmalsburg** [comment]
Ah, glad to hear that it's working now!  I'm closing this now.  @shivamkalra feel free to reopen if you still experience problems with underscores.

**Comment by shivamkalra** [comment]
I would like to reopen this issue. I'm starting to get same error again.

**Comment by tmalsburg** [comment]
Sure, go ahead.  But I will very likely not have time to work on this over the next weeks.  I already invested too much in time into this, especially given that I'm not even using the file field myself.  But if you want to prepare a PR, I'll be happy to look at it.

**Comment by shivamkalra** [comment]
@tmalsburg Only you have ability to open this PR (since you closed it). 

Sure, I'll be happy to contribute. Although, please see my updated comment.

However, I'm thinking of just setting a variable `bibtex-library-type` to `mendley and then just add special conditional case for Mendley. What do you think?

**Comment by tmalsburg** [comment]
I think I found the problem.  It occurs when the first field is empty.

**Comment by tmalsburg** [comment]
Should be fixed in 62593c6289a3d17566edb1aa8ef4700bc83e9df7. Could you please check?

**Comment by shivamkalra** [comment]
@tmalsburg Thank you. Works nicely.

**Comment by pangdouya** [comment]
Hi, I would like to report a issue. Helm-bibtex can't find the pdf file when the file path contains some nonascii character. For example the following bib item is generated by Mendeley .

@article{Jancar2010a,
archivePrefix = {arXiv},
arxivId = {arXiv:1010.4760v4},
author = {Jan{\v{c}}ar, Petr},
eprint = {arXiv:1010.4760v4},
file = {:home/yin/Documents/Papers/arXiv preprint arXiv1010.4760/Jan{\v{c}}ar - 2010 - A Short Decidability Proof for DPDA Language Equivalence via First-Order Grammars.pdf:pdf},
journal = {arXiv preprint arXiv:1010.4760},
keywords = {decidability,deterministic context-free language,first-order gram-,language equivalence,mar,pushdown automaton,trace equivalence},
pages = {1--28},
title = {{A Short Decidability Proof for DPDA Language Equivalence via First-Order Grammars}},
url = {http://arxiv.org/abs/1010.4760},
year = {2010}
}

Helm-bibtex can't find pdf file for this item. But on my file system the path is
/home/yin/Documents/Papers/arXiv preprint arXiv1010.4760/Jančar - 2010 - A Short Decidability Proof for DPDA Language Equivalence via First-Order Grammars.pdf

**Comment by tmalsburg** [comment]
Not sure why Mendeley escape these characters when UTF-8 should work just fine.  Anyway, I'm not going to work on this because I don't use Mendeley.  PRs welcome, though.

**Comment by jagrg** [comment]
This looks more like a Mendeley issue to me. They should at least have the option to prevent escaping the file field. In any case, you may want to experiment with biber as [this](https://tex.stackexchange.com/questions/27382/problem-with-escaped-characters-in-bibliography-when-using-mendeley-natbib-ur) Mendeley user suggests. Another solution to try would be to revert escaped characters in the file field before opening the PDF. If that works well, you could even replace helm-bibtex's open pdf function ;)

```elisp
(setq bibtex-escape-chars
      '(("{\\\\v{c}}" . "č")
	;; add more here...
	))

(defun my/helm-bibtex-open-pdf (_)
  (let* ((keys (helm-marked-candidates :with-wildcard t))
	 (entry (bibtex-completion-get-entry (car keys)))
	 (file (cdr (assoc "File" entry))))
    (with-temp-buffer
      (insert file)
      (goto-char (point-min))
      (dolist (char (mapcar (lambda (x) (car x)) bibtex-escape-chars))
	(while (re-search-forward char nil t)
	  (replace-match (cdr (assoc char bibtex-escape-chars))))
	(goto-char (point-min))
	(setq bibtex-completion--pdf (replace-regexp-in-string "^{" "" (replace-regexp-in-string "}$" "" (buffer-string))))))
    (funcall bibtex-completion-pdf-open-function bibtex-completion--pdf)))

(helm-add-action-to-source "Open PDF file (test me!)" 'my/helm-bibtex-open-pdf helm-source-bibtex 0)
```

**Comment by autosquid** [comment]
sorry to post to a closed issue.

@shivamkalra  use '-' instead of '_' in mendeley as delimiter, while I use '-' in mine. 


The following is the snippet I provide to `org-ref` to find pdfs for mendeley (`org-ref-get-mendeley-filename`).  It works for me so far. Hope it helps. 

```
(let ((e (org-ref-reftex-get-bib-field "file" entry)))
        (if (> (length e) 4)
            (let ((clean-field (replace-regexp-in-string "{\\|}\\|\\\\" "" e)))
              (let ((first-file (car (split-string clean-field ";" t))))
                (format "/%s" (substring first-file 1
					 (- (length first-file) 4)))))
          (format (concat
                   (file-name-as-directory org-ref-pdf-directory)
                   "%s.pdf")
                  key)))
```
