### ISSUE TITLE
Import library from mendely

### ISSUE THREAD

**Issue by DrWaleedAYousef** [tmalsburg/helm-bibtex#108]
I am using Mendely Desktop, and I want to switch to helm-bib. I have 3 questions:

1- How can I convert my FULL Mendely library (pdf, citation key, ...) to helm-bib
2- Does helm-bib have the nice feature of Mendely that extract article info from a pdf?
3- Can I have article groups as in Mendely?

Thanks

**Comment by tmalsburg** [comment]
Hi, all you questions are answered in the documentation: https://github.com/tmalsburg/helm-bibtex

The short answer is that helm-bibtex should not necessarily be seen as a replacement for Mendeley.  I think many people just use it to access Mendeley's bibliography from Emacs.
