### ISSUE TITLE
ivy-bibtex error: ad-Advice-select-window: Wrong type argument: window-live-p, nil

### ISSUE THREAD

**Issue by zeltak** [tmalsburg/helm-bibtex#111]
Hi wanted to try ivy-bibtex but got this error when trying to launch it

```ad-Advice-select-window: Wrong type argument: window-live-p, nil```
just reporting since im very happy with helm-bibtex, but wanted to give it a try ;-)

best

Z

**Comment by justbur** [comment]
I can't reproduce this. @zeltak do you have steps from `emacs -Q`?

**Comment by zeltak** [comment]
Hi justbur

i can confirm it work with emacs -Q with minimal config
again i love helm-bibtex but am wiling to help out debug this to help other users, yet i have a mammoth config with > 100 packages so any tips on how to debug this would be great :)

best

**Comment by tmalsburg** [comment]
Regarding point 1. My approach is usually to comment out the second half of my config and see if it works.  If yes, I add the first half of the commented config and test again.  (Similar approach as git bisect.) This way you can pin it down in just a couple of steps.

Regarding tags, they should actually work equally in ivy-bibtex, but you may have to use the config variables of the backend, i.e., `bibtex-completion-additional-search-fields` and so on.
