### ISSUE TITLE
helm-bibtex-candidates error

### ISSUE THREAD

**Issue by DiogoFerrari** [tmalsburg/helm-bibtex#114]
When I run org-ref-helm-insert-cite-link I get the following error

In `BibTeX entries' source: `helm-bibtex-candidates' 
 (error "helm-interpret-value: Symbol must be a function or a variable")

Any clue of what is going on?

**Comment by tmalsburg** [comment]
Since this error is triggered by `org-ref-helm-insert-cite-link`, I suppose it's a problem in org-ref.  I would post the issue in their repository.

**Comment by DiogoFerrari** [comment]
the same error occurs if I run helm-bibtex

**Comment by tmalsburg** [comment]
I have never encountered this error before.  What's your configuration? Which version of Emacs? ...

**Comment by DiogoFerrari** [comment]
Here it is:
GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2015-04-10 on builder10-9.porkrind.org

I tried to reinstall helm, helm-bibtex, it still does not work.

**Comment by jagrg** [comment]
@DiogoFerrari org-ref shadows a few functions of helm-bibtex. 

Can you try with emacs -Q without loading org-ref. See if that still yields any error.

**Comment by tmalsburg** [comment]
What @jagrg said, and by configuration I also meant the configuration of helm-bibtex.

**Comment by DiogoFerrari** [comment]
I am using Version: 20160422.1600. @jagrg and @tmalsburg, that is right. If I ignore org-ref, it works well. So my version of org-ref is causing the error. I didn't find it yet. I will start a thread there.

**Comment by tmalsburg** [comment]
Thanks for the update.
