### ISSUE TITLE
Suggestion: customizable Google Scholar fallback option

### ISSUE THREAD

**Issue by DiogoFerrari** [tmalsburg/helm-bibtex#115]
I use googlescholar.com instead of .uk.co b/c my setting and library links are associated with the .com domain. I wrote this hack to change the fallback option associated with that. The particular problem with the way I did below is that if the label for the option change, as It happened from "Google Scholar" in the old version of helm to "Google Scholar                            (web)" in the new one, we have to change the function below accordingly. Maybe there is another more elegant way to do it. It would be nice to have this as am easy customizable feature. 

;; for helm to use googlescholar.com
(setf 
  (cdr (assoc "Google Scholar                            (web)" helm-bibtex-fallback-options))
   "http://scholar.google.com/scholar?q=%s")

Original thread: https://github.com/jkitchin/org-ref/issues/99

**Comment by tmalsburg** [comment]
Just setq the configuration variable `helm-bibtex-fallback-options` to whatever suits you in your init.el.  That overrides the default, in which case you have no problem at all when there are changes in helm-bibtex'.

**Comment by tmalsburg** [comment]
Another solution would be to replace the `co.uk` in helm-bibtex by `.com` which is probably what most people want anyway.
