### ISSUE TITLE
helm-plugin is no longer used

### ISSUE THREAD

**Issue by gongzhitaao** [tmalsburg/helm-bibtex#116]
The following code in [helm-bibtex.el](https://github.com/tmalsburg/helm-bibtex/blob/master/helm-bibtex.el#L98) fails.
```
(require 'helm-plugin)
```
Since `helm-plugin` is no longer used.  I commented it out and everything works fine.

**Comment by tmalsburg** [comment]
Thanks for reporting.  Fixed in 6a355bfd7679de06d79f84d7bd70097fae4402cf.
