### ISSUE TITLE
searching for multiple authors finds none

### ISSUE THREAD

**Issue by plantarum** [tmalsburg/helm-bibtex#117]
Hi,

I'm having problems searching my bib file based on the author field. To reproduce:

Emacs 24.5.50
helm-bibtex-20160714.1000 from melpa

# Setup

    emacs  -Q

## Config

    (require 'package)
    (setq package-load-list
          '((helm t)
            (async t)
            (helm-bibtex t))
    (package-initialize)
    (setq bibtex-completion-bibliography '("~/scratch/test.bib"))

## Contents of "~/scratch/test.bib"

    @Article{smith_waterway_2008b,
      author =       {Tyler W. Smith and Marcia J. Waterway},
      title =        {Evaluating the taxonomic status of the globally rare
                      \emph{Carex roanensis} and allied species using
                      morphology and amplified fragment length polymorphisms},
      journal =      sysbot,
      year =         2008,
      volume =       33,
      pages =        {525--535},
      number =       3
    }
    
    @InProceedings{waterway_2006,
      author =       {Waterway, Marcia J.},
      title =        {Dismantling \emph{Carex} section \emph{Hymenochlaenae}:
                      biogeographic implications},
      booktitle =    {Botany 2006 (Chico, CA, July 29-August 2)},
      year =         2006,
      pages =        265
    }
    
    @incollection{waterway_starr_2007,
      author =       {Waterway, Marcia J. and Starr, Julian R.},
      title =        {Phylogenetic relationships in tribe {Cariceae
                      (Cyperaceae)} based on nested analyses of four molecular
                      data sets},
      booktitle =    {Monocots: Comparative biology and evolution. Vol. 2:
                      Poales},
      editor =       {Columbus, J. Travis and Friar, Elizabeth A. and Hamilton,
                      C. W. and Porter, J. W. and Prince, L. M. and Simpson, M.
                      G.},
      publisher =    {Rancho Santa Ana Botanic Garden},
      pages =        {165--192},
      address =      {Claremont, California},
      keywords =     {phylogeny, Carex},
      year =         2007,
    }
    
    @Book{aafc_1995,
      author =       {{Ecological Stratification Working Group}},
      title =        {A national ecological framework for Canada},
      publisher =    {Agriculture and Agri-Food Canada and Environment Canada},
      year =         1995,
      address =      {Ottawa/Hull},
      date_added =    {2012-04-27}
    }

# Steps to reproduce

Initiate a search with `M-x helm-bibtex`

At this point I'm presented with a list of all four references. 

1. If I enter `waterway` the list narrows, dropping the one entry that doesn't match. However, when I enter a single space, i.e., `waterway `, the two entries where 'waterway' is followed by a comma are dropped. I can 'fix' this by entering `waterway.?` instead, but that's awkward.

2. If I enter `waterway smith` no entries are left. There is a single entry that should match, but no combination of upper or lower case, with or without commas or `.?` that I have tried is successful in matching it.

**Comment by tmalsburg** [comment]
Thanks for the detailed bug report.  This used to work just fine.  Helm-bibtex uses Helm's search facilities, and I guess that there is a problem in Helm that's causing this issue. @thierryvolpiatto did you recently make any changes to the matching algorithm?

**Comment by tmalsburg** [comment]
I think Helm now only selects entries in which the the complete search string matches.  Previously, it selected entries where the search terms (separated by white space) matched individually.

**Comment by plantarum** [comment]
Interesting. `helm-M-x` still seems to work with partial matches on multiple search terms separated by spaces. I thought that used the same backend?

**Comment by jagrg** [comment]
I'm not sure why, but it works with `helm-source-sync`:

```
(helm :sources (helm-build-sync-source "BibTeX entries"
		 :init 'bibtex-completion-init
		 :candidates 'bibtex-completion-candidates
		 :filtered-candidate-transformer 'helm-bibtex-candidates-formatter))
```

**Comment by tmalsburg** [comment]
Helm-dictionary, which uses the same approach to building the helm source, always matched the whole string.  I never noticed this inconsistency because in helm-dictionary it is the desired behavior.

**Comment by tmalsburg** [comment]
Thank you, @jarg, this fixes it in my setup.  @plantarum, could you please test with the latest version?  Thank you.

**Comment by thierryvolpiatto** [comment]
Titus von der Malsburg <notifications@github.com> writes:

> @thierryvolpiatto did you recently make any changes to the matching
> algorithm?

Don't know what the issue is about, but no, no changes in how helm is
matching candidates.
Otherwise FYI helm doesn't support anymore plugins, IOW always use
helm-build-*-source to build your sources (or your own class +
helm-make-source of course).

-- 
Thierry

**Comment by plantarum** [comment]
Yes, that fixes the problem. Removing `helm-source-bibtex` broke org-ref, but after you reverted that with d6a98ac6f28d2a6a05e203115211c98333d40aca everything works as expected again.

Thanks for your prompt attention!

**Comment by tmalsburg** [comment]
Great, thanks everyone.
