### ISSUE TITLE
How to preserve the initial sorting order when narrowing down?

### ISSUE THREAD

**Issue by zzjjzzgggg** [tmalsburg/helm-bibtex#120]
This issue may be mostly related to `helm`, not `helm-bibtex`, but I'd like to hear your opinions.

I recently updated `helm`, and find that `helm-bibtex` no longer preserves the initial sorting order of bibliography entries when narrowing down. For example, my original bibliography entries are sorted decreasingly by year. If I search something in `helm-bibtex`, the resulting candidates are not sorted by year anymore (looks like by relevance). I still want `helm-bibtex` to preserve the initial sorting order, because I always want to read the latest paper.

I tried the method [here](https://github.com/emacs-helm/helm/issues/1492) to customize helm's default sorting function, but not working. Can you suggest some methods to preserve the initial order? 

Thanks!

**Comment by jagrg** [comment]
I cannot reproduce your problem. See if this [issue](https://github.com/tmalsburg/helm-bibtex/issues/117) is related.

**Comment by tmalsburg** [comment]
Hi @zzjjzzgggg, it's a little difficult to tell if the order is changing because the entries in my bib file have no particular order.  So far I have no evidence for that. But something definitely has changed: Now we're getting entries in which the match is discontiguous. I don't like this at all because in my experience every single of the discontiguous matches is a false alarm.

**Comment by zzjjzzgggg** [comment]
> Helm will try to search and sort according to highest match, from top to bottom. The best match is at the top, ...

So this is a feature of `helm`, not a bug. I think `helm` must have some configuration to allow people to change the sorting/ranking method, however, I don't known how to do this at present.

I provide a minimum running example to show this behavior.  In the scratch buffer with lisp-interaction-mode enabled, execute the following two pieces of code:

```
;; set the source
(setq h-src
      (helm-build-sync-source "test"
        :candidates
        '("Statistics & Estimation, EM 1998 A Gentle Introduction to the EM Algorithm.Part I: Theory Hemant D. Tagare article Tagare1998"
          "IEEE Transition on Information Theory # Statistics & Estimation, Fisher Information 1990 IEEE Transition on Information Theory Lower Bounds For Parametric Estimation with Constraints John D. Gorman and Alfred O. Hero article Gorman1990"
          "The Bell System Technical Journal # Statistics & Estimation 1948 The Bell System Technical Journal A Mathematical Theory of Communication C. E. Shannon article Shannon1948")
        ))

;; run helm
(helm :sources 'h-src)
```

The first just sets three strings as candidates, and the second runs a helm. In `helm`, you search "estimation", and you will find the order of candidates changes.

**Comment by tmalsburg** [comment]
I'm using the current version of Helm from Melpa and the order of entries does not change.  I also tried with `emacs -Q` to rule out any interaction with my personal configuration.

**Comment by zzjjzzgggg** [comment]
Hi @tmalsburg , thanks for your help.

I also find that with `emacs -Q`, the order indeed doesn't change. So I tried to find out what is the difference in my configuration and in `emacs -Q`.

I execute the following codes in my configuration and `emacs -Q` respectively. (in the scratch buffer with lisp-interaction-mode enabled)

```
;; set helm sources, the candidates are just three strings.
(setq h-src
      (helm-build-sync-source "test"
        :candidates
        '("Statistics & Estimation, EM 1998 A Gentle Introduction to the EM Algorithm.Part I: Theory Hemant D. Tagare article Tagare1998"
          "IEEE Transition on Information Theory # Statistics & Estimation, Fisher Information 1990 IEEE Transition on Information Theory Lower Bounds For Parametric Estimation with Constraints John D. Gorman and Alfred O. Hero article Gorman1990"
          "The Bell System Technical Journal # Statistics & Estimation 1948 The Bell System Technical Journal A Mathematical Theory of Communication C. E. Shannon article Shannon1948")
        ))

;; run helm
(helm :sources 'h-src)
```
If I search "estimation" in my configuration, the order changes; howeber,  the order doesn't change in `emacs -Q`.

I paste the output of executing `(setq h-src ...)`

under my configuration:
```
((name . "test")
 (candidates "Statistics & Estimation, EM 1998 A Gentle Introduction to the EM Algorithm.Part I: Theory Hemant D. Tagare article Tagare1998" "IEEE Transition on Information Theory # Statistics & Estimation, Fisher Information 1990 IEEE Transition on Information Theory Lower Bounds For Parametric Estimation with Constraints John D. Gorman and Alfred O. Hero article Gorman1990" "The Bell System Technical Journal # Statistics & Estimation 1948 The Bell System Technical Journal A Mathematical Theory of Communication C. E. Shannon article Shannon1948") 
 (action . identity) 
 (filtered-candidate-transformer helm-fuzzy-matching-default-sort-fn helm-fuzzy-highlight-matches) 
 (match helm-mm-exact-match helm-mm-match helm-fuzzy-match) 
 (fuzzy-match) 
 (header-line . "C-j: Do Nothing (keeping session)")
 (matchplugin))
```

with `emacs -Q`:
```
((name . "test")
 (candidates "Statistics & Estimation, EM 1998 A Gentle Introduction to the EM Algorithm.Part I: Theory Hemant D. Tagare article Tagare1998" "IEEE Transition on Information Theory # Statistics & Estimation, Fisher Information 1990 IEEE Transition on Information Theory Lower Bounds For Parametric Estimation with Constraints John D. Gorman and Alfred O. Hero article Gorman1990" "The Bell System Technical Journal # Statistics & Estimation 1948 The Bell System Technical Journal A Mathematical Theory of Communication C. E. Shannon article Shannon1948")
 (action . identity)
 (filtered-candidate-transformer helm-fuzzy-highlight-matches)
 (match helm-mm-exact-match helm-mm-match)
 (header-line . "C-j: Do Nothing (keeping session)")
 (matchplugin))
```
So you can see that, under my configuration, there is an additional `helm-fuzzy-matching-default-sort-fn`. I think this should be the reason.

I take a look at `helm.el`, and find that `helm-fuzzy-matching-default-sort-fn` is specified by a variable called `helm-fuzzy-sort-fn`. So If I set `(setq helm-fuzzy-sort-fn nil)`, `helm-fuzzy-matching-default-sort-fn` disappears and the order doesn't change anymore.

But new problem now comes out, if I config `(setq helm-fuzzy-sort-fn nil)`, I find that I even cannot use `M-x` to start helm. 

I will try to find out where goes wrong. 
Thank you!

btw, I am using spacemacs, and configure `helm-bibtex` as a layer.

**Comment by zzjjzzgggg** [comment]
Since this has nothing to do with `helm-bibtex`, and is not some big issue, I close it.

**Comment by zzjjzzgggg** [comment]
If you explicitly add an empty ":fuzzy-match" in you code, as follows, also solves my problem.

```
(defvar helm-source-bibtex
  (helm-build-sync-source "BibTeX entries"
    :init 'bibtex-completion-init
    :candidates 'bibtex-completion-candidates
    :filtered-candidate-transformer 'helm-bibtex-candidates-formatter
    :action (helm-make-actions
             "Open PDF file (if present)" 'helm-bibtex-open-pdf
             "Open URL or DOI in browser" 'helm-bibtex-open-url-or-doi
             "Insert citation"            'helm-bibtex-insert-citation
             "Insert reference"           'helm-bibtex-insert-reference
             "Insert BibTeX key"          'helm-bibtex-insert-key
             "Insert BibTeX entry"        'helm-bibtex-insert-bibtex
             "Attach PDF to email"        'helm-bibtex-add-PDF-attachment
             "Edit notes"                 'bibtex-completion-edit-notes
             "Show entry"                 'bibtex-completion-show-entry)
    :fuzzy-match
)
"Source for searching in BibTeX files.")
```

I don't know why this works. I also tried `:fuzzy-match nil`, `:fuzzy-match t`, and `:fuzzy-match ""`, none of them work.

**Comment by tmalsburg** [comment]
Hm, I must say that I don't understand this whole fuzzy matching business. Unfortunately, Helm's documentation isn't really helpful.
