### ISSUE TITLE
Error running timer: (error "Attempt to delete minibuffer or sole ordinary window") [2 times]

### ISSUE THREAD

**Issue by Enrico68** [tmalsburg/helm-bibtex#122]
Hello,

after update I start to get this error whenever I try make a search.

**Comment by tmalsburg** [comment]
Doesn't look like a problem with helm-bibtex because helm-bibtex doesn't have timers and also doesn't manipulate buffers and windows. That's done by the helm framework.  Perhaps post there.

**Comment by tmalsburg** [comment]
I also just updated from MELPA and can't reproduce the problem.
