### ISSUE TITLE
feature request: ability to insert into a default .bib file and set default search engine

### ISSUE THREAD

**Issue by yilihong** [tmalsburg/helm-bibtex#123]
Hello, I have two feature requests:

1) can we allow the ability to directly insert/append to a bib file on disk. Something similar to:
`(setq helm-bibtex-database-file "/path/to/refs.bib")
`

2) can we have something similar to: 
`(setq helm-bibtex-default-source "crossref")
`
so that the selected search engine is always on top

**Comment by tmalsburg** [comment]
1.) The following function appends the content of the current buffer to your helm-bibtex bib file.  Is this what you want? 

``` elisp
(defun append-to-bibliograpy ()
  (interactive)
  (append-to-buffer (save-current-buffer (find-file helm-bibtex-bibliography) (goto-char (point-max)) (current-buffer)) (point-min) (point-max)))
```

2.) You can redefine the customization variable `bibtex-completion-fallback-options` to change the order of search engines.  This is explained in the documentation, see [here](https://github.com/tmalsburg/helm-bibtex#online-databases).
