### ISSUE TITLE
Wrong capitalization in headings (title field) of notes

### ISSUE THREAD

**Issue by gujiaxi** [tmalsburg/helm-bibtex#126]
When taking notes, the generated heading (article title file) in org file is wrongly capitalized.
e.g., `HTTP over UDP: an Experimental Investigation of QUIC` turns to `Http over udp: an experimental investigation of quic` in org file.
Is it designed like this by purpose?

**Comment by jagrg** [comment]
You need to wrap those acronyms yourself in the bibtex entry:

`title = {{HTTP} over {UDP}: an Experimental Investigation of {QUIC}},`

**Comment by tmalsburg** [comment]
Yes, this was on purpose as it is folowing Latex/BibTeX conventions.
