### ISSUE TITLE
what is the key binding to edit a BibTeX entry in the dropdown?

### ISSUE THREAD

**Issue by yilihong** [tmalsburg/helm-bibtex#132]
wondering if there is a way to directly go to the BibTeX entry in the corresponding bib file from the dropdown?

For example, I want to edit the "Snir, Hitt" reference by going to the corresponding bib file.

<img width="848" alt="screenshot 2016-09-10 15 12 08" src="https://cloud.githubusercontent.com/assets/11595258/18413795/f887ea2c-7768-11e6-865a-288a1192199c.png">

**Comment by yilihong** [comment]
using C-z gives me these available actions:

<img width="346" alt="screenshot 2016-09-10 21 46 15" src="https://cloud.githubusercontent.com/assets/11595258/18415310/911571c2-77a2-11e6-896e-62a8efbea443.png">

**Comment by jagrg** [comment]
Why only six? I believe the one you want is f9.

**Comment by tmalsburg** [comment]
There are entries missing in your list of actions.  This is probably due to your configuration.

**Comment by yilihong** [comment]
Thank you @jagrg and @tmalsburg:

Indeed, I configured helm to only show 6 candidates. This the issue.
