### ISSUE TITLE
bibtex-completion-show-entry does not expand abbreviations defined in String entry

### ISSUE THREAD

**Issue by sewkokot** [tmalsburg/helm-bibtex#133]
Assume in lit.bib file I have this entry:

@Article{neuenhofer97jse,
  author =       {Neuenhofer, A. and Filippou, F. C.},
  title =        {Evaluation of nonlinear frame finite element models},
  journal =      jse,
  year =         1997,
  volume =   123,
  number =   7,
  number =   {958-966}}

and jse abbreviation is defined in other file journals.bib
@String{jse = {Journal of Structural Engineering}}

in bibtex-completion-bibliography I have both bib files. However after [f4] "Insert reference" the abbrev is not expanded:
- Neuenhofer, A., & Filippou, F. C. (1998). Evaluation of nonlinear
  frame finite-element models. jse, 124(6), 704–711.

Any idea how to fix it?

[Update: I meant "Insert reference" and not "Show entry"]

**Comment by jagrg** [comment]
That's a good point. You need `bibtex-expand-strings` set to t, but I think `bibtex-completion-apa-format-reference` would need to be changed as well. Here's a short version of how that might work:

```elisp
(defun bibtex-expand-journal (key)
  (let* ((key (bibtex-completion-normalize-candidate key))
	 (entry (bibtex-completion-get-entry key))
	 (ref (pcase (downcase (bibtex-completion-get-value "=type=" entry))
		("article"
		 (s-format
		  "${author} (${year}). ${title}. ${journal}, ${volume}(${number}), ${pages}.${doi}"
		  'bibtex-completion-apa-get-value entry)))))
    (with-temp-buffer
      (mapcar (lambda (x)
		(insert-file-contents x))
	      bibtex-completion-bibliography)
      (goto-char (point-min))
      (re-search-forward
       (concat "^@\\(" parsebib--bibtex-identifier
	       "\\)[[:space:]]*[\(\{][[:space:]]*"
	       (regexp-quote key) "[[:space:]]*,") nil t)
      (bibtex-beginning-of-entry)
      (let* ((journal (bibtex-text-in-string
		       (bibtex-search-forward-field "journal") t))
	     (s (replace-regexp-in-string (cdr (assoc "journal" entry))
					  journal ref))
	     (s (replace-regexp-in-string "\\([.?!]\\)\\." "\\1" s)))
	s))))
```

With the above, the journal should expand:

`(bibtex-expand-journal "neuenhofer97jse")`

**Comment by sewkokot** [comment]
Thank you for help. In fact bibtex-completion-apa-format-reference require some modification to enable string expanding. 

Option bibtex-expand-strings seems not to be used in helm-bibtex yet, so does nothing in this case.

After executing (bibtex-expand-journal "neuenhofer97jse") I get:

Neuenhofer, A., & Filippou, F. C. (1997). Evaluation of nonlinear
frame finite element models. Journal of Structural Engineering,
123(958-966), .
so it seems ${number} got lost.

**Comment by jagrg** [comment]
> so it seems ${number} got lost.

Your entry is not formatted properly.

**Comment by sewkokot** [comment]
You are right, thanks!
I should have noticed two 'number' fields and not 'pages' field.

**Comment by tmalsburg** [comment]
Hi, I think this should be handled in the underlying library for parsing BibTeX.  In our case that is parsebib.el.  Perhaps post a issue there?  Alternatively we could switch to parsing with bibtex.el but I suppose this would require some effort, especially for testing.

**Comment by tmalsburg** [comment]
Just had a look at bibtex.el which is part of Emacs.  It has pretty nifty facilities for handling bibtex and perhaps we should use that for parsing.

**Comment by tmalsburg** [comment]
Hi, I just reread the conversations about this, had a look at the code, and ran some basic tests.  All looks good.  I'm not a super expert for GitHub pull requests.  Can I merge this without you having to rebase on the most recent version of bibtex-completion.el?

**Comment by sewkokot** [comment]
Hi,
Thank you for your work on this library. I use the melpa repository to
update helm-bibtex, so from my part, there is no problem with merging it.
Kind regards.

**Comment by tmalsburg** [comment]
Hi @sewkokot, I intended to post the comment you replied to somewhere else.  Sorry.  The feature is now merged and you should be able to get the updated version later today from MELPA.
