### ISSUE TITLE
string transform before finding files

### ISSUE THREAD

**Issue by malb** [tmalsburg/helm-bibtex#135]
My bibtex keys have the form CONFERENCE:AuthorYear (they are from some database, so I cannot really change them). While locally my FS supports "CONFERENCE:AuthorYear.pdf" and "CONFERENCE:AuthorYear.org" those filenames break when syncing (e.g. using BT Sync). Could a function be added which performs string translations on bibtex keys before they are turned into filenames?

**Comment by tmalsburg** [comment]
Colons often have special meaning in paths (e.g., on Windows "C:\") and are therefore not considered legal characters.  If you want to translate the bibtex key, you can redefine the function `bibtex-completion-find-pdf`.  Just remove the colon or replace it by something else before anything else happens in this function.  Should be easy.

Hope that helps.
