### ISSUE TITLE
reference inserted with many (nil) text, anyway to change that?

### ISSUE THREAD

**Issue by zeltak** [tmalsburg/helm-bibtex#136]
Hi again

i notices recently (but was to lazy to open an issue :)) that many times i get references that have a lot of (nil), nil etc text in them , ie:

> - Landau, D., Novack, L., Yitshak-Sade, M., Sarov, B., Kloog, I.,
  Hershkovitz, R., Grotto, I., Karakis, I., .. (2015). Nitrogen
  dioxide pollution and hazardous household environment: what impacts
  more congenital malformations. Chemosphere, 139(nil),
  340–348. http://dx.doi.org/10.1016/j.chemosphere.2015.06.091

> 
> - Shi, L., Liu, P., Kloog, I., Lee, M., Kosheleva, A., & Schwartz,
>   J. (2016). Estimating daily air temperature across the southeastern
>   united states using high-resolution satellite data: a statistical
>   modeling study. Environmental Research, 146(nil),
>   51–58. http://dx.doi.org/10.1016/j.envres.2015.12.006

i assume its because the bib entry is missing that info. is there a way to make helm-bibtex just insert an empty space instead of putting nil?

thx alot

Z

**Comment by tmalsburg** [comment]
I can't reproduce this.  When some information is not present in the entry it is just omitted on my system.  Which version of emacs and the s package are you using?

**Comment by zeltak** [comment]
im was using emacs 24.5 but i can confirm it happens in emacs 25.1 i use now.

im not sure about the 's' package as i cant find it in my melpa/elpa packages?

here is an example bibtex entry i use and get the nil

`
@article{landau-2015-nitrog-dioxid,
  author =	 {D. Landau and L. Novack and M. Yitshak-Sade and
                  B. Sarov and I. Kloog and R. Hershkovitz and
                  I. Grotto and I. Karakis},
  title =	 {Nitrogen Dioxide Pollution and Hazardous Household
                  Environment: What Impacts More Congenital
                  Malformations},
  DATE_ADDED =	 {Sat Jul 2 08:12:44 2016},
  journal =	 {Chemosphere},
  year =	 {2015},
  volume =	 {139},
  number =	 {nil},
  pages =	 {340-348},
  doi =		 {10.1016/j.chemosphere.2015.06.091},
  url =		 {http://dx.doi.org/10.1016/j.chemosphere.2015.06.091},
  
}


happy to help debug this

best

Z
`

**Comment by tmalsburg** [comment]
`nil` is the value given in the BibTeX entry.  In this case, it's supposed to be printed in the reference.  :-)

**Comment by zeltak** [comment]
Oo..i guess its an org-ref issue that add that when cleaning the data

sorry about that

thx

Z

**Comment by tmalsburg** [comment]
No problem.

**Comment by jagrg** [comment]
I don't think org-ref does that. See `org-ref-clean-bibtex-entry-hook`.

**Comment by zeltak** [comment]
thx i discovered it was the  'doi-utils-add-bibtex-entry-from-doi'  that inserts all the nils. if anyone is interested i opened an issue:
https://github.com/jkitchin/org-ref/issues/295
