### ISSUE TITLE
Debugger entered--Lisp error: (void-variable helm-source-bibtex)

### ISSUE THREAD

**Issue by pawsen** [tmalsburg/helm-bibtex#138]
Hi,

I get the following error when I try to redefine the default behavior of C-j for helm-bibtex in the init-file.
```
(helm-delete-action-from-source "Insert citation" helm-source-bibtex)
(helm-add-action-to-source "Insert citation" 'bibtex-completion-insert-citation helm-source-bibtex 0)

Debugger entered--Lisp error: (void-variable helm-source-bibtex)
  (helm-delete-action-from-source "Insert citation" helm-source-bibtex)
```

If I however run `M-x helm-bibtex` first, then `helm-source-bibtex`exist and I can set the variables.
How can I set the default behavior from the init file?

Best regards,
Paw

**Comment by tmalsburg** [comment]
You have to redefine the actions after `(require helm-bibtex)` in your init file.

**Comment by pawsen** [comment]
Oh yes. I just thought the autoload command would make variables defined.
Thanks.
