### ISSUE TITLE
bibtex-completion-show-entry fails

### ISSUE THREAD

**Issue by gongzhitaao** [tmalsburg/helm-bibtex#141]
When I tried `bibtex-completion-show-entry` through the action menu <kbd>f9</kbd>, it fails, 

The Backtrace message is 

> Debugger entered--Lisp error: (wrong-type-argument listp "zhang2005-k")
car("zhang2005-k")
......
bibtex-completion-show-entry("zhang2005-k")
helm-execute-selection-action-1()
helm-execute-selection-action()

**Comment by tmalsburg** [comment]
I experienced the same after the last update. Just restart Emacs and it should work.

**Comment by gongzhitaao** [comment]
It still fails for me.  

I had `org-ref` installed also, but I looked into the `org-ref-helm-bibtex.el` code, it seems that it uses this function correctly.  Therefore, I kinda guess it is still the problem in `helm-bibtex`.

**Comment by ericdanan** [comment]
I can reproduce this with `org-ref-helm-bibtex`, and solve it by making a couple of changes in `org-ref-helm-bibtex.el` to adapt to the recent update of `helm-bibtex`. I sent a [PR](https://github.com/jkitchin/org-ref/pull/302) for this.

**Comment by tmalsburg** [comment]
Thank you, Eric.

**Comment by tmalsburg** [comment]
I'm assuming that this is solved now.
