### ISSUE TITLE
Consider using reftex-get-bibfile-list in additional to bibtex-completion-bibliography

### ISSUE THREAD

**Issue by xuhdev** [tmalsburg/helm-bibtex#153]
`reftex-get-bibfile-list` get the bib file for the current document:

> Return list of bibfiles for current document.
> When using the chapterbib or bibunits package you should either
> use the same database files everywhere, or separate parts using
> different databases into different files (included into the mater file).
> Then this function will return the applicable database files.

When editing `tex` files, this is a very good completion source in addition to the global ones.

**Comment by tmalsburg** [comment]
We already have that feature. See the relevant section in the documentation: https://github.com/tmalsburg/helm-bibtex#search-in-the-local-bibliography
