### ISSUE TITLE
Small issue when adding new references to an existing cite: command

### ISSUE THREAD

**Issue by jmburgos** [tmalsburg/helm-bibtex#155]
Hi Titus,
I hope you are doing well.  I am bothering you with a small annoyance that happens when adding a new reference to an existing cite command .  Here the underdash (_) indicates the position of the cursor.  Let's say you want to cite a couple of references.  You do helm-bibtex, and insert the first one, and get something like this.

parencite:Smith2008_

Then you do helm-bibtex again and insert the second one, and you get this:

parencite:Smith2008Smith2009,_

... with the comma that should separate both references placed after the second one.  If you remember to insert a blank space after the first reference

parencite:Smith2008 _

...you get the comma in the right place:

parencite:Smith2008,Smith2009.

Would it be possible to make helm-bibtex a bit smarter in this regard, so if you do not insert the space then the comma is placed in the right position?
Many thanks,

Julian

**Comment by tmalsburg** [comment]
Hi Julian, quick clarification question: are we talking about LaTeX?  I'm asking because I'm not familiar with this syntax (`parencite:key`).

**Comment by jmburgos** [comment]
Yes, it is LaTeX.  Parencite is the Biblatex command to insert author and year between parenthesis.

**Comment by tmalsburg** [comment]
I know parencite but I'm used to the syntax `\parencite{key}` instead of `parencite:key`.  I'll look into it.

**Comment by tmalsburg** [comment]
I can't reproduce the problem.  I tried this:

    \parencite{AuthorA2011_}

and then inserted another key.  The result was

    \parencite{AuthorA2011, AuthorB2011}

**Comment by jmburgos** [comment]
Sorry, I was not clear.  The syntax is LaTeX, but the buffer is in org-mode.  The parencite:key command gets exported to LaTeX as parencite{key}.

**Comment by jmburgos** [comment]
Actually I just realized that this is an org-ref issue rather than a helm bibtex issue.  If I turn off org-ref, the comma appears in the right place when adding citations.   Sorry for the noise.

**Comment by tmalsburg** [comment]
Yeah, helm-bibtex doesn't support this syntax, so the issue must arise in org-ref.  Have a great weel, Julian!
