### ISSUE TITLE
Symbol's function definition is void: s-blank-str?

### ISSUE THREAD

**Issue by billbrod** [tmalsburg/helm-bibtex#164]
This is probably something trivial that I'm missing, but I just recently updated `helm-bibtex` and found that, when trying to use `bibtex-completion-find-pdf-in-field` that I got an error: `Symbol's function definition is void: s-blank-str?` I found the bit of [code](https://github.com/tmalsburg/helm-bibtex/blob/master/bibtex-completion.el#L565) and changing it to `s-blank?` fixed the problem.

I had just used el-get to update all my libraries and just checked the README of [s-lib](https://github.com/caisah/s-lib), where it says the function is `s-blank?`. Why is it `s-blank-str?` in the `helm-bibtex`?

**Comment by tmalsburg** [comment]
I have both functions in the MELPA version of s.el and `s-blank` has a different meaning than `s-blank-str`.  The former tests whether the string is empty or nil and the latter tests whether the string is nil, empty, or contains only whitespace.

**Comment by tmalsburg** [comment]
Just checked the GitHub repo of s.el and it includes `s-blank-str`.  Perhaps, you have an outdated version?

**Comment by billbrod** [comment]
Whoops, yup that does it. I didn't realize my `s.el` was being handled by something other than el-get and so hadn't been updated. I fixed that and now it works without a problem, thanks!

**Comment by tmalsburg** [comment]
Cool, thanks for the update.
