### ISSUE TITLE
Unicode `bibtex-completion-pdf-symbol` cause line wrap

### ISSUE THREAD

**Issue by Yevgnen** [tmalsburg/helm-bibtex#165]
If `bibtex-completion-pdf-symbol` is set to a unicode char(default `⌘`), the candidates of the `helm-bibtex` buffer will have a slightly line wrap since the `⌘` is wider than normal chars even if I use a mono font. So does `bibtex-completion-notes-symbol`. Setting both to a english char solves the issue though, but I think when computing the wide of `${title:*}`, it would better to slightly minus `2 * some small margin`. Thanks !

<img width="1279" alt="screen shot 2016-12-13 at 3 16 55 pm" src="https://cloud.githubusercontent.com/assets/16749790/21131546/47c413ba-c14a-11e6-8143-3504d4897ecc.png">

**Comment by tmalsburg** [comment]
Strange, we are already subtracting a character to account for the wide symbols and that's usually enough.   I subtracted another char to increase the safety buffer. See 58dc08b8b8e6ea0c809052e082c867e05acef16a

**Comment by ssfrr** [comment]
I'm seeing this currently, but only for references that have _both_ a PDF and notes.

![image](https://user-images.githubusercontent.com/734386/39940048-054384fa-5526-11e8-9b31-c1d87b4af1a7.png)

I know there are a lot of variations based on people's fonts and setup - maybe a setting that determines how much space to add would let people customize?

**Comment by tmalsburg** [comment]
My recommendation is to use a monospaced font that is actually monospaced :-) More seriously, the titles of articles can in principle also contain unicode characters and adding a fixed buffer of one space (or whatever is necessary to avoid the line break in the screengrab) would not deal with that.  One easy fix (apart from switching the font) is to use another symbol for PDFs and notes.  These can be configured via `bibtex-completion-pdf-symbol` and bibtex-completion-notes-symbol`.
