### ISSUE TITLE
ivy-bibtex-display-transformer: Invalid function: -1

### ISSUE THREAD

**Issue by swarnendubiswas** [tmalsburg/helm-bibtex#168]
I am trying to use ivy-bibtex, and face the following error: `ivy-bibtex-display-transformer: Invalid function: -1`. I have tried to debug the validity of the .bib file (with say bibtex-validate and Jabref 3.8.1), but haven't found obvious errors. Evaluating `(bibtex-completion-candidates)` works.

I tried with `helm-bibtex` and "Insert citation" action works as expected.

**Comment by jmburgos** [comment]
I had the same problem when trying ivy-bibtex.
