### ISSUE TITLE
'helm-delete-action-from-source 'helm-add-action-to-source don't work in with-eval-after-load 'helm-bibtex

### ISSUE THREAD

**Issue by leezu** [tmalsburg/helm-bibtex#172]
```
(with-eval-after-load 'helm-bibtex
(helm-delete-action-from-source "Insert BibTeX key" helm-source-bibtex)
(helm-add-action-to-source "Insert BibTeX key" 'bibtex-completion-insert-key helm-source-bibtex 0)
    )
```

does not change the `helm-source-bibtex` when being placed in init.el. Calling it manually later via `eval-expression` does however work.
Using a timer is another work-around:

```
  (with-eval-after-load 'helm-bibtex
    (run-at-time "1 sec" nil
                 'helm-delete-action-from-source "Edit notes" helm-source-bibtex
     )
    (run-at-time "2 sec" nil
                 'helm-add-action-to-source "Edit notes" 'helm-bibtex-edit-notes helm-source-bibtex 0
                 )
    )
```

Is this behaviour expected? Is there a nicer way to solve the issue? It seems that `helm-source-bibtex` is being set to its default value after `with-eval-after-load 'helm-bibtex` is executed so that the changes defined therein are overwritten (?).

**Comment by tmalsburg** [comment]
Not an expert for `eval-after-load` but from looking at its documentation, I get the impression that it should work without the timers.  Not sure what is going on there.

**Comment by tmalsburg** [comment]
I think helm-bibtex is following helm best practices here.  For this reason, I doubt that this issue is related to helm-bibtex directly.  Will close this issue.  If you find that there is indeed a problem with helm-bibtex, feel free to reopen.
