### ISSUE TITLE
Options in fallback options if there is no match in the .bib file

### ISSUE THREAD

**Issue by DiogoFerrari** [tmalsburg/helm-bibtex#174]
I would like to have a single option, specifically, to search on-line using https://scholar.google.com/, when there is no match in my .bib file. The fallback options, however, include as the first option "Create new entry in <my-bib-file-name>.bib". I don't want to have that option because I never used it. How can I eliminate it from the fallback options and just let the option to search on google scholar?

**Comment by jagrg** [comment]
You would have to redefine the fallback function:

```
(defun bibtex-completion-fallback-candidates ()
  bibtex-completion-fallback-options)

(setq bibtex-completion-fallback-options
      '(("Google Scholar" . "https://scholar.google.com/scholar?q=%s")))
```

**Comment by DiogoFerrari** [comment]
Yes, of course. Thanks !
