### ISSUE TITLE
Customization group not working properly

### ISSUE THREAD

**Issue by plantarum** [tmalsburg/helm-bibtex#176]
Hi,

I've been trying to work out some customization values, and have run into a strange behaviour. After loading Emacs, if I try `M-x customize-variable bibtex-completion-`, the only available completions are `-display-formats` and `-notes-global-mode`. The list should be quite a bit longer, as there are a lot of customization options in bibtex-completion. 

I did some snooping, and found this in helm-bibtex:

```
(cl-loop
 for var in '("bibliography" "library-path" "pdf-open-function"
              "pdf-symbol" "format-citation-functions" "notes-path"
              "notes-template-multiple-files"
              "notes-template-one-file" "notes-key-pattern"
              "notes-extension" "notes-symbol" "fallback-options"
              "browser-function" "additional-search-fields"
              "no-export-fields" "cite-commands"
              "cite-default-command"
              "cite-prompt-for-optional-arguments"
              "cite-default-as-initial-input" "pdf-field")
 for oldvar = (intern (concat "helm-bibtex-" var))
 for newvar = (intern (concat "bibtex-completion-" var))
 do
 (defvaralias newvar oldvar)
 (make-obsolete-variable oldvar newvar "2016-03-20"))
```

Curiously, the two options that `customize-variable` knows about are not in this list, and none of the items in this list are known to `customize-variable`. So I think this code is part of the problem. Another curiosity, the problem goes away when I replace the `(defvaralias...) (make-obsolete-variable ...)` forms with the single form `(define-obsolete-variable-alias oldvar newvar "2016-03-20")`. I don't know why that should be, but with that change `M-x customize-variable` can now see all of the customizable variables in `bibtex-completion` again.

You can get to those variables via `M-x customize-group`, so it almost doesn't matter. Except that there were some small errors in some of the `defcustom` forms, and none of the changes I made to those definitions had any effect until I fixed the problem described above.

So, I'm reporting this as a bug, although I don't understand exactly what's going on here. I do have a small pull request to deal with the defcustom forms (switch from 'list to '(repeat string) for a few variables), but I'll hold onto that until I'm sure the problem described here is fixed (or at least understood).

Best,

Tyler

**Comment by tmalsburg** [comment]
Thank you very much for reporting this.  I had a look at `define-obsolete-variable-alias` and it also uses `defvaralias` and `make-obsolete-variable`.  However, there is some additional magic that I don't understand.  I suppose that must be making the difference.  I changed it to use `define-obsolete-variable-alias`.  Also, thanks in advance for the PR.

**Comment by plantarum** [comment]
Thanks for the speedy response!
