### ISSUE TITLE
fail to open Mendeley generated bibtex after recent update

### ISSUE THREAD

**Issue by cryoguy** [tmalsburg/helm-bibtex#179]
Everything works fine until a recent git pull.  Please help or advise (in the middle of paper submission) get following error:

/home/tony/Documents/bibliography/references.bib ...
In ‘BibTeX entries’ source: ‘bibtex-completion-candidates’ 
 (void-function s-blank-str\?)

an example citation:

`@article{Bellissent-Funel1989,
author = {Bellissent-Funel, M -C and Teixeira, J and Bosio, L and Dore, J C},
doi = {10.1088/0953-8984/1/39/024},
file = {:mnt/2nd{\_}BAY/papers/Bellissent-Funel et al. - 1989 - A structural study of deeply supercooled water - Journal of Physics Condensed Matter.pdf:pdf},
issn = {0953-8984},
journal = {Journal of Physics: Condensed Matter},
month = {oct},
number = {39},
pages = {7123--7129},
title = {{A structural study of deeply supercooled water}},
url = {http://stacks.iop.org/0953-8984/1/i=39/a=024?key=crossref.4c8f13c7fdd4d6818558d37339b50179},
volume = {1},
year = {1989}
}`

**Comment by tmalsburg** [comment]
Your s.el is outdated, see #164. 

On February 25, 2017 10:39:48 AM GMT+01:00, cryoguy <notifications@github.com> wrote:
>Everything works fine until a recent git pull.  Please help or advise
>(in the middle of paper submission) get following error:
>
>/home/tony/Documents/bibliography/references.bib ...
>In ‘BibTeX entries’ source: ‘bibtex-completion-candidates’ 
> (void-function s-blank-str\?)
>
>an example citation:
>
>`@article{Bellissent-Funel1989,
>author = {Bellissent-Funel, M -C and Teixeira, J and Bosio, L and Dore,
>J C},
>doi = {10.1088/0953-8984/1/39/024},
>file = {:mnt/2nd{\_}BAY/papers/Bellissent-Funel et al. - 1989 - A
>structural study of deeply supercooled water - Journal of Physics
>Condensed Matter.pdf:pdf},
>issn = {0953-8984},
>journal = {Journal of Physics: Condensed Matter},
>month = {oct},
>number = {39},
>pages = {7123--7129},
>title = {{A structural study of deeply supercooled water}},
>url =
>{http://stacks.iop.org/0953-8984/1/i=39/a=024?key=crossref.4c8f13c7fdd4d6818558d37339b50179},
>volume = {1},
>year = {1989}
>}`
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/tmalsburg/helm-bibtex/issues/179

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by cryoguy** [comment]
FYI:
my problem lies in the {\_} in the file path from my Mendeley generated file. Here is my fix:
add the following to line 548:
`for record = (replace-regexp-in-string "{\\|}\\|\\\\" "" record) `
all good now!

**Comment by tmalsburg** [comment]
A bit of a hack because it will break file names containing curly braces if I'm not mistaken.  But perhaps good enough for now.
