### ISSUE TITLE
displaying the other fields

### ISSUE THREAD

**Issue by DrWaleedAYousef** [tmalsburg/helm-bibtex#180]
I try, e.g., to display other fields as "language", "volume"; however it does not show up:

${author:36} ${title:40} ${year:4} ${=has-pdf=:1}${=has-note=:1} ${=type=:7} ${volume:4}

**Comment by tmalsburg** [comment]
This is explained in the documentation.  See [here](https://github.com/tmalsburg/helm-bibtex#customize-layout-of-search-results).

**Comment by DrWaleedAYousef** [comment]
I had tried all of that before sending you; it does not work. E.g., this is my .emacs:

(setq bibtex-completion-additional-search-fields '(keywords journal language))

(setq bibtex-completion-display-formats
      '((article       . "${language:20} ${=has-pdf=:1} ${year:4} ${author:20} ${title:20} ${volume:20}")
      (book        . "${=has-pdf=:1}${=has-note=:1} ${=type=:3} ${year:4} ${author:36} ${title:*} Chapter ${chapter:32}")
      (t             . "${=has-pdf=:1}${=has-note=:1} ${=type=:3} ${year:4} ${author:36} ${title:*}")))

and this is a simple .bib

@article{waleed2017thisistitle,
  author =	 {Waleed},
  journal =	 {PAMI, IEEE},
  language =	 {CAD Mammography},
  title =	 {This Is the Title},
  year =	 2017,
  volume = 17
}

However, the field "language" and "volume" never show up; what shows up is spaces!!

**Comment by tmalsburg** [comment]
Read the section to the end.  It says that you have to add all fields that you'd like to display to the variable  `bibtex-completion-additional-search-fields`.

**Comment by DrWaleedAYousef** [comment]
Oh, it seems that I have to add all fields as you said to be able to display them EVEN IF I did not search! Thanks so much

**Comment by tmalsburg** [comment]
Yes, helm-bibtex only loads the standard fields and the fields in that variable.  It's a bit confusing admittedly.
