### ISSUE TITLE
converting Mendely file names and their correspondence on disk

### ISSUE THREAD

**Issue by DrWaleedAYousef** [tmalsburg/helm-bibtex#189]
Now, I am using plain bib files along with helm-bibtex; wonderful. However, my library was built with Mendely. A nasty thing is that the "file" field looks like, e.g.,

  file =	 {:home/wyousef/MyDocuments/Phd/PDF/Gaulton et al. - 2012 - ChEMBL A
                  large-scale bioactivity database for drug
                  discovery(2).pdf:pdf;:home/wyousef/MyDocuments/Phd/PDF/Gaulton et al. - 2012
                  - ChEMBL A large-scale bioactivity database for drug discovery.pdf:pdf},

Can you provide a function that scans all the file names and remove the spaces; and accordingly rename the corresponding files on disk. The problem is that when I go with cursor over the file name and try to open it using helm C-x C-f it cannot see it because of the spaces, new lines, etc..

Thanks so much

**Comment by DrWaleedAYousef** [comment]
Or alternatively, 

in helm-bibtex, pressing F3 on an entry suggests the PDFs existing in the "file" field even if they are in Mendely format. How can I do the same but from with the bib file while the cursor is on an entry.

**Comment by tmalsburg** [comment]
My memory was that we already have support for Mendeley's format.  See section (PDF files)[https://github.com/tmalsburg/helm-bibtex#pdf-files] in the documentation.

**Comment by DrWaleedAYousef** [comment]
I mean while I am in the bib buffer at a particular entry.

On Apr 20, 2017 10:16 PM, "Titus von der Malsburg" <notifications@github.com>
wrote:

My memory was that we already have support for Mendeley's format. See
section (PDF files)[https://github.com/tmalsburg/helm-bibtex#pdf-files] in
the documentation.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmalsburg/helm-bibtex/issues/189#issuecomment-295889858>,
or mute the thread

**Comment by tmalsburg** [comment]
Ah, I see. Such a function would be useful but I don't have time to write it.  Maybe ask on https://emacs.stackexchange.com/ I'll close this issue because it's not about an issue in helm-bibtex.

**Comment by DrWaleedAYousef** [comment]
Thanks so much for reply. One third solution is how to call helm-bibtex
from a current bib file to show directly the current entry of the bib file.

**Comment by tmalsburg** [comment]
See #121 and #169 .
