### ISSUE TITLE
Taking actions after opening PDF

### ISSUE THREAD

**Issue by jschwab** [tmalsburg/helm-bibtex#191]
Hello,

Frequently, I use helm-bibtex to find a bibtex entry and then open the associated PDF.  Subsequently, I want to take another action associated with that paper (e.g., attach it to an email).  Right now, I return to the `*helm-bibtex*` buffer, re-do the search, and then take the desired second action.

Is there a better way to do this?  Is there some way that I can take helm-bibtex actions from the PDFview buffer?

Thanks,
Josiah

P.S.  If there's a better place to ask this question, let me know; I'm not aware of a mailing list or forum.

**Comment by jagrg** [comment]
> Right now, I return to the *helm-bibtex* buffer, re-do the search, and then take the desired second action.

No need to re-do the search. You can use M-x helm-resume (or C-x c b).

**Comment by jschwab** [comment]
Perfect.  That's exactly what I wanted.  Thanks!
