### ISSUE TITLE
displaying date field as alternative to year in search results?

### ISSUE THREAD

**Issue by bdarcus** [tmalsburg/helm-bibtex#192]
I'm not sure if this is a FR, or a request for support/help.

I have a biblatex file, where a lot of the entries use the `date` field, rather than `year`.

I guess I'm suggesting either:

1. for helm-bibtex to fallback to date if year isn't present
2. if not, then how would I modify the example customization from the README to do the same (pasted below)?

```
'((t . "${author:36} ${title:*} ${year:4} ${=has-pdf=:1}${=has-note=:1} ${=type=:7}"))
```

**Comment by jagrg** [comment]
I copied the author/editor part to get the year/date, and it worked. You also have to add the date field to `bibtex-completion-additional-search-fields`.

```
(setq bibtex-completion-additional-search-fields '(date))

(defun bibtex-completion-format-entry (entry width)
  "Formats a BibTeX ENTRY for display in results list. WIDTH is
the width of the results list. The display format is governed by
the variable `bibtex-completion-display-formats'."
  (let* ((format
          (or (assoc-string (bibtex-completion-get-value "=type=" entry)
                            bibtex-completion-display-formats-internal
                            'case-fold)
              (assoc t bibtex-completion-display-formats-internal)))
         (format-string (cadr format)))
    (s-format
     format-string
     (lambda (field)
       (let* ((field (split-string field ":"))
              (field-name (car field))
              (field-width (cadr field))
              (field-value (bibtex-completion-get-value field-name entry)))
         (when (and (string= field-name "author")
                    (not field-value))
           (setq field-value (bibtex-completion-get-value "editor" entry)))

	 ;; vvvvvv
         (when (and (string= field-name "year")
                    (not field-value))
           (setq field-value (bibtex-completion-get-value "date" entry)))
	 ;; ^^^^^^	 

	 (setq field-value (bibtex-completion-clean-string (or field-value " ")))
         (when (member field-name '("author" "editor"))
           (setq field-value (bibtex-completion-shorten-authors field-value)))

	 ;; vvvvvvv
         (when (member field-name '("year" "date"))
           (setq field-value (bibtex-completion-shorten-authors field-value)))
	 ;; ^^^^^^^

	 (if (not field-width)
             field-value
           (setq field-width (string-to-number field-width))
           (truncate-string-to-width
            field-value
            (if (> field-width 0)
                field-width
              (- width (cddr format)))
            0 ?\s)))))))
```

**Comment by bdarcus** [comment]
Thanks!

**Comment by tmalsburg** [comment]
I'm not going to include this in helm-bibtex because I think this use case is too rare. But thanks, @jagrg, for providing the code. It's useful to have this.

**Comment by bdarcus** [comment]
Totally reasonable @tmalsburg - thanks anyway.

I finally got around to adding the code to my config, and it correctly searches on the date field. But I still don't see the date values in my results in column. 

![screenshot from 2017-05-21 11-34-14](https://cloud.githubusercontent.com/assets/1134/26285224/9684a66c-3e19-11e7-99e3-d75e54d33e4f.png)

**Comment by jagrg** [comment]
You have to add the code *after* helm-bibtex. You might also consider replacing all date fields in the file.

On 21 May 2017, bdarcus <notifications@github.com> wrote:

> Totally reasonable @tmalsburg - thanks anyway.
>
> I finally got around to adding the code to my config, and it correctly searches on the date field. But I still don't
> see the date values in my results in column.
>
> screensh
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Jonathan
