### ISSUE TITLE
Getting BibTex entries of all papers in a given journal volume or conference proceeding.

### ISSUE THREAD

**Issue by mgoldenbe** [tmalsburg/helm-bibtex#193]
I apologize for spamming this forum, but I hope that people here might know the answer to this question. I am writing a reference manager and would like to enable the user to get all the BibTex entries of the papers in a given journal volume or conference proceeding. Since many indexing services managed to get those entries, I naively supposed that journals and conferences provided a standard feed of some kind. To my surprise, I was not able to find any such feeds.

So, do you have an idea of how I could go about getting all the BibTex entries of the papers in a given journal volume or conference proceeding?

**Comment by mgoldenbe** [comment]
I see that my post was not welcome. I apologize again.

**Comment by tmalsburg** [comment]
Sorry, there are better places to ask such questions.  This issue tracker is for problems related to helm-bibtex.  I also don't have an answer to your question.
