### ISSUE TITLE
Allow relative path in file field for PDF

### ISSUE THREAD

**Issue by heartnheart** [tmalsburg/helm-bibtex#194]
By default, helm-bibtex will search PDF files under `bibtex-completion-library-path` which is great. 
However, I would organize PDF file using subfolders under that folder, and put the `.bib` file in the top folder with `file` field using relative path relative to the `.bib` file. For example:

 C:\TEMP\MYREFERENCES
│  ref.bib
├─groupA
│　　 A.pdf
└─groupB
　　　B.pdf

and I have the following content in ref.lib

>@Article{bibkeyA,
>  author       = {authorA},
>  title        = {titleA},
>  file         = {groupA/A.pdf}
>}
>@Article{bibkeyB,
>  author       = {authorB},
>  title        = {titleB},
>  file         = {groupB/B.pdf}
>}

Note the relative path in the file field. helm-bibtex cannot find the PDF now and the problem is that in function `bibtex-completion-find-pdf-in-field`, [https://github.com/tmalsburg/helm-bibtex/blob/master/bibtex-completion.el#L539](url), we have
```
((-any 'f-file? (--map (f-join it (f-filename value)) (-flatten bibtex-completion-library-path))) (-filter 'f-file? (--map (f-join it (f-filename value)) (-flatten bibtex-completion-library-path))))
```
I'm wondering what's the purpose of `(f-filename value)`, by removing it, I have 
```
 ((-any 'f-file? (--map (f-join it value) (-flatten bibtex-completion-library-path))) (-filter 'f-file? (--map (f-join it value) (-flatten bibtex-completion-library-path))))
```
which solves the problem.

Could you please remove the unnecessary `f-filename` function to allow for better flexibility? Thanks!

**Comment by tmalsburg** [comment]
Hm, I suppose there was a reason for adding `f-filename` but I forgot what it was.   Can't you simply use absolute paths?  Or use the [Mendeley/JabRef/Zotero syntax](https://github.com/tmalsburg/helm-bibtex#pdf-files)?

**Comment by heartnheart** [comment]
I cannot use absolute path as I need to move the folder around. 

I've tried with the first of Mendeley/JabRef/Zotero format you mentioned earlier which is:
> File = {/path/to/article.pdf}
and it did not work for relative path so I thought they only works for absolute paths.

But the following format works for me (with an extra ':' in the beginning) now
> File = {:/path/to/article.pdf}

Thanks for your help!

**Comment by tmalsburg** [comment]
I think Mendeley format is:
```
   File = {:/path/to/article.pdf:PDF}
```
It's a pure coincidence that your format with just one `:` at the beginning is working.  Better switch to the correct format because we may not support the other in the future.
