### ISSUE TITLE
bibtex-completion-notes-template-one-file - Can not set a custom property

### ISSUE THREAD

**Issue by brianmcgillion** [tmalsburg/helm-bibtex#197]
This is probably not a bug, rather user error when trying to set a template in my init.

`setq bibtex-completion-notes-template-one-file
      (format
       "\n** ${author} (${year}): ${title}\n  :PROPERTIES:\n  :Custom_ID: ${=key=}\n  :URL: ${url}\n  :INTERLEAVE_PDF: %s\n  :END:\n\n" (file-name-nondirectory "${file}")))`

I would expect this to insert just the filename into the INTERLEAVE_PDF string. However, it inserts the absolute path (as is stored in the .bib file), so the exact value of "${file}"
 
Testing using a hardcoded string the following will return "some file.pdf" as expected

`(setq bibtex-completion-notes-template-one-file
      (format
       "\n** ${author} (${year}): ${title}\n  :PROPERTIES:\n  :Custom_ID: ${=key=}\n  :URL: ${url}\n  :INTERLEAVE_PDF: %s\n  :END:\n\n" (file-name-nondirectory "/m/some file.pdf")))`

Any ideas would be really appreciated. Thanks

**Comment by tmalsburg** [comment]
`format` doesn't use `${name}` notation.  See the documentation of the function.  I think you are looking for `s-format` from s.el.
