### ISSUE TITLE
bibtex-completion doesn't work in Emacs 26

### ISSUE THREAD

**Issue by chrikoehn** [tmalsburg/helm-bibtex#198]
Somehow the alias `acons` (for `cl-acons`) isn't defined in Emacs 26 (I'm using 26.0.50) anymore. I don't know whether this is a bug or a feature in Emacs itself. Anyway, the alias was originially defined for backwards-compatibility with `cl.el` AFAIK and therefore I suggest to replace it with `cl-acons`.

**Comment by tmalsburg** [comment]
Merged.
