### ISSUE TITLE
does helm-bibtex support finding duplicates and changing order of entries

### ISSUE THREAD

**Issue by kirk86** [tmalsburg/helm-bibtex#200]
Hi, thanks for this great package. I was wondering if `helm-bibtex` supports finding duplicates. Since most of the time we deal with large .bib files it would be useful to have some functionality such as finding duplicates by content and not only by `cite-key`. The second thing I would like to ask is if it is possible to rearrange the entries from inside the `helm-bibtex` buffer. For instance select and entry and with key arrows move it up or down in the desired position. That would require moving the original entry in the `.bib` file.

**Comment by tmalsburg** [comment]
Helm-bibtex does not support finding duplicates and this seems actually like a non-trivial problem unless you mean by duplicate that two entries have identical content in all fields which is the boring case.  However, if you want to write something yourself could build on the infrastructure in helm-bibtex or you could use parsebib, the package we're using to read bibtex. 

Helm-bibtex also doesn't do the second thing you're asking (rearranging entries).  Generally, helm-bibtex (at this time) is only meant to read a bibliography not to change it.  If you'd like to have editing capabilities, one question is going to be whether the helm framework supports this (not to my knowledge, but I may be wrong).

**Comment by kirk86** [comment]
@tmalsburg Hi, thanks for the response. I was hoping maybe these were meant to be some feature requests. 

> if you want to write something yourself could build on the infrastructure in helm-bibtex or you could use parsebib

I plan to but my lisp skills are not at that level yet. BTW do you know any package that provides those capabilities. Maybe there is something equivalent and I've missed it.

**Comment by tmalsburg** [comment]
Feature requests are fine but it's very unlikely that I will work on these features, so I thought I should give you some pointers.  Re other packages for editing, check out ebib.  Personally, I prefer to edit my bib-files by hand.
