### ISSUE TITLE
Rename all files in the file field of a Bibtex exported from Mendely

### ISSUE THREAD

**Issue by DrWaleedAYousef** [tmalsburg/helm-bibtex#201]
The bibtex exported from Mendely is terrible, especially the "file" field. I want to write a lisp function the scans the bibtex, and rename all PDFs of an entry to be KEYa, KEYb, .... However, I am not that good in LISP. Any help?

**Comment by tmalsburg** [comment]
`bibtex-completion-cache` contains all entries.  You have to iterate over those and for each entry retrieve the current PDF name with `bibtex-completion-find-pdf-in-field`.  Then create a new name and rename the file (use functions from f.el if convenient). Finally to have to search the old file name in the .bib file and replace it with the new file name.  Hope this helps.

**Comment by DrWaleedAYousef** [comment]
Thanks so much, although it seems to be a big job for me.

**Comment by tmalsburg** [comment]
Learning to hack elisp is fun and once you know the basics it can also increase your productivity because it allows you to tailor Emacs to your personal needs.  If I had more time, I'd look into it but unfortunately I don't.  Good luck!
