### ISSUE TITLE
UK Google scholar does not provide BibTeX link

### ISSUE THREAD

**Issue by drghirlanda** [tmalsburg/helm-bibtex#202]
I noticed that helm-bibtex seems to use scholar.google.co.uk for Google Scholar searches. The .com site also adds a BibTeX import link that I find handy, but the .co.uk site seems to not have that link. Would it be possible to switch to scholar.google.com?

**Comment by tmalsburg** [comment]
I can't replicate this.  The .co.uk version looks exactly the same as .com for me.  Is it possible that you're logged in on .com but not on .co.uk and that you're seeing the difference between that?

**Comment by drghirlanda** [comment]
I figured it out... .co.uk provides a "Cite" link which I had not seen (my bad), and that brings up a selection of various reference formats. For me, however, .com only includes an "Import into BibTeX" link, so the .co.uk version is actually better. Maybe I have configured somewhere to only show the BibTeX link, but I can't figure out where... Thanks for your time and a great software!

**Comment by tmalsburg** [comment]
Thanks for the update. Glad you found a solution.
