### ISSUE TITLE
Sort order

### ISSUE THREAD

**Issue by jag2** [tmalsburg/helm-bibtex#21]
Ebib sorts the bib file alphabetically (a-z), but helm-bibtex reverses the order (z-a). Any idea how to fix this?

**Comment by rjww** [comment]
You can un- or re-reverse the candidate order by advising the appropriate formatter function, intercepting the list of candidates passed from `bibtex-completion-candidates`. For example, if you're using Helm:

````emacs-lisp
(defun -helm-bibtex--reverse-candidates (orig-fun &rest args)
  (setcar args (reverse (car args)))
  (apply orig-fun args))

(advice-add 'helm-bibtex-candidates-formatter
            :around #'-helm-bibtex--reverse-candidates)
````

I know this is an old (and closed) issue, but I'm putting this here in case anyone comes through looking for a solution. I assume some people are like me in keeping their `.bib` files sorted, e.g. to avoid `crossref` conflicts.

**Comment by tmalsburg** [comment]
Thank you, @rjww.  One thing to note is that this solution only reverses the list of top-500 entries, so the list of entries is going to start somewhere in the middle of your BibTeX file not at the beginning.  The following code reverses the whole list:

``` elisp
(advice-add 'bibtex-completion-candidates
            :around (lambda (orig-fun &rest args)
                      (reverse (apply orig-fun args))))
```

**Comment by jagrg** [comment]
Nice. We can also do it interactively.

```elisp
(defun helm-bibtex-reverse-candidates (arg)
  (interactive "P")
  (with-selected-window (helm-window)
    (if arg
	(advice-remove 'bibtex-completion-candidates
		       '(lambda (orig-fun &rest args)
			  (reverse (apply orig-fun args))))
      (advice-add 'bibtex-completion-candidates
		  :around (lambda (orig-fun &rest args)
			    (reverse (apply orig-fun args)))))
    (helm-refresh)
    (helm-goto-line 1)))
     
(define-key helm-map (kbd "<f9>") 'helm-bibtex-reverse-candidates)
```

**Comment by tmalsburg** [comment]
Nice!

My earlier code was unnecessarily complicated.  The code below does the same in fewer words:

``` elisp
(advice-add 'bibtex-completion-candidates
            :filter-return 'reverse)

```

**Comment by rjww** [comment]
Thanks for the improvements guys!
