### ISSUE TITLE
missing year in bibtex entry causes error

### ISSUE THREAD

**Issue by jmburgos** [tmalsburg/helm-bibtex#212]
Hi Titus,

I upgraded to  ivy-bibtex version  20171002.907 and when I tried to load my bibliography I got this error:

Parsing bibliography file /home/julian/Documents/org_files/references.bib ...
Resolving cross-references ...
split-string: Wrong type argument: stringp, nil

After doing some detective work I figured out that the issue was triggered by a bibtex entry without year or date.  As an example, ivy-bibtex works fine with a .bib file with this single bibtex entry: 

```
@article{Aarts2012,
  author       = {Aarts, Geert and Fieberg, John and Matthiopoulos, Jason},
  journaltitle = {Methods in Ecology and Evolution},
  number      = 1,
  pages	    = {177--187},
  title	       = {Comparative Interpretation of Count, Presence--absence and Point Methods for Species Distribution Models},
  volume       = 3,
  year	       = 2012,
}  
```

But if you remove the line with the year field like this, ivy-bibtex gives the error I mentioned above:

```
@article{Aarts2012,
  author       = {Aarts, Geert and Fieberg, John and Matthiopoulos, Jason},
  journaltitle = {Methods in Ecology and Evolution},
  number       = 1,
  pages	       = {177--187},
  publisher    = {Wiley Online Library},
  title	       = {Comparative Interpretation of Count, Presence--absence and Point Methods for Species Distribution Models},
  volume       = 3,
 }
```
Maybe this has to do with the new feature of using the date field if the year is not defined?  What happens if neither field is defined?

**Comment by tmalsburg** [comment]
Thanks for reporting. Should be fixed now.
