### ISSUE TITLE
ivy-bibtex gives different hits depending on order of terms

### ISSUE THREAD

**Issue by eeenilsson** [tmalsburg/helm-bibtex#215]
Ivy-bibtex gives different hits depending on order of terms, ie "zhang hemoglobin" gives a different number of list items than "hemoglobin zhang".

**Comment by tmalsburg** [comment]
I'm not using ivy-bibtex myself, it was contributed by a user.  However, my understanding is that the search logic is inherited from ivy.  So I think this may not be an ivy-bibtex issue.  Perhaps try whether the order of search terms also affects the results in other ivy search functions?

**Comment by ericdanan** [comment]
Yes I confirm this is about ivy in general and not ivy-bibtex specifically.

**Comment by tmalsburg** [comment]
Thanks you, Eric. @eeenilsson, please open an issue for ivy.
