### ISSUE TITLE
All actions insert citation rather than open pdfs etc

### ISSUE THREAD

**Issue by jdtonkin** [tmalsburg/helm-bibtex#218]
No matter what I do in helm-bibtex, the result is an inserted citation (i.e. Return, C-j, F1). Tab doesn't bring up the options either. Any ideas? I shouldn't need to go through and change all the default options should I as this comes as part of the package?

This is the relevant stuff in my init: 

(setq reftex-default-bibliography '("~/gdrive/Research/org/references/articles.bib"))

  (setq org-ref-bibliography-notes "~/gdrive/Research/org/references/articles.org"
	org-ref-default-bibliography '("~/gdrive/Research/org/references/articles.bib")
	org-ref-pdf-directory "~/gdrive/Research/org/references/pdfs/")

      (setq bibtex-completion-bibliography '("~/gdrive/Research/org/references/articles.bib")
	    bibtex-completion-library-path '("~/gdrive/Research/org/references/pdfs")
  )

   ;; open pdf with system pdf viewer (works on mac)
    (setq bibtex-completion-pdf-open-function
      (lambda (fpath)
	(start-process "open" "*open*" "open" fpath)))

**Comment by jdtonkin** [comment]
I should note that when I click on the citation inserted from helm-bibtex, it brings up all the helm-bibtex options and I can open the pdf from there. It's just the options in the main menu that don't work.

**Comment by jdtonkin** [comment]
Got it! Sorry about this. My issue. I forgot that when I set up helm a long time ago, I remapped tab as follows: (define-key helm-map (kbd "<tab>") 'helm-execute-persistent-action). So now tab works as it should in the helm-bibtex menu.

**Comment by tmalsburg** [comment]
Glad that you could fix it.  (And sorry for the slow response.)
