### ISSUE TITLE
cyclic function indirection conflict for show-all with emacs< 25.1 

### ISSUE THREAD

**Issue by jonmoore** [tmalsburg/helm-bibtex#225]
Hi,

For emacs < 25.1 I think a recent change creates a circularity between outline-show-all and show-all.  This results in a hang or a cyclic-function-indirection error when either is invoked.

Specifically, https://github.com/tmalsburg/helm-bibtex/commit/bd089342a5000fd5477d0eae98be5b2fdb317adb adds the alias below

```lisp
(when (version< emacs-version "25.1")
  (defalias 'show-all 'outline-show-all))
```
while org-mode's org-compat.el has 
```lisp
(when (< emacs-major-version 25)
  ;; ...
  (defalias 'outline-show-all 'show-all)
```
I think that either using the same defalias that org does or removing the alias and using the obsolete "show-all" name would resolve this.

**Comment by tmalsburg** [comment]
Thanks for the report.  I removed the defalias.
