### ISSUE TITLE
Sudden break in helm-bibtex after Archlinux update

### ISSUE THREAD

**Issue by DrWaleedAYousef** [tmalsburg/helm-bibtex#229]
All of the sudden, I get this:
```helm-M-x: Wrong type argument: stringp, nil```

**Comment by tmalsburg** [comment]
Everything works fine on my setup.  Perhaps try reinstalling helm-bibtex from MELPA?

**Comment by DrWaleedAYousef** [comment]
Already have done that! Same problem

**Comment by tmalsburg** [comment]
If you can find a way to reliably reproduce the problem, I'll be happy to look into it.

**Comment by DrWaleedAYousef** [comment]
Thanks so much for your patience. I did this; 
```
M-x toggle-debug-on-error
M-x helm-bibtex

Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  looking-at(nil)
  org-heading-components()
  org-element-headline-parser(253 t)
  org-element--current-element(253 headline first-section nil)
  org-element--parse-elements(2 253 first-section nil headline nil (org-data nil))
  org-element-parse-buffer(headline)
  bibtex-completion-candidates()
  helm-bibtex(nil)
  funcall-interactively(helm-bibtex nil)
  call-interactively(helm-bibtex record nil)
  command-execute(helm-bibtex record)
  helm-M-x(nil #("helm-bibtex" 0 11 (match-part "helm-bibtex")))
  funcall-interactively(helm-M-x nil #("helm-bibtex" 0 11 (match-part "helm-bibtex")))
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)
```

**Comment by tmalsburg** [comment]
Since the problem doesn't occur on my system, I would need a minimal reproducible example.  I.e. a minimal configuration and bibliography that reliably produce the error.

**Comment by DrWaleedAYousef** [comment]
Thanks so much; your reply gave me a clue to re-parse my bib, configs, ...etc. I did not find an error! However, after doing that the problem gone (again without finding the error, which sound so funny). Anyway, thank so much.

**Comment by tmalsburg** [comment]
Glad you could fix it.
