### ISSUE TITLE
Symbol’s function definition is void: org-element-parse-buffer 

### ISSUE THREAD

**Issue by heartnheart** [tmalsburg/helm-bibtex#230]
`org-element-parse-buffer` is called by `(bibtex-completion-candidates)` which is in turn called by `(helm-bibtex)`. But this function is not autoloaded, and if I call `(helm-bibtex)` without org-mode loaded already, such error occurred. 

One solution is adding`(require 'org-element)` in file `bibtex-completion.el`.  Thanks!

**Comment by tmalsburg** [comment]
Fixed in c18ce5b4fa1c6730f4aa1df4bf86466af1d851e1.  Thank you!
