### ISSUE TITLE
Provide information about how to configure ivy for ivy-bibtex

### ISSUE THREAD

**Issue by fbkarsdorp** [tmalsburg/helm-bibtex#236]
`bibtex-completion-candidates` creates search strings in which bibtex fields are ordered according to their order of appereance in a bibtex file. Unless one is very strict about ordering all entries in exactly the same way, this might lead to unexpected orderings, which, problematically, don't comply with ivy's default *ordered* regex builder. This problem can be resolved by using the (slightly slower) `ivy--regex-ignore-order` with `ivy-bibtex`, like so:

```lisp
(setq ivy-re-builders-alist
      '((ivy-bibtex . ivy--regex-ignore-order)
        (t . ivy--regex-plus)))
```

It took me a while to sort this out, so perhaps it's a good idea to add it to the readme?

**Comment by tmalsburg** [comment]
Hi, happy to include this information in the documentation.  Unfortunately I'm not familiar with ivy at all (the ivy-related code was contributed by a user).  Would you mind making a PR for README.org?
