### ISSUE TITLE
fail to open pdf file name with special character?

### ISSUE THREAD

**Issue by cryoguy** [tmalsburg/helm-bibtex#238]
Anyone knows a solution to this?  If there a special character in my pdf file name, helm-bibtex fails to open it.  PDF file with special characters works fine.

`@article{urbanyi1996,
author = {Magyary, I. and Urb{\'{a}}nyi, B. and Horv{\'{a}}th, L.},
doi = {10.1111/j.1439-0426.1996.tb00072.x},
file = {:mnt/2nd{\_}BAY/papers/Magyary, Urb{\'{a}}nyi, Horv{\'{a}}th - 1996 - Cryopreservation of common carp (Cyprinus carpio L.) sperm I. The importance of oxygen supply - Jou.pdf:pdf},
issn = {0175-8659},
journal = {Journal of Applied Ichthyology},
month = {jul},
number = {2},
pages = {113--115},
title = {{Cryopreservation of common carp (Cyprinus carpio L.) sperm I. The importance of oxygen supply}},
url = {http://doi.wiley.com/10.1111/j.1439-0426.1996.tb00072.x},
volume = {12},
year = {1996}
}`

**Comment by tmalsburg** [comment]
We've discussed this previously.  The problem is that your bibliography software is escaping special characters (e.g. `{\'{a}}`).  We'd basically have to implement LaTeX escaping rules which sounds like a lot of work.  Better to use a bibliography manager that does escape those characters. Escaping them is to my knowledge unnecessary.

**Comment by jagrg** [comment]
It is not necessary in some cases. For example, numerical styles apparently do not need to copy the unicode characters elsewhere, while alphabetical ones do (and fail) (quoted from a recent discussion in org-ref about umlauts).

In any case, the [citeproc-el](https://github.com/andras-simonyi/citeproc-el) library does these kinds of conversions, so if you have that installed, you could advice the `bibtex-completion-find-pdf-in-field` to replace escaped characters.

```
(advice-add 'bibtex-completion-find-pdf-in-field :filter-return
	    (lambda (path)
	      (citeproc-bt--to-csl path)))
```

returns:

`":mnt/2nd_BAY/papers/Magyary, Urbányi, Horváth - 1996 - Cryopreservation of common carp (Cyprinus carpio L.) sperm I. The importance of oxygen supply - Jou.pdf:pdf"`

Now I know why you're the cryoguy.
