### ISSUE TITLE
Unable to use ivy-bibtex

### ISSUE THREAD

**Issue by basille** [tmalsburg/helm-bibtex#240]
Coming from JabRef, I have installed `ivy-bibtex` to find a lightweight replacement within Emacs. However, I can only access basic functionality, which shows me that the installation and recognition of my BibTeX file works fine… but inserting the reference, or opening PDF or URL/DOIs all fail.

After installing `ivy-bibtex`, I tried with a very limited `init.el`, with only this:

```
(setq
 bibtex-completion-bibliography '("/home/mathieu/Work/Biblio/test.bib")
 bibtex-completion-library-path '("/home/mathieu/Work/Biblio/test/")
 )
(global-set-key (kbd "C-c b") 'ivy-bibtex)
```

And a simple BibTeX file, with references such as:

```
@Article{Benhamou2011,
  Title                    = {{D}ynamic approach to space and habitat use based on biased random bridges},
  Author                   = {Benhamou, Simon},
  Journal                  = {PLOS ONE},
  Year                     = {2011},
  Pages                    = {e14592},
  Volume                   = {6},
  Abstract                 = {{B}ackground {A}lthough habitat use reflects a dynamic process, most studies assess habitat use statically as if an animal's successively recorded locations reflected a point rather than a movement process. {B}y relying on the activity time between successive locations instead of the local density of individual locations, movement-based methods can substantially improve the biological relevance of utilization distribution ({UD}) estimates (i.e. the relative frequencies with which an animal uses the various areas of its home range, {HR}). {O}ne such method rests on {B}rownian bridges ({BB}s). {I}ts theoretical foundation (purely and constantly diffusive movements) is paradoxically inconsistent with both {HR} settlement and habitat selection. {A}n alternative involves movement-based kernel density estimation ({MKDE}) through location interpolation, which may be applied to various movement behaviours but lacks a sound theoretical basis. {M}ethodology/{P}rincipal {F}indings {I} introduce the concept of a biased random (advective-diffusive) bridge ({BRB}) and show that the {MKDE} method is a practical means to estimate {UD}s based on simplified (isotropically diffusive) {BRB}s. {T}he equation governing {BRB}s is constrained by the maximum delay between successive relocations warranting constant within-bridge advection (allowed to vary between bridges) but remains otherwise similar to the {BB} equation. {D}espite its theoretical inconsistencies, the {BB} method can therefore be applied to animals that regularly reorientate within their {HR}s and adapt their movements to the habitats crossed, provided that they were relocated with a high enough frequency. {C}onclusions/{S}ignificance {B}iased random walks can approximate various movement types at short times from a given relocation. {T}heir simplified form constitutes an effective trade-off between too simple, unrealistic movement models, such as {B}rownian motion, and more sophisticated and realistic ones, such as biased correlated random walks ({BCRW}s), which are too complex to yield functional bridges. {R}elying on simplified {BRB}s proves to be the most reliable and easily usable way to estimate {UD}s from serially correlated relocations and raw activity information.},
  Doi                      = {10.1371/journal.pone.0014592},
  File                     = {Benhamou2011.pdf:Benhamou2011.pdf:PDF},
  Owner                    = {mathieu},
  Timestamp                = {2013.02.27}
}
```

If I launch `ivy-bibtex`, I do have the list of references, with the correct association to PDF files as denoted by the ⌘ symbols. But then, some actions do work (insert, copy), but all others fail with different error messages. 

Open the PDF, insert citation, insert reference, insert BibTeX key or entry return:

```
Wrong type argument: listp, "<Benhamou2011>"
```

Open the URL/DOI returns:

```
Search failed: "^@\\([^\"@\\#%',={}() 	
]+\\)[[:space:]]*[({][[:space:]]*Benhamou                             Dynamic approach to space and habitat use based on biased random bridges                                                               2011 ⌘  article[[:space:]]*,"
```

And show entry returns:

```
Wrong type argument: stringp, (#("Benhamou                             Dynamic approach to space and habitat use based on biased random bridges                                                               2011 ⌘  article" 0 1 (idx 1)) . "Benhamou2011")
```

Any pointer to what is going on here would be very much appreciated. I'm using `ivy-bibtex` 2.0.0 from Melpa-stable, on GNU Emacs 25.1.1(Debian Stretch).

**Comment by jagrg** [comment]
FWIW I cannot reproduce this.

Run `emacs -Q` and in the scratch buffer evaluate the following and try again. Does it work for you?

```
(require 'package)
(package-initialize)
(require 'ivy-bibtex)

(setq bibtex-completion-bibliography '("/home/mathieu/Work/Biblio/test.bib")
      bibtex-completion-library-path '("/home/mathieu/Work/Biblio/test/"))
```

**Comment by tmalsburg** [comment]
Hm, I can't reproduce this either.  I second Jonathan's suggestion to try it with a clean and minimal config to rule out interference from other packages.

**Comment by basille** [comment]
Thanks Jonathan and Titus for your feedback. I tried exactly as Jonathan suggested (`emacs -Q` and the snippet of code evaluated), to no avail… In the end, I upgraded from melpa-stable (2.0.0) to melpa (20180602.430), and now it works beautifully!

Not sure if I should close this bug report: I have now `ivy-bibtex` functional on my system, but it seems to be related to melpa-stable…

**Comment by basille** [comment]
(by the way, great work for `ivy-bibtex`, I'm very happy to have it working now!!)

**Comment by tmalsburg** [comment]
Glad that it's working now.  I don't know who added ivy-bibtex / helm-bibtex to melpa-stable but I recommend against using that.  The latest version is always the recommended version since we do not have a concept of a stable vs a development version.

**Comment by basille** [comment]
Fair enough! Maybe you should check why it's on melpa-stable though… I will probably not be the only one relying on it.

**Comment by tmalsburg** [comment]
Oops, it appears that I had added it to melpa-stable.  I have no memory of that.  Anyway, the melpa-stable recipe simply retrieves the up-to-date version, so melpa-stable should give you the same as ordinary melpa.  Question: why did switching resolve you problem? ivy/helm-bibtex probably rely on a package that is outdated in melpa-stable (my guess is parsebib).

**Comment by basille** [comment]
Probably the case: switching to melpa instead of melpa-stable for `ivy-bibtex` upgraded 17 additional packages (I did not keep track of them)…

**Comment by tmalsburg** [comment]
Looking at the download stats on melpa-stable, it seems that only few people are using it.  Perhaps, not surprising that it's not receiving enough attention from developers.  Ironically the result may be that melpa-stable is less stable than melpa.
