### ISSUE TITLE
ivy-add-actions gives error

### ISSUE THREAD

**Issue by eeenilsson** [tmalsburg/helm-bibtex#241]
I am trying to add ivy-bibtex actions using the following lisp (as recommended in https://github.com/tmalsburg/helm-bibtex).

```
(ivy-add-actions
   'ivy-bibtex
   '(("A" 'ivy-bibtex-add-PDF-attachment "Add PDF")))

```
Then searching for an entry and `M-o` for options includes as expected:

> A: Add PDF

But selecting "A" gives the following error:

> Invalid function: (quote ivy-bibtex-add-PDF-attachment)

Same result when adding for example ivy-bibtex-open-annotated-pdf

Any ideas how to fix this?

> ivy version: 20180515.1057 
> ivy bibtex version: 20180328.1147
> GNU Emacs 25.3.1

**Comment by tmalsburg** [comment]
Yes, it should work without the quote.  I fixed the example in the documentation.  I'll close this issue but feel free to reopen if it still doesn't work.

**Comment by tmalsburg** [comment]
Great, glad to head and thanks for the feedback!
