### ISSUE TITLE
Use highlighted candidate to display helm source

### ISSUE THREAD

**Issue by eeenilsson** [tmalsburg/helm-bibtex#244]
Thanks for the great work! Hope it is ok to ask this here.

I would like to modify the helm buffer so that the abstact field of the candidate that is currently highlighted is displayed as a source in the helm buffer (ie not as an action but continuously shown and updated when moving between candidates). 

Im not even sure this is possible. Made some attempts but would need a pointer on where to start. Is there a way to continuously retrieve the key from the entry currently marked?

**Comment by tmalsburg** [comment]
I don't know whether Helm supports this but Thierry Volpiatto, the lead dev of Helm, could give you input on that.  One keyword that might be useful is "persistent actions" a helm feature where an action is executed without finishing the helm session.

**Comment by eeenilsson** [comment]
Thanks for the tip! Its a place to start and I will look into it.

**Comment by jagrg** [comment]
> I would like to modify the helm buffer so that the abstact field of the candidate that is currently highlighted is displayed as a source in the helm buffer (ie not as an action but continuously shown and updated when moving between candidates).

I'm not sure how to do what you want, but here is something to get you started:

```elisp
(defun helm-bibtex-preview-abstract (_)
  (let* ((key (helm-marked-candidates))
	 (entry (bibtex-completion-get-entry (car key)))
	 (abstract (cdr (assoc "abstract" entry))))
    (with-current-buffer (get-buffer-create "*abstract*")
      (pop-to-buffer "*abstract*")
      (erase-buffer)
      (insert (if abstract abstract ""))
      (visual-line-mode))))
```

You would also need to add `:persistent-action 'helm-bibtex-preview-abstract` to the `helm-source-bibtex` source. Now when you call helm-bibtex, you can press C-j to preview the abstract, or C-c C-f to activate helm-follow-mode.

> Im not even sure this is possible. Made some attempts but would need a pointer on where to start. Is there a way to continuously retrieve the key from the entry currently marked?

To get the key you can use `helm-marked-candidates`. For example, to display the key of the current candidate in the modeline, you can use the function below, and add `:mode-line 'foo` to `helm-source-bibtex`.

```
(defun foo ()
  (let ((key (car (helm-marked-candidates))))
    (format "%s" key)))
```

**Comment by eeenilsson** [comment]
Thanks, thats great!

In the meantime my preliminary solution was to just display abstract text (and some other content) from all candidates as a separate helm source. Its not exactly what i had thought at first but may have some advantages.

```
;; helper function
(defun get-abstract-contents (candidates)
  "Helper function that extracts abstract text from candidates (which is a list of alists). Also extracts author, year, title, journal, tags. To be put in customized helm-bibtex function. Requires the package 'dash'."
  (let* (
	 ;; drop car from candidates	 
	 (displaythis  (mapcar 'cdr candidates))

	 ;; select fields to include
	 (selectlist (list "author" "abstract" "year" "title" "journal" "tags" "booktitle"))
	 (displaythis (mapcar  (lambda (sublist) (-filter (lambda (x) (-contains? selectlist (car x))) sublist)) displaythis))

	 ;; format using melt-cons
	 (displaythis (mapcar (lambda (sub) (mapcar (lambda (x) (s-concat (format "%s" (car x)) ": " (format "%s" (cdr x)))) sub)) displaythis))

	 ;; join sub-lists to one string per entry, keeping labels
	 (displaythis (mapcar (lambda (x) (format "%s" x)) displaythis))

	 ;; format text
	 (displaythis (mapcar (lambda (x) (replace-regexp-in-string "^(" "ENTRY TEXT " x)) displaythis)) ;; add marker at start of entry
	 (displaythis (mapcar (lambda (x) (replace-regexp-in-string ")$" "\n" x)) displaythis)) ;; replace last parens with newline
	 (displaythis (mapcar (lambda (x) (replace-regexp-in-string "abstract:" " ABSTRACT:" x)) displaythis))
	 (displaythis (mapcar (lambda (x) (replace-regexp-in-string "author:" " AUTHOR:" x)) displaythis))
	 (displaythis (mapcar (lambda (x) (replace-regexp-in-string "journal:" " JOURNAL:" x)) displaythis))
	 (displaythis (mapcar (lambda (x) (replace-regexp-in-string "year:" " YEAR:" x)) displaythis))
	 (displaythis (mapcar (lambda (x) (replace-regexp-in-string "tags:" " TAGS:" x)) displaythis))
	 (displaythis (mapcar (lambda (x) (replace-regexp-in-string "title:" " TITLE:" x)) displaythis))
	 (displaythis (mapcar (lambda (x) (replace-regexp-in-string "booktitle:" " BOOKTITLE:" x)) displaythis))
	 )
    (progn displaythis)
    )
  )

```
Then add this to `:sources` in the `helm-bibtex` function: 

```
	   (helm-build-sync-source "Abstract search"
	     :candidates (get-abstract-contents candidates))
```

**Comment by eeenilsson** [comment]
@jagrg I am sorry but I could not get your example function (to display the key of the current candidate in mode-line) to work (nothing was displayed), did you test it? Best.

**Comment by jagrg** [comment]
You probably need to restart emacs. Otherwise, copy helm-source-bibtex to your scratch buffer and change defvar to setq.

On 07 Jun 2018, eeenilsson <notifications@github.com> wrote:

> @jagrg I am sorry but I could not get your example function (to display the key
> of the current candidate in mode-line) to work (nothing was displayed), did you
> test it? Best.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Jonathan
Monthly Atmospheric CO₂: May 2018: 411.25, May 2017: 409.65

**Comment by eeenilsson** [comment]
Tried restart and `setq helm-source-bibtex` (error dur to wrong number of arguments), but no luck.

I will close this for now, since its really not an issue with helm-bibtex.
