### ISSUE TITLE
@collection entry and bibtex-completion-notes-template-

### ISSUE THREAD

**Issue by dedalu** [tmalsburg/helm-bibtex#246]
A @collection bib entry normally does not have any author(s), but at least one editor. In this case the editor(s) replaces the missing author(s). Most bibliographical styles add a note: "Name (ed.)".

But I cannot find a way to customize the bibtex-completion-notes-template-... variable to follow this rule: If there is no author, but and editor, put the editor as the author with the note "(ed.) or (eds.)". 

The problem is the note. Without it, a simple `(setq 'bibtex-completion-notes-template-one-file "\n* ${author} {$editor} ...)` could be ok. 

There is any way to make a conditional template, like if ${author} is void and ${editor} is not void then print ${editor} (ed.) etc.?

Today I correct my notes titles by hand. Not much a trouble. But, would be very nice if the everyday use helm-bibtex could do this out of the box.

Thank you very much.

**Comment by tmalsburg** [comment]
Thanks for pointing out this shortcoming.  I've just added a virtual field `author-or-editor`.  With that author is used if defined otherwise editor.  If you're using the default templates there is nothing you have to change in order to use this.  Enjoy :-)

**Comment by tmalsburg** [comment]
I can't reproduce this error.  Could you please provide more details?  Thanks.

**Comment by tmalsburg** [comment]
The code uses `if-let*` which was introduced in Emacs 25.1.  Is your Emacs older than that?

**Comment by dedalu** [comment]
My emacs is "GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.21) of 2017-09-22, modified by Debian".

I tested without any other packages than helm-bibtex and its dependencies and with this minimal init.el:

```
(package-initialize)

(setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
                         ("marmalade" . "https://marmalade-repo.org/packages/")
                         ("melpa" . "http://melpa.milkbox.net/packages/")))
(custom-set-variables
 '(package-selected-packages (quote (helm-bibtex))))
(custom-set-faces
 )

;;
;; helm-bibtex
;;
(autoload 'helm-bibtex "helm-bibtex" "" t)
(setq bibtex-completion-bibliography
      '("/home/dedalu/Documentos/Biblioteca/Biblioteca.bib"))
(setq bibtex-completion-library-path '("/home/dedalu/Documentos/Biblioteca/pdfs"))
(setq bibtex-completion-pdf-field "File")
(setq bibtex-completion-notes-path "/home/dedalu/Documentos/Biblioteca/notas.org")
```


'M-x helm-bibtex' then 'f8' in any entry and I get the message:

'bibtex-completion-apa-get-value: Invalid function: (value (bibtex-completion-get-value "author" entry))'

I am sorry to have given you so much hassle.

Thanks.

**Comment by dedalu** [comment]
@tmalsburg, check this http://lists.gnu.org/archive/html/emacs-devel/2017-10/msg00524.html. The problem seems to be the starred version of if-let (if-let*). I will update my emacs and test again.

**Comment by dedalu** [comment]
Work fine with "GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-05-29" after forcing recompile. Thanks!

**Comment by tmalsburg** [comment]
Thanks for the pointer.  If I understand the thread halfway correctly, we can avoid this issue in Emacs 25 by adding `(require subr-x)`.   Added in 421c6224b1f51656584d72ca7538cddacb05784e. Hope that helps other people. I doubt that everyone has moved to 26.
