### ISSUE TITLE
Issue with the new `author-or-editor`

### ISSUE THREAD

**Issue by mgttlinger** [tmalsburg/helm-bibtex#249]
When opening a new notes file I get the following error:

    bibtex-completion-apa-get-value: Invalid function: (value (bibtex-completion-get-value "author" entry))

which wasn't there previous to the introduction of the new `author-or-editor` virtual variable (and it if inside a part of code that is related to this virtual variable).

**Comment by tmalsburg** [comment]
The code for author-or-editor previously used the `if-let*` macro which is buggy in Emacs 25.  However, I had removed `if-let*` in the latest version.  Updating should fix it.

**Comment by mgttlinger** [comment]
Thanks for the quick reply (and the awesome package as a whole). The update fixed it.

**Comment by mclearc** [comment]
I'm seeing this same error on the most recent helm-bibtex with emacs 26.3. Perhaps one of the recent PRs has brought a regression with it?

**Comment by tmalsburg** [comment]
I can't reproduce this in Emacs 28 but removed if-let and when-let in 8a0dd9841316793aacddea744d6b8ca4a7857a35.  Could you please test?  Thank you.

**Comment by mclearc** [comment]
That works! Thanks for the quick fix and for the great package.

**Comment by tmalsburg** [comment]
You're welcome.

It's weird because all I did was to expand the if-let and when-let macros manually.  To my naive understanding there shouldn't be any room for bugs.  Anyway, glad it works now.

**Comment by myshevchuk** [comment]
@tmalsburg This may have something to do with compilation and/or eager macro expansion. The second should not be the case for `if-let*` and friends, since `subr-x` is Emacs built-in library used very often, and it is most probably already loaded by the time `bibtex-completion` is loaded. But if the code is compiled, the problems may potentially arise. 

This observation may be an evidence in favour of the above assumption:
> It's weird because all I did was to expand the if-let and when-let macros manually. 

And this should fix issues with `if-let*`:

```elisp
(eval-when-compile 
    (require 'subr-x))

or

(require 'subr-x)
```

**Comment by tmalsburg** [comment]
Thanks @myshevchuk for the input.  I will have to reserve some time to study this aspect of elisp / emacs more closely before I can say that I really understand this.
