### ISSUE TITLE
helm-bibtex does not match spaces 

### ISSUE THREAD

**Issue by scaramouche1** [tmalsburg/helm-bibtex#251]
Imagine I run `helm-bibtex`, type "sm", and get these two results:

- Smith 2015
- Smith 2016

For some reason, if I type "sm 16", I get no matches.  This problem does not occur with ivy-bibtex (which correctly matches "Smith 16").

It seems helm-bibtex is not recognizing spaces correctly, as if I try to match " " (one blank space), I get no matches.

**Comment by tmalsburg** [comment]
We're using ivy's and helm's matching engines, so there is always a possibility that you get different search results.  However, I can't reproduce this specific problem with helm-bibtex.  Did you perhaps configure helm to use some non-standard rules for matching?

**Comment by scaramouche1** [comment]
Thanks.  I think it was my mistake.  I updated Emacs and packages and the problem disappeared.

**Comment by tmalsburg** [comment]
Glad you could get it fixed.
