### ISSUE TITLE
helm-bibtex only ever searches online, never my bib files?

### ISSUE THREAD

**Issue by jona-sassenhagen** [tmalsburg/helm-bibtex#252]
See title. I guess it works decently at that, but I'd really like it to look at my bib files first?

I have an entry added to my `.emacs`:

```
(setq bibtex-completion-bibliography
      '("/path/to/my/local/ref.bib"))

;; and for good measure ...

(setq helm-bibtex-bibliography '("/path/to/my/local/ref.bib"
                                 ))
```

Sorry if this is a stupid question, I only started using Emacs this week.

**Comment by tmalsburg** [comment]
Not a stupid question at all.  Although the second line (`helm-bibtex-bibliography`) is redundant, this should work and show you the entries from the bib file at the top.  I'm assuming that you start helm-bibtex with `M-x helm-bibtex`?  Could you try with a minimal bib file (with just one entry) and post that bib file if it still doesn't work?

**Comment by jona-sassenhagen** [comment]
Sure. Minimal bib file:

```
@article{metzner2017importance,
        Author = {Metzner, Paul and von der Malsburg, Titus and Vasishth, Shravan and R{\"o}sler, Frank},
        Date-Added = {2018-06-26 08:25:38 +0000},
        Date-Modified = {2018-06-26 08:25:38 +0000},
        Journal = {Cognitive science},
        Number = {S6},
        Pages = {1232--1263},
        Publisher = {Wiley Online Library},
        Title = {The importance of reading naturally: Evidence from combined recordings of eye movements and
electric brain potentials},
        Volume = {41},
        Year = {2017}}
```

Open and close emacs, ...

```
M-x helm-bibtex
metzner RET
```

gives:

```
  1CrossRef search results for ‘metzner’
  2> Metzner, Samy
  3  (no authors)
  4  In: Benezit Dictionary of Artists
  5  Type: reference-entry
  6  Publisher: Oxford University Press
  7  References: 10.1093/benz/9780199773787.article.b00121642
  8  URL: http://dx.doi.org/10.1093/benz/9780199773787.article.b00121642
  9
 10> Metzner, Franz
 11  (no authors)
 12  In: Benezit Dictionary of Artists
 13  Type: reference-entry
 14  Publisher: Oxford University Press
 15  References: 10.1093/benz/9780199773787.article.b00121641
 16  URL: http://dx.doi.org/10.1093/benz/9780199773787.article.b00121641
 17
 18> Early Unstable CO2-Fixation Products in Photosynthesis
 19  Helmut Metzner, Barbara Metzner, Melvin Calvin
 20  Type: report
 21  Publisher: Office of Scientific and Technical Information  (OSTI)
 22  References: 10.2172/915462
 23  URL: http://dx.doi.org/10.2172/915462
 24 ...
```

**Comment by tmalsburg** [comment]
Thanks for providing this recipe.  Now, I understand what's happening.  Helm-bibtex doesn't require that you press `RET`. Instead it searches instantly as you type.  If there is no match in the upper section (local results), the cursor is placed on the first entry from the online section (search in Crossref) and when you press `RET` you're triggering the online search.

Now the question is why you're not seeing the Metzner entry in the list of local results.  Could you please execute the command 'M-: (bibtex-competion-candidates)` and check the `*Messages* buffer for the result?  The result should looks something like this (different entry):

``` elisp
(("2014 Growth Curve Analysis and Visualization Using R Daniel Mirman book Mirman2014" ("year" . "2014") ("title" . "Growth Curve Analysis and Visualization Using {R}") ("author" . "Daniel Mirman") ("=type=" . "book") ("=key=" . "Mirman2014")))
```

**Comment by jona-sassenhagen** [comment]
Meta-colon? I.e., on my German keyboard, press meta, release, shift-.?

That gives:
```
Eval: (bibtex-completion-candidates)
1Debugger entered--Lisp error: (void-function bibtex-completion-candidates)
2  (bibtex-completion-candidates)
3  eval((bibtex-completion-candidates) nil)
4  eval-expression((bibtex-completion-candidates) nil)
5  funcall-interactively(eval-expression (bibtex-completion-candidates) nil)
6  call-interactively(eval-expression nil nil)
7  command-execute(eval-expression)
```

If I do `M-x (bibtex-completion-candidates)`, I get `No match`.

**Comment by tmalsburg** [comment]
Yes, press `alt` (=meta) and then `:`. This gives you a prompt in which you can enter elisp commands.  The error message suggests that helm-bibtex is not properly loaded.  Did you install it via MELPA?  Perhaps (re-)load it with `M-: (require 'helm-bibtex)`

**Comment by tmalsburg** [comment]
Btw, `M-x` is for executing commands.  Commands are special elisp functions. All commands are functions but the reverse is not true.  Commands are basically user-facing functions, whereas non-command functions are for internal purposes.  Since `bibtex-completion-candidates` is not user-facing, we need to call it with  `M-:`.  Hope that helps to make sense of what's going on.  These things can be a bit confusing for Emacs beginners but don't let this discourage you.

**Comment by jona-sassenhagen** [comment]
>Did you install it via MELPA?

Indeed- `package-install` and `helm-bibtex`.

>Perhaps (re-)load it with `M-: (require 'helm-bibtex)`

Doesn't change anything -- the mini buffer says `helm-bibtex` and that's it.

I guess I somehow have a broken install of helm-bibtex. I could un- and reinstall I guess - just delete  `~/.emacs.d/elpa/helm-*`, and then redo the `package-install` thing?

>Btw, M-x is for executing commands. Commands are special elisp functions. All commands are functions but the reverse is not true. Commands are basically user-facing functions, whereas non-command functions are for internal purposes. Since bibtex-completion-candidates is not user-facing, we need to call it with M-:. Hope that helps to make sense of what's going on. These things can be a bit confusing for Emacs beginners but don't let this discourage you.

Ah, ok. That indeed does clear things up.

**Comment by tmalsburg** [comment]
Yes, something must be broken when `M-x helm-bibtex` does something but `bibtex-completion-candidates` is undefined.  Have you also installed org-ref?  In the past it sometimes interfered with helm-bibtex.

No need to delete files manually.  Just do `M-x list-packages` and use the UI to remove and reinstall packages.

**Comment by jona-sassenhagen** [comment]
Ok, after much trying around, including reinstalling everything, I found the issue: I had a broken line in my `.emacs` right before the line where the bibtex file to use by helm-bibtex is specified. After removing the line, it parses my bib file properly, and I can search it. Sorry for the vain search!

**Comment by jona-sassenhagen** [comment]
Thanks!
