### ISSUE TITLE
(bibtex-completion-init) causes error, complains about no space on disk

### ISSUE THREAD

**Issue by jabranham** [tmalsburg/helm-bibtex#253]
```
(bibtex-completion-init)
```

```
Debugger entered--Lisp error: (file-notify-error "Could not add watch for file" "No space left on device" "/home/alex/Sync/bibliography")
  inotify-add-watch("/home/alex/Sync/bibliography" (create delete delete-self modify move-self move) file-notify-callback)
  file-notify-add-watch("~/Sync/bibliography/references.bib" (change) #f(compiled-function (event) #<bytecode 0x1e13969>))
  #f(compiled-function (file) #<bytecode 0x1e13975>)("~/Sync/bibliography/references.bib")
  mapc(#f(compiled-function (file) #<bytecode 0x1e13975>) ("~/Sync/bibliography/references.bib"))
  bibtex-completion-init()
  eval((bibtex-completion-init) nil)
  eval-expression((bibtex-completion-init) nil nil 127)
  funcall-interactively(eval-expression (bibtex-completion-init) nil nil 127)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```

I'm guessing that this is because of 01a37a593436ca7fc361490093ab084a626fc425 coupled with the fact that I use syncthing (with inotify) to sync my bib file across computers. 

EDIT: But only happens on my desktop, not my laptop, even though they have very similar setups...

**Comment by tmalsburg** [comment]
The error message ("No space left on device") suggests that your hard drive is full. Could you check that?

**Comment by jabranham** [comment]
Yes, sorry I thought I mentioned in the first report that it's not full (not even close, really).

**Comment by tmalsburg** [comment]
Ah sorry, I overlooked the title of the issue.  Not sure what's going on but I doubt that the problem is in helm-bibtex.  All we're doing is adding a watch to this file, which should work unless the file doesn't exist.  I'm not familiar with syncthing but perhaps you could try using a bib file that is not managed by syncthing and see what happens then?

**Comment by jabranham** [comment]
I don't see it then, and haven't been able to reliably reproduce the problem. I'll close this issue until I have more information.

**Comment by a-fent** [comment]
I just had the same error opening a bibtex file without the hard disk being short of space. The solution offered at https://github.com/Alexander-Miller/treemacs/issues/462 solved it (but I couldn't explain why it solved it ...)

**Comment by tmalsburg** [comment]
Thanks for leaving this information here. I haven't had this problem but other users might find it useful in the future.
