### ISSUE TITLE
Custom naming scheme for pdfs and other files

### ISSUE THREAD

**Issue by mgttlinger** [tmalsburg/helm-bibtex#254]
Currently, there is no way (to my knowledge) to use a custom naming scheme for the pdf files to be found by helm-bibtex but to redefine the ` bibtex-completion-find-pdf-in-library` `defun` to generate a different file name.
This then, however, does not apply to the names used for the note files and also is rather fragile as it likely has to be adjusted if the original implementation changes with a new release.

Would it make sense to have a customizable function to generate those names allowing the user to define their own custom naming scheme?

**Comment by tmalsburg** [comment]
Hi, thanks for the suggestion. I'm not sure there is enough demand for this feature to include it. Could you perhaps explain your custom scheme? This would help me to get a better understanding of your use case.

**Comment by mgttlinger** [comment]
My scheme consists of two parts separated by `_`:
The author names separated by `_` where each first name is shortened to the first letter.
The title of the work where each symbol like `:` which somewhat initiates a subtitle is replaced by `_`.
Additionally, every space everywhere is replaced by `-`.

If there are special letters in the title or the names which shouldn't be in file names, I usually pick the closest regular letter and use the `file` field to handle that situation.

And the reason for having a custom naming scheme at all is that I don't want to impose a custom bibtexkeying scheme in the shared bib file while still having my pdfs and notes named in a readable way.
I hope that makes sense.

**Comment by tmalsburg** [comment]
Why don't you use the `file` field for all entries?

**Comment by mgttlinger** [comment]
Because generating the names works most of the time and avoids me having to insert a `file` field everywhere.

**Comment by tmalsburg** [comment]
So this is more a matter of personal preference instead a technical necessity, which is perfectly fine, of course.  Longer term, I was planning to make the code for referencing PDFs (and possibly notes) more flexible.  I'm imagining a sort of plug-in scheme that allows users to flexibly mix and match various methods of referencing PDFs.  This would also cover your case.  Unfortunately, this is not very high up in my list of priorities due to time constraints and the fact that the current scheme seems to work well for most people.  So I don't know when, and if at all, this is going to happen.  However, I'm always happy to provide guidance and feedback to people who want to work on PRs.

**Comment by tmalsburg** [comment]
In the meantime, I recommend that you just override the standard functions for finding PDFs.  The code is relatively stable and I wouldn't expect this approach to break anytime soon.  And when it does it will be easy to adapt your code to the new plug-in scheme that I described above.

**Comment by mgttlinger** [comment]
Sure, I wouldn't expect you to implement this just for me :joy:. If this would have been a feature which seemed useful to you for a larger userbase, I would have had a stab at implementing it. But as is, I guess, I'll follow your recommendation and stick to my redefinition.

And by the way, thank you for always replying super fast!

**Comment by mgttlinger** [comment]
> Longer term, I was planning to make the code for referencing PDFs (and possibly notes) more flexible. I'm imagining a sort of plug-in scheme that allows users to flexibly mix and match various methods of referencing PDFs. This would also cover your case. Unfortunately, this is not very high up in my list of priorities due to time constraints and the fact that the current scheme seems to work well for most people. So I don't know when, and if at all, this is going to happen. However, I'm always happy to provide guidance and feedback to people who want to work on PRs.

Any update on that? 

Would you be open for PR that introduces a custom variable allowing users to specify a function from entry to string that generates a file name which defaults to the current behaviour and is used to generate names for pdfs and notes?

**Comment by tmalsburg** [comment]
No updates, I'm afraid.  I guess it wouldn't even be that much work to implement that plug-in system (in lack of a better name) that I have in mind.  But there are just so many other more urgent things on my to-do list.  

At this stage, I'd rather not introduce more custom variables that might become obsolete when we switch to a better system.  Let me know if you'd like to take a stab at writing code for that new system.

**Comment by mgttlinger** [comment]
I can't promise that I have loads of time to implement that plugin system but I could try. I'm not that experienced in Elisp but maybe that would be a good project to learn a bit more on that front.

**Comment by tmalsburg** [comment]
I think (not sure) it mostly involves rearranging the existing code.  I imagine a set of functions that can find PDFs (and other document types) for a given BibTeX key.  And then the user can define a list of these functions which are tried either until a PDF is found or exhaustively.  This would also make it easy for users to add their own custom functions.

**Comment by mgttlinger** [comment]
Wouldn't this basically be what I proposed but with a customizable list of name generators rather than a single function?

**Comment by mgttlinger** [comment]
Is there (or can you open) an issue where this idea is described/can be discussed rather than the comments on this issue?

**Comment by tmalsburg** [comment]
There is none but I can: #287 :) Let me know what you think.

**Comment by tmalsburg** [comment]
Before any code is written, we should probably review earlier issues on that topic to see whether this system really covers all cases that users might plausibly care about.
