### ISSUE TITLE
Query multiple fallback options

### ISSUE THREAD

**Issue by mgttlinger** [tmalsburg/helm-bibtex#264]
I may have missed how to do this but I often find myself in the situation where I query CrossRef without success then reopen, retype and requery e.g. HAL.
Is there a way to query multiple of those sources or query another one with the same search when the first doesn't yield any results?

**Comment by tmalsburg** [comment]
I think you are looking for `helm-resume`.  I use this all the time especially with CrossRef searches:

- Search for article.
- Select Cross ref search.
- Copy BibTeX.
- `helm-resume` + enter to add the BibTeX entry to my bibliography.

**Comment by mgttlinger** [comment]
Apart from `helm-resume` opening a new buffer for the result this is exactly what I was looking for. 

Thanks! 
Should I add that to the Readme or is this common knowledge?

**Comment by tmalsburg** [comment]
`helm-resume` is mentioned in two places in the README but not very prominently.  I think it would be good to make this more visible. It also took me a while to discover this feature.  So, yes, please add it at an appropriate place.  Thank you!

**Comment by tmalsburg** [comment]
If there is an analogous command for ivy, it would be good to mention that as well.
