### ISSUE TITLE
Add abbreviated author list option for bibtex-completion-notes-template

### ISSUE THREAD

**Issue by ashiklom** [tmalsburg/helm-bibtex#266]
For papers with 3 or more authors, it's common to abbreviate the author list to "First Author et al.". However, as far as I can tell, there is currently no way to do this in the `bibtex-completion-notes-template-*` variables.

I propose adding a `${author-abbrev}` (or similar) formatting option that behaves like the `%2a` format in `org-ref-reftex-format-citation`, such that one author is written as "Smith", two authors as "Smith and Jones", and three or more authors as "Smith et al.". Even better if the number of authors was customizable in the format (e.g. `${author-abbrev 3}` would list up to 3 authors in full, but 4 or more would be abbreviated to "et al.").

**Comment by tmalsburg** [comment]
Make sense.  I would welcome this feature but won't have time to work on it any time soon.  PRs welcome, as always.
