### ISSUE TITLE
Feauture request: Add user-default for source for pdf-files in bibtex-completion-add-pdf-to-library

### ISSUE THREAD

**Issue by ardpp** [tmalsburg/helm-bibtex#269]
Hi! 

Many thanks for ivy-bibtex, that I use almost on a daily basis!

In my workflow I usually use firefox to look for papers and download those that I need. They are stored in the "~\Downloads" directory. Files that I want to keep and add to my library have to be moved to the library-directory "~\papers", where I keep all papers. 

When using  `ivy-bibtex-add-pdf-to-library`-action one is asked to choose file or buffer and choosing file asks you for a file in the library-directory. I'm not experienced enough with elisp but I think that it should be possible and would be nice to have a default directory ("~\Downloads" in my case) where the action looks for the pdf-files. When this variable is set to nil (the default setting) then the behaviour for adding of files should be the same as now. 

Also it would be nice if one could choose moving (and renaming a file) from "~\Downloads" to  "~\papers" instead of copying it. I usually have to delete the file from "~\Downloads" manually. Again I suppose this could be a variable which preserves the present behaviour when set to nil. 

Does it make sense, or can I change my workflow or personal configuration somehow to achieve what I want? 

Cheers,
Andrej

**Comment by tmalsburg** [comment]
I see how the current setup perhaps causes a bit more friction than necessary.  However, I do worry a bit about inflation of config variables.  Two variables just for this tiny feature seems a bit much.  Is there a way to improve the workflow without introducing new variables?  Personally, I don't use this feature so I haven't thought about it much.

**Comment by tmalsburg** [comment]
Wait, can't we use the minibuffer's history?  The first time you have to enter the path.  But the next time you just press *cursor up* to access and select that path.

**Comment by ardpp** [comment]
If I'm not mistaken the minibuffer history will show the file that I chose previously instead of the path in that case. No worries! I can define the corresponding action in my own config. Can't think of a better way than just copying the corresponding function and change the two things accordingly.
