### ISSUE TITLE
 Quote key before using in re-search-forward.

### ISSUE THREAD

**Issue by swhahn** [tmalsburg/helm-bibtex#27]
Quote the key before using re-search-forward in helm-bibtex-get-entry,
    because the key can contain regexp chars.
    
    Use the same search algorithm in helm-bibtex-show-entry to find the
    entry as in helm-bibtex-get-entry, because it can be possible to
    have string entries which contain the key.

diff --git a/helm-bibtex.el b/helm-bibtex.el
index 237b047..98944b8 100644
--- a/helm-bibtex.el
+++ b/helm-bibtex.el
@@ -262,7 +262,7 @@ (defun helm-bibtex-get-entry (entry-key)
     (goto-char (point-min))
     (re-search-forward (concat "^@\\(" parsebib--bibtex-identifier
                                "\\)[[:space:]]*[\(\{][[:space:]]*"
-                               entry-key))
+                               (regexp-quote entry-key)))
     (let ((entry-type (match-string 1)))
       (helm-bibtex-prep-entry (parsebib-read-entry entry-type)))))
 
@@ -494,7 +494,10 @@ (defun helm-bibtex-show-entry (key)
       (let ((buf (helm-bibtex-buffer-visiting bibtex-file)))
         (find-file bibtex-file)
         (goto-char (point-min))
-        (if (search-forward key nil t)
+        (if (re-search-forward
+             (concat "^@\\(" parsebib--bibtex-identifier
+                     "\\)[[:space:]]*[\(\{][[:space:]]*"
+                     (regexp-quote key)) nil t)
             (throw 'break t)
           (unless buf
             (kill-buffer)))))))

**Comment by tmalsburg** [comment]
Ah, thanks for catching that.  I'll fix it.

**Comment by tmalsburg** [comment]
Fixed in ef9c153a7f9c1c3bf525f61103489480ba7d3c82.  Thanks for the patch.
