### ISSUE TITLE
Not all functions are working (notes, files, BibLATEX-fields)

### ISSUE THREAD

**Issue by hdevriese** [tmalsburg/helm-bibtex#270]
Hello,

I have been trying to work with Helm-BibTeX and Org-Ref. I installed through Melpa-stable on gnu Emacs 26.1, system: OSX 10.14.1. Helm-BibTeX 2.0.0, org-ref 1.1.1.

When adding keywords through Helm-BibTeX, I get this message:
wrong type argument: strings, ("Bibtexkey for selected entry")

When trying to add a note through Helm-BibTeX, I get this message: 
symbol's function definition is void: Helm-BibTeX-edit-notes
Similar messages for inserting pdf etc.  

I tried to see if BibLATEX fields are recognized, which isn't the cas, for instance for the "file" field.

I can access my .bib file through Helm-BibTeX though and some fonctions work as expected: Insert BibTeX key/entry/formatted citation works. Using Cite:bibtexkey in org-files works. 

Any thoughts ? 

I don't know anything about programming, I might be doing something very obviously wrong. 
Copy of .emacs in attachment. 

Kind regards, 
HDV

[copyinitfile.txt](https://github.com/tmalsburg/helm-bibtex/files/2568407/copyinitfile.txt)

**Comment by tmalsburg** [comment]
I think these are problem with org-reg which modifies helm-bibtex.  For instance, helm-bibtex doesn't even have a feature for adding keywords.  Please post an issue at org-ref's repository.

Regarding the file field. Please see the documentation in our README.  Perhaps that helps.  The `file` field should definitely work if helm-bibtex is configures appropriately.
