### ISSUE TITLE
Project-wise structure

### ISSUE THREAD

**Issue by vlamacko** [tmalsburg/helm-bibtex#271]
I organize my notes using a folder per project.
The rough structure looks like this:
```
project
|--- project.org
|--- references.bib
|---reading
     |--- book1.pdf
     |--- book2.pdf
```
How would I go about setting this up? I use Spacemacs on Windows.

I tried setting both `bibtex-completion-bibliography` and `bibtex-completion-library-path` to relative paths. That is `references.bib` and `reading` respectively. This did not work.

**Comment by tmalsburg** [comment]
You have to list all `.bib` files in `bibtex-completion-bibliography` and all directories containing PDFs in `bibtex-completion-library-path`.  Paths have to be absolute.  See [here](https://github.com/tmalsburg/helm-bibtex#minimal-configuration) and [here](https://github.com/tmalsburg/helm-bibtex#pdf-files) for examples.  If you don't want to set all these `.bib` files and PDF directories manually, you could write some elist code that scans your filesystem to find them.  Hope that helps.
