### ISSUE TITLE
Parsebib issue

### ISSUE THREAD

**Issue by jmburgos** [tmalsburg/helm-bibtex#278]
Hi Titus,
Afte the last update when I do M-x "ivy-bibtex" I get the following error:

parsebib-find-next-item: Illegal entry type: 520860

Do you know what could be the issue?  I am using helm-bibtex 20190113.1845.

Thanks!

**Comment by tmalsburg** [comment]
Hi Julian!  Sorry, no idea. Everything works fine for me.  Since we didn't change the code for reading BibTeX, I suspect that either there is a problem with your .bib file or there is an issue in parsebib that is triggered by something in your .bib file.  A reproducible example would be helpful.

**Comment by jmburgos** [comment]
Ah! Sorry for the noise.  There was a tny issue with my bib file.  Strangely, "bibtex-validate" did not showed any problems.  Everything is fine now.

**Comment by tmalsburg** [comment]
Glad to hear. Have a great weekend!
