### ISSUE TITLE
automatic multiple files broke my file naming convention

### ISSUE THREAD

**Issue by jlapeyre** [tmalsburg/helm-bibtex#282]
A feature has been added (I searched the github README, but I can't find it documented. I did read it somewhere!) that associates with a bibkey all filenames whose initial characters are that bibkey. Upon choosing that bibkey in the helm menu, you are prompted to select one of the files.

But, my convention is: `@Article{Smith2018,`  for `Smith2018.pdf`. And `@Article{Smith2018a,`  for `Smith2018a.pdf`, etc. So this convention is now broken, because the key `Smith2018` now is associated with every paper from 2018 whose first author is Smith.

Any ideas how to fix this ? Probably the best is for me to find a new naming convention, and then write some scripts to rename my entire collection and my bibtex files. I use this convention a lot (eg for all my own notes and papers), so it will take a bit of work and care inspection to make sure it is done correctly.

If there is an obvious way around this, please let me know.

**Comment by tmalsburg** [comment]
There is a customization variable that can be used to control this behavior: `bibtex-completion-find-additional-pdfs`  What I don't understand is why you're getting the new behavior when the default value of this variable should give you the old behavior (only exact matched).

**Comment by tmalsburg** [comment]
By the way, this is described in the README: https://github.com/tmalsburg/helm-bibtex#additional-pdfs
