### ISSUE TITLE
`helm-bibtex` not working if `bibtex-completion-bibliography` is specified

### ISSUE THREAD

**Issue by danielw2904** [tmalsburg/helm-bibtex#285]
I am using helm-bibtex with usepackage. The relevant part of the config looks as follows:

```
(use-package helm-bibtex
  :ensure t
  :init
 (autoload 'helm-bibtex "helm-bibtex" "" t)
  :config
  (require 'helm)
  (setq bibtex-completion-bibliography '("~/Desktop/project/bibliography.bib"))
  )
``` 

When I run `helm-bibtex` I get the error: 

```
Could not add watch for file: No space left on device , /home/daniel/Desktop/project
```

I've moved to folder to desktop in case there was something weird in the original folder which is synced. I have read and write permissions for the file and tried different content including no content. There is also around 600GB space on the partition.

The problem does not persist if I remove the `bibtex-completion-bibliography` line and get the fallback search option.

Any suggestions about what might be wrong?

**Comment by tmalsburg** [comment]
I think this isn't a problem with helm-bibtex but something related to how Emacs creates watches for file system events.  To confirm, could you please execute the following:

``` elisp
(file-notify-add-watch "~/Desktop/project/bibliography.bib" '(change) (lambda (event) (message "Watch is working.")))
```

Then change the content of  the ~.bib~ file, save, and check whether you got the message "Watch is working." in the ~*Messages*~ buffer.

**Comment by danielw2904** [comment]
I apologize for the long delay. It took me a while to recreate the problem. It appears another app was creating tons of watches and thus no more watches could be created. Once I closed that app everything worked. For future readers [this SO question has been helpful.](https://stackoverflow.com/questions/13758877/how-do-i-find-out-what-inotify-watches-have-been-registered  )

**Comment by tmalsburg** [comment]
Thanks for the update, Daniel!  Glad you could get this resolved.
