### ISSUE TITLE
Add resolution of cross-references

### ISSUE THREAD

**Issue by scottmartincampbell** [tmalsburg/helm-bibtex#29]
A request: it would be helpful if helm-bibtex used the crossref field, if available, to show the inherited auhtor and year fields for inbook, incollection, inproceeding entries.

**Comment by tmalsburg** [comment]
The author and title fields of these entries typically have different values than the books/proceedings/collections in which they appeared. Proceedings and collections also don't have authors (but editors) so the authors can't be inherited.  The only value for which this is really relevant is the year, right?

Anyway, I agree that resolving crossreferences is a good idea but the data structure that helm-bibtex currently uses is not perfectly suited for that.  Entries are stored in a list and finding the crossreferenced entries in that list will be slow when the database is big.  I know that some people are using fairly huge bibliographies, so I'm reluctant to implement a naive solution.  Ideally, we'd switch to hash tables but I'm not sure how exactly it should be done. Hash tables don't preserve the order of entries and while there are solutions for that they may have negative implications for memory use and performance.  Hash tables are desirable for independent reasons, too, so I'll keep thinking about it.

**Comment by tmalsburg** [comment]
Could you try the version in the branch [hash-table](https://github.com/tmalsburg/helm-bibtex/tree/hash-table)?  In that branch, I added crossref resolution (via a hash table) and also fixed some bugs.  Initial parsing is probably a but slower than before because the hash table has to be built but with my bibliography everything is still snappy.

**Comment by tmalsburg** [comment]
Forget about the hash-table branch.  That approach is flawed.  I'm have a new implementation. It's finished but I'd like to do some more testing.

**Comment by scottmartincampbell** [comment]
I was pretty busy the last few days and hadn't been able to get to it and was just going to give the hash-table branch a go. Thanks for the hard work. I'd looked over the code before posting the issue in the first place, but didn't know enough about managing large sets of data with elisp to tackle it. Thanks.

**Comment by tmalsburg** [comment]
I just uploaded the code of crossref resolution.  After some testing it seems to work well.  Enjoy.

**Comment by mgttlinger** [comment]
Is this feature gone again or should I open an issue for e.g. the year not getting populated from the cross-referenced `proceedings` entry?

**Comment by mgttlinger** [comment]
Nvm there was a comma missing which broke it.
