### ISSUE TITLE
helm-bibtex and zotxt

### ISSUE THREAD

**Issue by fpopineau** [tmalsburg/helm-bibtex#292]
Hi,

This is a request for an enhancement in case someone would like to pick up the idea!

When using Zotero, there are 2 plugins called [zotxt](https://github.com/egh/zotxt) and [better-bibtex](https://retorque.re/zotero-better-bibtex/) which allow to talk to Zotero from emacs.
What is interesting is that biblatex is also able to talk the same way to Zotero:
```
\addbibresource[location=remote]
                {http://localhost:23119/better-bibtex/collection?/0/8CV58ZVD.biblatex}
```
So it would be very nice that helm-bibtex be able to use the same source to get its list of bib entries!

Regards,

**Comment by tmalsburg** [comment]
Interesting.  Could you please explain the benefits of this approach compared to exporting `.bib` files.  I'm not familiar with Zotero.

If we wanted to implement something like this, we'd need something like a plug-in infrastructure for sources but I doubt there is sufficient demand to justify the effort.

**Comment by fpopineau** [comment]
Actually, after second thought, I wonder if it is a good idea at all.
I jumped quickly on this idea because I saw that biblatex was able to talk to Zotero this way.
But that kills the portability of your documents quickly ! So I think it is much better to go
through the use of good old .bib files.

**Comment by tmalsburg** [comment]
Okay. I'll close this issue then.
