### ISSUE TITLE
Add a configuration option to prevent proactive reloading

### ISSUE THREAD

**Issue by mwlodarczak** [tmalsburg/helm-bibtex#297]
While I understand its rationale, I find the new proactive reloading of bibliography quite frustrating as it kicks in every time I save the BIB file. I wonder whether adding a variable that controls this behaviour would be an option?

**Comment by tmalsburg** [comment]
While I sympathize, I'm worried about inflation of customization variables; we already have too many if you ask me.  Perhaps a better solution would be to reload the bibliography in the background so that users don't have to wait?  This could be implemented using threads which were introduced in Emacs 26.

**Comment by mwlodarczak** [comment]
Titus von der Malsburg <notifications@github.com> writes:

> While I sympathize, I'm worried about inflation of customization
> variables; we already have too many if you ask me. Perhaps a better
> solution would be to reload the bibliography in the background so that
> users don't have to wait? This could be implemented using threads
> which were introduced in Emacs 26.

Indeed, that would be a good compromise. I understand the desire to keep
the number of customisation variables to a minimum but I would argue
that reloading on each save is such an invasive behaviour that it does
warrant making an exception.

Marcin

**Comment by tmalsburg** [comment]
Could you make a PR please?

**Comment by mwlodarczak** [comment]
Sure. I think that's all it takes: [PR #301](https://github.com/tmalsburg/helm-bibtex/pull/301).

**Comment by rdiaz02** [comment]
If I may, I'd like to raise this issue again. I've fixed what I think was a bug in the original PR and added a longer docstring that specifically addresses @tmalsburg question:

> If someone loads helm-bibtex with the default setting for bibtex-completion-watch-bibliography and then decides that they don't want to proactively reload the bibliography, they have to restart Emacs with the new setting, right?

The answer is yes: changing the value of the variable after loading helm-bibtex has no effect.

This is the PR: https://github.com/tmalsburg/helm-bibtex/pull/443

**Comment by tmalsburg** [comment]
See `bibtex-completion-watch-bibliography`.
