### ISSUE TITLE
Insert bibtex reference in notes template

### ISSUE THREAD

**Issue by mclearc** [tmalsburg/helm-bibtex#302]
I'd like to include the complete bibtex entry in the notes file for archival purposes (and for completeness with using with latex/pandoc). I'm not clear how this might work though -- currently I have:

```emacs-lisp
(setq bibtex-completion-notes-template-multiple-files "---\ntitle: '${author} (${year}): ${title}'\nnocite: |\n   @${=key=}\n---\n\n[PDF Link](${file})\n\n```{.bibtex}\n INSERT BIBTEX HERE \n```")
```

Am I right to think that there is no straightforward way to insert the whole bibtex entry in the template?

**Comment by tmalsburg** [comment]
Hi Colin, you are right that there is no way to include the BibTeX automatically in the notes template.  I suspect that very few users will need this feature, so I'm currently not inclined to include it.  But as always with Emacs, you can probably hack something with some lines of Elisp.

**Comment by jagrg** [comment]
See org-ref-get-bibtex-entry in the org-ref code base. You can use it like this:

(insert (org-ref-get-bibtex-entry KEY))
