### ISSUE TITLE
Make bibtex-completion a separate package on MELPA

### ISSUE THREAD

**Issue by tmalsburg** [tmalsburg/helm-bibtex#312]
See https://github.com/Zaeph/org-roam-bibtex/issues/2 for context.

**Comment by myshevchuk** [comment]
Hi! I'm the co-maintainer of `org-roam-bibtex` for what it matters.
Please, could you revert this
```
;; Package-Requires: ((bibtex-completion "1.0.0") (helm "1.5.5") (cl-lib "0.5") (emacs "24.1"))
```
to the state before 3e75018 meanwhile, until `bibtex-completion` is actually packaged on MELPA. It seems that `straight` fails to build `helm-bibtex` because it
```
"Could not find package bibtex-completion in recipe repositories: (org-elpa melpa gnu-elpa-mirror emacsmirror-mirror)"
```

**Comment by myshevchuk** [comment]
Never mind, I pinned to the earlier commit.

**Comment by tmalsburg** [comment]
Hi, I know this is annoying but if the MELPA recipe gets merged and this pacakge is not package yet we get a conflict as well.  No idea how to do this without causing this friction.

**Comment by myshevchuk** [comment]
No problem, I figured it out. Thank you!

**Comment by tmalsburg** [comment]
MELPA PR here: https://github.com/melpa/melpa/pull/6840

**Comment by salotz** [comment]
@myshevchuk out of laziness on my part how did you pin?

**Comment by myshevchuk** [comment]
@salotz I'm using doom emacs and they have a macro for that.
```
(package! helm-bibtex
  :recipe (:host github :repo "tmalsburg/helm-bibtex")
  :pin "3cff6bd")
```

**Comment by salotz** [comment]
@myshevchuk thanks for the tip. Doom emacs seems to be getting popular! I figured it out for vanilla with `use-package`, just needed to add melpa-stable to my package lists and similarly pin:

```
(use-package helm-bibtex
  :ensure t
  :pin melpa-stable)

```

**Comment by tmalsburg** [comment]
bibtex-completion is now available on MELPA.

**Comment by tmalsburg** [comment]
While preparing the package I noticed that we actually depend on Emacs 26.1.  I hope that's not a problem for too many people.  (Current Ubuntu LTS, 18.04, comes with Emacs 25.)

**Comment by salotz** [comment]
I started compiling my own emacs a while ago because many packages require new 26. Ubuntu 20.04 comes out soon anyways with 26 I believe and userspace package managers are becoming more popular so I think its alright.
