### ISSUE TITLE
tab on ivy-bibtex to open command list?

### ISSUE THREAD

**Issue by bdarcus** [tmalsburg/helm-bibtex#313]
Is there a way I can configure so that ivy-bibtex behaves the same as helm-bibtex here; using `TAB` instead of `M-o` to open the command list?

While I have you, if yes, why is that not default?

**Comment by tmalsburg** [comment]
I don't use ivy myself. The code was contributed by a user.  But I think the key-bindings may be the default in ivy?  Probably best to ask there.

**Comment by bdarcus** [comment]
Thanks.

Yes, you are correct. That is the binding for `ivy-dispatching-done`.
