### ISSUE TITLE
melpa install broken

### ISSUE THREAD

**Issue by seanfarley** [tmalsburg/helm-bibtex#314]
Looks like you added a dependency on a not-yet-merged version of `bibtex-completion` in 3e750181dfd31469e5550d4c9282f812cc6417ea, fyi. This broke installations from melpa since melpa builds from master. Just a heads up.

Also, `bibtex-completion` doesn't specify `biblio` as a dependency. From that same commit, it seems `{ivy,helm}-bibtex` removes `(biblio "0.2")` from `Package-Requires` but `bibtex-completion` doesn't have that.

Thanks for the great packages!

**Comment by Xunius** [comment]
Hi,
I found the same error. My `M-x list-packages` shows the following:
```
helm-bibtex is an incompatible package.

     Status: Incompatible because it depends on uninstallable packages.
    Archive: melpa
    Version: 20200415.1311
     Commit: 1e5b50652d1f5189cfeb6b5ce3c4437e0239d4f5
    Summary: A bibliography manager based on Helm
   Requires: bibtex-completion-1.0.0 (not available), helm-1.5.5, cl-lib-0.5, emacs-24.1
   Homepage: https://github.com/tmalsburg/helm-bibtex
```
Hope this helps.

**Comment by tmalsburg** [comment]
The MELPA PR for fixing this has been merged an hour ago.  Please try again.

**Comment by tmalsburg** [comment]
Thanks for pointing out the missing biblio dependency.  This is fixed now.

**Comment by Xunius** [comment]
Yes it worked for me now.

**Comment by tmalsburg** [comment]
Awesome, thanks for confirming.  Need to figure out how cleanly navigate such upgrades with MELPA in the future.
