### ISSUE TITLE
escape brackets in file path for org links

### ISSUE THREAD

**Issue by wo** [tmalsburg/helm-bibtex#319]
My PDF files are in a directory called '[A-Z]'. When I insert citations with links to the PDF into an org file, the brackets in the file path are not escaped, resulting in a malformed link of the form [[file:/foo/[A-Z]/bar.pdf][title]].

**Comment by tmalsburg** [comment]
Thanks for reporting this.  We're using org infrastructure to generate links.  This should make sure that everything is escaped properly (using whatever method org developers deem appropriate at a given time).

**Comment by tmalsburg** [comment]
LaTex stuff (e.g. curly braces) is now also being stripped from the title when generating links.
