### ISSUE TITLE
bibtex-completion-at-point void with bibtex-completion 2.0.0 and helm-bibtex-20200429.1606

### ISSUE THREAD

**Issue by gelbwald** [tmalsburg/helm-bibtex#322]
Hi,

I just upgraded helm-bibtex to MELPA 20200429.1606. I had bibtex-completion 2.0.0 from MELPA stable installed. After upgrading helm-bibtex I got "Symbol's function definition is void: bibtex-completion-at-point" when calling helm-bibtex. Upgrading bibtex-completion to MELPA 20200501.1524 solved the issue. Perhaps the dependency has to be updated?

- gelbwald

**Comment by tmalsburg** [comment]
Hi, there is no stable version of this software.  MELPA added the stable package without my knowledge and I see it's horribly outdated.  Please install the package from standard MELPA.  (Ironically, MELPA maintainers themselves advice against using MELPA stable.)

Apart from that: We don't have and never had (I think) a function called `bibtex-completion-at-point`.  So I'm not sure why you're getting this error message.  Googling `bibtex-completion-at-point` yields only one hit: this issue.  Strange.
