### ISSUE TITLE
Link to pdf in org mode doest not work : function definition is void : org-link-make-string

### ISSUE THREAD

**Issue by MigAP** [tmalsburg/helm-bibtex#326]
When using the default configuration given in the README : 

`(setq bibtex-completion-format-citation-functions
  '((org-mode      . bibtex-completion-format-citation-org-link-to-PDF)
    (latex-mode    . bibtex-completion-format-citation-cite)
    (markdown-mode . bibtex-completion-format-citation-pandoc-citeproc)
    (default       . bibtex-completion-format-citation-default)))`

I get the following error : **Symbol's function definition is void: org-link-make-string** , when trying to insert a link to the pdf in an org file. 
I use Emacs 26.3. 

I hope I gave all the necessary information. 

Best regards

**Comment by tmalsburg** [comment]
What's your `M-x org-version`?

**Comment by MigAP** [comment]
9.1.9

**Comment by tmalsburg** [comment]
Should be fixed. Could you please confirm?

**Comment by MigAP** [comment]
I manually modified the _bibtex-completion.el_ and I did `eval-buffer` and it worked ! 

The links are inserted automatically and they work fine.

**Comment by tmalsburg** [comment]
Great, thanks.
