### ISSUE TITLE
bibtex-completion-edit-notes-default inserting duplicate #'TITLE when using multiple notes files

### ISSUE THREAD

**Issue by umbromancer** [tmalsburg/helm-bibtex#327]
Hi,
Thank you for helm-bibtex!

`(bibtex-completion-edit-notes-default KEYS)` seems to duplicate the #+TITLE property when creating a new notes file (unfortunately I still don't know enough elisp to ensure this... yet!)

For example, calling on an existing key `(bibtex-completion-edit-notes '("bibtex-completion-edit-notes"))` renders:

``` elisp
#+TITLE: #+TITLE: Notes on: Boes, J. R., Gumuslu, G., Miller, J. B., Gellman, A. J., & Kitchin, J. R. (2015): Estimating bulk-composition-dependent H2 adsorption energies on Cu_xpd_1-x alloy (111) surfaces
```

**Comment by tmalsburg** [comment]
Hi, thanks for reporting this.  I tried to reproduce this but failed.  Do you have a step-by-step recipe?  And could you please try with `emacs -q` and share your config?  Thank you!

**Comment by umbromancer** [comment]
Hi Titus, I managed to run a minimal example in vanilla emacs **without** the duplication problem. Seems like this is attributable to my emacs doom configuration. Haven't managed to find out what though. Will see if I can spot what and then notify if need be. Sorry to disturb you. Thank you!

**Comment by tmalsburg** [comment]
Thanks for the feedback and good luck!
