### ISSUE TITLE
multiple search sources issue

### ISSUE THREAD

**Issue by wdysun** [tmalsburg/helm-bibtex#329]
Sorry this might be silly, I am new to helm-bibtex but I find a bit difficult to use it. I installed it from MELPA, I tried `M-x helm-bibtex` I could put some pattern word and pressed TAB and wonderfully I could get some citation from web searches.  

Then I added my main bib database file to emac init file as following:

``
(setq bibtex-completion-bibliography
      '("~/Dropbox/biblio/myrefs.bib"))
``

When I do `M-x helm-bibtex` I can see my main database, and I can search patterns over it. But I can't see how I can search over the web resources. I am sure I can do both local search and web searches, but I am struggling to do it.

This would be particularly useful when I don't find something in the local database and I want to find something on the web to be added to the local database.

How do I do this?

**Comment by tmalsburg** [comment]
This is a helm question.  It used to be possible to switch between sources with the left and right arrow keys but they removed that some time ago.  There is probably a new key binding but I haven't checked.  What I do is just entering some random characters, the there are no entries in the first source and you get to see the other below.  Ugly I know.  If you by any chance feel like looking up helm documentation for the key bindings ... :)
