### ISSUE TITLE
Open directory with the same key name if exists

### ISSUE THREAD

**Issue by ledohod** [tmalsburg/helm-bibtex#334]
Hi,

Is it possible to specify a directory with the same key as the PDF file, so that when Action is to open the PDF, if directory exists with the same key, then both will be given as options to open?

Or search recursively inside folder with the same key.

Thanks.

**Comment by tmalsburg** [comment]
Hi, the feature you describe does not currently exist.  In the future there will be a plug-in based method for finding associated files, and the way I envision it, it would also support finding directories instead of files.  Having said that, the chances that I will find time to implement this system in the near future are rather slim.

**Comment by ledohod** [comment]
I was thinking just adding a new action which opens a key-filtered helm file finder in the PDF direcotry. I am pretty basic with Elisp but will give it a shot.

**Comment by tmalsburg** [comment]
Adding a custom action should be relatively easy.  You can use `bibtex-completion-open-pdf` as a starting point.  But the icons indicating whether the article is present or not would not reflect the state of affairs.  Fixing that is perhaps a bit more difficult.

**Comment by ledohod** [comment]
I have finally got round to this:
`  ;; Add action to browse files as the default action
  (defun my-helm-bibtex-find-files (key)
    "Find files for a single selected entry."
    (if (not (listp key))
        (progn
          (let ((pdf (bibtex-completion-find-pdf
                      key bibtex-completion-find-additional-pdfs)))
            (if (= (length pdf) 0)
                (message "No files found for this entry: %s" key)
              (helm-find-files-1
               (concat (nth 0 bibtex-completion-library-path) "/" key)))))
      (message "Please select only one entry.")))

  (helm-add-action-to-source
   "Find files" 'my-helm-bibtex-find-files helm-source-bibtex 0)
`
I am very basic with `Elisp` so this is pretty simple but does exactly what I want it to do. However, it seems the action list is build quite late and this action always a appears as second in the list to the original, default action. I am using `use-package` and put the code in the `:config` section, also I am using `straight` for package management. Where should I put the above code? I've tried `require`, `:demand t` but to no avail.

**Comment by ledohod** [comment]
So, I've overridden the default action function. This is mostly because some references contain lots of associated files that I usually put them in the folder with the same name as the key, and I keep all bibliography files in the same folder.

```
;; Customise `helm-bibtex' actions
(defconst iceberg-bibliography-dir (expand-file-name "~/library/bibliography")
  "Bibliography directory that should contain all bibliography files.")

(defun iceberg//helm-bibtex-key-files (key)
  "List files in `iceberg-bibliography-dir' associated with KEY.
  Search for files starting with KEY and/or files in directory
  named KEY within `iceberg-bibliography-dir'."
  (let* ((files (directory-files iceberg-bibliography-dir t key))
         (kfiles (f-uniquify-alist
                  ;; Remove directory key if present, process it separately; or,
                  ;; if no files were found and `directory-files' listed all
                  ;; files in `iceberg-bibliography-dir', remove all files not
                  ;; matching key
                  (delq nil
                        (mapcar (lambda (x) (and (and (not (file-directory-p x))
                                                      (string-match-p key x))
                                                 x))
                                files))))
         ;; Process key directory if it exists
         (kdir (concat iceberg-bibliography-dir "/" key))
         (dfiles (if (file-directory-p kdir)
                     (--map (cons it (concat key "/" (f-filename it)))
                            (directory-files-recursively kdir "."))
                   nil)))
    (append kfiles dfiles)))

;; Override the default action function to list all files
(defun bibtex-completion-open-pdf (keys &optional fallback-action)
  "Open files with KEY prefix and/or in KEY directory."
  (if (= (length keys) 1)
      (let* ((key (car keys))
             (files (iceberg//helm-bibtex-key-files key)))
        (cond
         ((> (length files) 1)
          (let* ((choice (completing-read "File: " (mapcar 'cdr files) nil t))
                 (file (car (rassoc choice files))))
            (funcall bibtex-completion-pdf-open-function file)))
         (files
          (funcall bibtex-completion-pdf-open-function (car files)))
         (fallback-action
          (funcall fallback-action (list key)))
         (t
          (message "No files found for key: %s" key))))
    (message "Please select only one entry.")))
```

**Comment by tmalsburg** [comment]
> but it seems the action list is constructed only when helm-bibtex is called for the first time, so added actions appear as second and third as opposed to being last.

I don't use use-package but a plain (and somewhat messy) configuration script.  So I can't help with this. Sorry.
