### ISSUE TITLE
Setting `ivy-bibtex-default-action` to `bibtex-completion-edit-notes` doesn't work

### ISSUE THREAD

**Issue by fapdash** [tmalsburg/helm-bibtex#337]
## Reproduction

My config looks something like this:

```
(use-package ivy-bibtex
  :ensure t
  :after org-ref
  :bind ("C-c n b" . ivy-bibtex)
  :config
  (setq
   ;; more config..
   bibtex-completion-pdf-field "file"
   ivy-bibtex-default-action 'bibtex-completion-edit-notes))
```

1. call `ivy-bibtex`
![screenshot_99](https://user-images.githubusercontent.com/459631/91662959-13930000-eae6-11ea-95a4-29c0015a5f8f.png)
2. `<return>` or `<C-j>`

## Expected
Creates new note or shows existing note file.

## Actual

Fails with the following warning:
```
Warning (:warning): Bibtex-completion couldn't find entry with key "2017 How to Take Smart Notes Sönkre Ahrens book Ahrens2017a".
```

Editing the note by keying `M-o` -> `e` (edit notes via ivy context menu) works without problems.

## Assumption
It seems that the key that gets passed to `bibtex-completion-edit-notes` is wrong.  
`"2017 How to Take Smart Notes Sönkre Ahrens book Ahrens2017a` instead of `Ahrens2017a`?

**Comment by tmalsburg** [comment]
Instead of `bibtex-completion-edit-notes` please try `ivy-bibtex-edit-notes`.

**Comment by fapdash** [comment]
Oh, that was easy. Thanks you!
