### ISSUE TITLE
Adding current folder to bibtex-completion-bibliography

### ISSUE THREAD

**Issue by DrWaleedAYousef** [tmalsburg/helm-bibtex#346]
I tried something like
```
(setq bibtex-completion-bibliography '("SOME PATH" "./"))
```
so that when I try to open the pdf of the selection it look at the current folder as well. It does not work!

**Comment by tmalsburg** [comment]
This variable is used to specify BibTeX files that should be loaded, not directories.  Please have a look at the documentation and the examples in the README.org.

To configure the directories used to locate PDFs, use `bibtex-completion-pdf-field`.  There's currently no way to dynamically include the current directory, but you could write a wrapper around `helm-bibtex` or `ivy-bibtex` that temporarily sets `bibtex-completion-pdf-field` such that it includes the current directory.
