### ISSUE TITLE
option to add tilde (~) for an unbreakable space

### ISSUE THREAD

**Issue by gabriben** [tmalsburg/helm-bibtex#352]
It [is considered good practice](https://tex.stackexchange.com/questions/41264/what-is-the-difference-in-citing-referencing-with-or-without-tilde) in TeX to write `~\cite{}`, because the tilde guarantees that there will be no linebreak between the word and its associated citation. Is there a way to add "~" before cite/citep/parencite... by default with helm-bibtex?

Thx

**Comment by tmalsburg** [comment]
You can provide your own citation function via the customization variable `bibtex-completion-format-citation-functions`.  Simply modify `bibtex-completion-format-citation-cite` and use that instead of the default.
