### ISSUE TITLE
ivy-bibtex not parsing bib file

### ISSUE THREAD

**Issue by roberthowton** [tmalsburg/helm-bibtex#358]
Hi,

First of all, thanks for your work on this fine package. I have been using Ivy-BibTeX on Spacemacs for a while now, but I am having trouble configuring it on a custom Emacs configuration I'm currently tinkering with. I believe I have Ivy working properly, but when I call `ivy-bibtex` it does not seem correctly to parse the .bib file I direct it to. Instead of the expected list of 1409 BibTeX entries that shows up when I call `ivy-bibtex` on Spacemacs, I get the following in my message buffer:
```
(1/0) BibTeX entries:
```
And when I press enter I get the following error: `ivy-call: Wrong type argument: listp, ""`. Here is my config, which is pretty much the same as what I have in my Spacemacs init file:
```
(use-package ivy-bibtex
 :config
 (setq bibtex-completion-bibliography-path '("~/Documents/Library/library.bib"))
 (setq bibtex-completion-library-path '("~/Documents/Library/"))
 (setq bibtex-dialect 'biblatex)
)

(autoload 'ivy-bibtex "ivy-bibtex" "" t)
;; ivy-bibtex requires ivy's `ivy--regex-ignore-order` regex builder, which
;; ignores the order of regexp tokens when searching for matching candidates.
;; Add something like this to your init file:
(setq ivy-re-builders-alist
      '((ivy-bibtex . ivy--regex-ignore-order)
        (t . ivy--regex-plus)))
```
I installed `ivy-bibtex` from MELPA, and as far as I can tell I'm not missing any dependencies. Any idea what I've done wrong?

**Comment by tmalsburg** [comment]
> (1/0) BibTeX entries:

Not sure where this message is coming from. To my knowledge ivy-bibtex doesn't generate such messages.

Typically if people has problems like this, the cause is a syntax error in the .bib file.  Please have a look at [this section](https://github.com/tmalsburg/helm-bibtex#helm-bibtex-doesnt-show-any-entries) of the documentation (applies to ivy-bibtex, as well):

**Comment by roberthowton** [comment]
Thank you for the swift reply, @tmalsburg! I followed the instructions in the section of the documentation you linked to, but no errors appeared: `(bibtex-completion-candidates)` showed no errors in my library.bib file, while `bibtex-validate` outputs `Buffer is syntactically correct'. 

As for the message, I am not sure, but I get this message at the top of the buffer when I call `ivy-bibtex` in Spacemacs:

```
1409 BibTeX entries:
```
As in the attached image.

![ivy-bibtex](https://user-images.githubusercontent.com/29513143/107949443-54a0a300-6fa6-11eb-9c86-7d8033749d06.png)

**Comment by tmalsburg** [comment]
Hm, not sure what's going on.  Your configuration looks correct to me.  Though I'm not sure that `(setq bibtex-dialect 'biblatex) is doing.  Since I'm not familiar with ivy, I also don't know whether the bit about `ivy-re-builders-alist` is required.  Could you try to prepare a minimal reproducible example that works with `emacs -q`?

**Comment by roberthowton** [comment]
Sure! This is my first time creating a minimal reproducible example, so I hope has everything it needs. In any case, I get the same surprising message (viz., `(1/0) BibTeX entries:` if I evaluate this code block in `emacs -q`:
```
(require 'package)
(add-to-list 'package-archives
 	     '("melpa" . "https://melpa.org/packages/"))

(package-initialize)

(package-refresh-contents)

;; following: https://oremacs.com/swiper/#installing-from-emacs-package-manager
(package-install 'counsel)

;; following: https://oremacs.com/swiper/#getting-started
(ivy-mode 1)
(setq ivy-use-virtual-buffers t)
(setq ivy-count-format "(%d/%d) ")

(package-install 'ivy-bibtex)

;; ivy-bibtex requires ivy's `ivy--regex-ignore-order` regex builder, which
;; ignores the order of regexp tokens when searching for matching candidates.
;; Add something like this to your init file:
(setq ivy-re-builders-alist
      '((ivy-bibtex . ivy--regex-ignore-order)
        (t . ivy--regex-plus)))

(setq bibtex-completion-bibliography-path '("~/test.bib"))
```
and then run `M-x ivy-bibtex RET`. The .bib file contains the following entry:
```
$ cat ~/test.bib

@article{Adamson2011,
  title = {Posterior {{Analytics}} 2.19: {{A Dialogue}} with {{Plato}}?},
  author = {Adamson, Peter},
  date = {2011},
  journaltitle = {Bulletin of the Institute of Classical Studies},
  volume = {54},
  pages = {1--19},
  issn = {00760730},
  doi = {10.1111/j.2041-5370.2011.tb00010.x},
  url = {http://doi.wiley.com/10.1111/j.2041-5370.2011.tb00010.x},
  keywords = {\#nosource},
  timestamp = {2020-11-20T14:17:04Z}
}% 
```

**Comment by tmalsburg** [comment]
There is no configuration variable called `bibtex-completion-bibliography-path`.  You need to set `bibtex-completion-bibliography`.
