### ISSUE TITLE
Multiple notes per source with page numbers?

### ISSUE THREAD

**Issue by adam52** [tmalsburg/helm-bibtex#359]
A significant portion of my academic sources are books. So as you can imagine, I often collect multiple notes from each source. helm-bibtex specifies one notes file per source, so individual notes become headings, within the same file.

So if I want to insert a cite link for note 5, which references pages 57-59 from source 1, how should I setup helm-bibtex/org-ref (or my bibtex db) to automatically add the right page numbers, when I have multiple notes per source?

I thought about breaking notes into multiple @inbook entries. But unless I am citing a chapter heading, it means inserting an artificial title, which will get added to the citation. I also thought about using multiple @book entries but with different page numbers. But this seems like it would make a total mess of my helm-bibtex search view...

Any ideas?

Thanks,

**Comment by tmalsburg** [comment]
I'm using [org-pdftools](https://github.com/fuxialexander/org-pdftools) for this purpose.

**Comment by adam52** [comment]
Thanks Titus. So suppose you have a the following notes file:

    #+TITLE: Bradley, J. (1973): Essential Mathematics For Economists
    #+STARTUP: latexpreview inlineimages
    -----

    * Dynamic models: the consumption function
    Taken from p. 164

    * Changes in Capital Stock
    Taken from p.  188

    * The Accelerator-Multiplier Model
    Taken from p. 200

You now start working on a research paper and you want to cite your notes on the Accelerator-Multiplier Model, from page 200. How do you configure `helm-bibtex` so that when you insert the reference, your cite link automatically pulls the page reference, i.e., this:

    [[cite:bradley1973es][p. 200]]

instead of this:

    cite:bradley1973es

By-the-way, a good part of my references were authored before the days of Pdfs. So if you have any guidance on how we should be documenting page numbers in our notes (whether as part of a properties drawer, etc.) to make this work, that would be fantastic!

Thanks,

**Comment by tmalsburg** [comment]
I'm not sure I understand.  You say that you'd like to cite your notes but notes are not publications, so how do you cite them?  But your example suggests that you'd like to cite a specific page of a publication, but how does this involve notes?  Also, the cite syntax that you're using suggests that you're using org-ref.  Are you sure that you're question is about helm-bibtex not org-ref?  These are different projects.  The scope of helm-bibtex is to provide a way to search entries in your bibliography.  org-ref offers bibliography tools for authoring org documents. It uses helm-bibtex in some places.

**Comment by adam52** [comment]
Hi Titus - thank you for your response. 

I am not looking to cite my notes. I am looking to cite the page or page range from the source where the notes were taken.

My question was whether there is a recommended way to document page numbers (either in our `.bib` file or in our notes) so that adding cite links of the form [[cite:refkey][p. 32]] can be automated, similar to how `helm-bibtex` inserts cite links for entire sources?

**Comment by tmalsburg** [comment]
> I am not looking to cite my notes. I am looking to cite the page or page range from the source where the notes were taken.

Sorry, that wasn't clear. Have you tried org-pdftools?  I use it exactly for this purpose.  I configured it such that it includes the page number by default in the link.  But the links are not org-ref links as in your example.  Here's my config:

```
(require 'org-pdftools)

(setq org-pdftools-root-dir "~/Documents/Uni/Bibliographie/")
(setq org-pdftools-link-prefix "pdftools")

(org-link-set-parameters "pdftools"
                         :follow #'org-pdftools-open
                         :complete #'org-pdftools-complete-link
                         :store #'org-pdftools-store-link
                         :export #'org-pdftools-export)

(defun tmalsburg-org-pdftools-get-desc-function (file page text)
  (format "“%s” (page %s)" text page))

(setq org-pdftools-get-desc-function #'tmalsburg-org-pdftools-get-desc-function)

(add-hook 'org-store-link-functions 'org-pdftools-store-link)
```

**Comment by adam52** [comment]
Ah fantastic. Thanks Titus! Are you able to use this same workflow for sources that do not have a pdf (eg. book)?

**Comment by tmalsburg** [comment]
> Are you able to use this same workflow for sources that do not have a pdf (eg. book)?

I don't know.  All my documents are in PDF format.  But the name `org-pdftools` suggests that it may be limited to PDFs.
