### ISSUE TITLE
Remove default action

### ISSUE THREAD

**Issue by ledohod** [tmalsburg/helm-bibtex#368]
I am having a problem with removing the default action, or ordering the actions in general.
`(helm-delete-action-from-source "Open PDF, URL or DOI" helm-source-bibtex)` doesn't take effect. I've put it in `:config` section in the `use-package`, I'm also using `straight`. I've tried `:demand` also I've tried it after `(require 'helm-bibtex)` but all to no avail.

But, it works when I run it after loading Emacs. What am I missing?

**Comment by tmalsburg** [comment]
I'm not an expert for use-package but I suspect that the your code tries to add/remove actions before the helm source (`helm-source-bibtex`) is created. Is that possible?

**Comment by ledohod** [comment]
I think that is what it is. I've tried requiring helm, bibtex but I am only a user of Emacs really, so I was thinking to call `helm-bibtex` within my init file and try to force it to build the source before changing the actions. I wonder whether I can call a function in Emacs suppress its effect?

**Comment by ledohod** [comment]
Ah, I've put the command on its own at the very end of my init file and it worked. I will try to figure out where what is going on with loading the init file. Thanks!

**Comment by tmalsburg** [comment]
Okay, thanks for the update.
