### ISSUE TITLE
expand proactive reloading to notes/pdf dirs

### ISSUE THREAD

**Issue by bdarcus** [tmalsburg/helm-bibtex#369]
In 2018, bibtex-completion added the feature "Reload bibliography proactively when bib files are changed."

The use case is when you're moving back and forth between, say, note taking on sources, and writing document that integrate those sources. With the expansion in last years of note support, and existing pdf integration, this seems like a natural extension.

Is there any reason not to extend this to PDFs and notes? 

As in, if I add a PDF or note to my respective configured directories, bibtex-completion will update the candidates. 

Something like this?

https://gist.github.com/bdarcus/6fa2918bfe5f4e89af44e2b0ceb0e550

cc @myshevchuk

_Originally posted by @bdarcus in https://github.com/tmalsburg/helm-bibtex/issues/242#issuecomment-812851362_

**Comment by tmalsburg** [comment]
[Copied from #242 discussion]: Good idea. The only downside that I see is that it could cause more reloads than users might like, especially users with very large bibliographies. For instance, say you have all notes in one file and you edit this file frequently and accordingly save it frequently, then Emacs would block every time you save that file and with large bibs like crypto.bib it would block for (I think) more than 30s. This could be addressed by allowing users to configure autoreloading on a fine-grained level but this would be complicated, potentially error prone, and perhaps not worth it. Not sure.

**Comment by tmalsburg** [comment]
Some more scenarios that are potentially difficult:

1. If a user also keeps other files in the directories that contain notes and PDFs, any change in those files will also trigger a expensive reloads which block Emacs.
2. If a user keeps PDFs in many different directories (referenced via the BibTeX file field), we'd have to watch all those directories. And any change in these directories, related or not, will trigger a reload.
3. In the previous case, we don't even know, a priori, which directories we need to watch.

I'm not saying that we shouldn't expand proactive reloading, but there are many different scenarios that we need to consider before implementing it.

**Comment by bdarcus** [comment]
Yeah, good points.

Hmm ...

**Comment by tmalsburg** [comment]
There may be a good solution, it's just not immediately clear to me what it is.

**Comment by bdarcus** [comment]
Just thinking out loud ...

Might this be a scenario for sensible default behavior, with a hook to
allow people to customize?

**Comment by tmalsburg** [comment]
You can already customize this without a hook.  Just set up the file watches in your config and let them reload the bibliography when something changes on disk.  For one specific setup (e.g. yours) this may actually be doable with a small handful of lines of code.  The difficult part is to come up with something that works for all users and all configurations.  When I implemented the current version of proactive loading, which is very basic, there were already users whose experience was degraded by this addition.  It's important to keep in mind that this package has quite a number of users who all have their own peculiar setups and preferences.  There's also other software that depends on bibtex-completion and it's current behavior (org-roam-bibtex, org-ref) and changes like this can easyly break things for them.  Not saying that this necessarily would break something but it's my experience that it's surprisingly difficult to anticipate due to all the accumulated complexity.

**Comment by bdarcus** [comment]
> You can already customize this without a hook. Just set up the file watches in your config and let them reload the bibliography when something changes on disk.

In that case, the simplest and most general solution is to not implement this, but put an example somewhere (docs, wiki, etc.).

> Not saying that this necessarily would break something but it's my experience that it's surprisingly difficult to anticipate due to all the accumulated complexity.

Yeah; I guess it's not surprising given how many disparate packages people are often trying to get working together.

**Comment by tmalsburg** [comment]
I think something like this (not tested) should do the trick for PDFs:

``` elisp
(file-notify-add-watch bibtex-completion-library-path
                       '(change)
                       (lambda (event) (bibtex-competion-candidates)))))
```

For notes you can use the same approach but with `bibtex-completion-notes-path`.  Let me know how it goes.

**Comment by bdarcus** [comment]
Thanks!

I added it to my (now pretty bare) wiki here:

https://github.com/bdarcus/bibtex-actions/wiki/Configuration#expand-proactive-loading-of-library-to-pdfs-and-notes

**Comment by tmalsburg** [comment]
Let's keep this issue open until we have added a working solution to the documentation.  Otherwise it will fall through the cracks.

**Comment by bdarcus** [comment]
Sure.

I seem to have something wrong with my emacs setup ATM, so I'll have to fix that first.

**Comment by bdarcus** [comment]
I think, aside from the typo, this is right.

But I can't confirm it ATM, I think because of idiosyncrasies in my implementation, which may take me a bit of time to sort out.

**Comment by bdarcus** [comment]
Two things:

First, to avoid the confusion below, I tested this with `helm-bibtex.`

Specifically, I:

1. opened library, and selected "edit notes" for an item without a note
2. new org buffer opens, and it appears to reload (because the "Done (re) loading" message)

But when I return to the library view, the new state doesn't show.

Not sure why not.

-------

Second, on this:

> But I can't confirm it ATM, I think because of idiosyncrasies in my implementation ...

Do you have any thoughts on this?

The bibtex-completion caching, and in turn clearing the cache etc, is of `bibtex-completion-candidates`.

But I think because completing-read works differently than ivy and helm (it doesn't have that separate notion of a "formatter"), I can't use those candidate strings without losing features that users want (namely, selection highlighting).

So my candidates are instead created using a different function that uses the output of format-entry, along with some hidden data to ensure uniqueness (really only the key is needed there).

Right now, then, I'm actually not caching the entries, which is a problem I need to fix in general, but also before I can test whether this bit works..

**Comment by bdarcus** [comment]
Update: I had a user request I add a cache, and so have done that. He has [confirmed](https://github.com/bdarcus/bibtex-actions/pull/71#issuecomment-817353793) the [README instructions](https://github.com/bdarcus/bibtex-actions#proactive-reloading-of-library) (adapted from your example) work.

So I think the example should be good to go for your docs.

**Comment by tmalsburg** [comment]
Thanks for the update.  I've added a section in the README, see [here](https://github.com/tmalsburg/helm-bibtex#refresh-bibliography-when-new-pdfs-and-notes-are-added).

**Comment by bdarcus** [comment]
I learned something you might appreciate.

If you add an optional parameter, that you don't use, to `bibtex-completion-candidates`, you can forego the lambda on the add-watch setup.

Explained here:

https://github.com/oantolin/embark/issues/176#issuecomment-817798025

**Comment by tmalsburg** [comment]
Hm, this would indeed simplifies the setup of the watch but other users of bibtex-completion-candidates will find the seemingly useless extra argument confusing.  Better to keep the interface clean the various functions orthogonal (to the extend possible).
