### ISSUE TITLE
Tweaking `bibtex-completion-add-pdf-to-library` to move and not just copy file

### ISSUE THREAD

**Issue by apc** [tmalsburg/helm-bibtex#372]
First: thanks for all your work on this!

I'm looking for way to make `bibtex-completion-add-pdf-to-library` move a file from its old location to the PDF library. I do this often enough that it'd be great to not have to keep track of which PDFs I've already moved to my library so I can avoid duplicates etc. 

My unsophisticated first thought would be to just rewrite `bibtex-completion-add-pdf-to-library` so that it has `(move-file-to-trash file)` after `(copy-file file pdf 1)`. But I'm wondering if there's a more elegant, and most importantly, 'safer' way to incorporate this sort of thing into `bibtex-completion`.

**Comment by tmalsburg** [comment]
Hey, I'm not aware of an command that moves files. But your approach seems reasonable.  If I understand correctly, the file will only be deleted if it was successfully copied.  Why do you think it's unsafe?  The only thing I would change is to remove the `1` in the `copy-file` command.  If there already is a file with that name, I would want to check what it is before overwriting it.

**Comment by apc** [comment]
Ah, good point. Looking over [the manual](https://www.gnu.org/software/emacs/manual/html_node/emacs/Copying-and-Naming.html) makes me think there is already a command that does what I want: `rename-file`. So simply changing `(copy-file file pdf 1)` to `(rename-file file pdf nil)` should work. Do you think it would be best to have a new function, perhaps `bibtex-completion-move-pdf-to-library`? Would you be interested in seeing a proposal for implementing this? 

You could have an option to use that or the default for the action `bibtex-completion-add-pdf-to-library`.

**Comment by tmalsburg** [comment]
> Would you be interested in seeing a proposal for implementing this?

Yes!

> You could have an option to use that or the default for the action `bibtex-completion-add-pdf-to-library`.

I'm not sure about having another option. We already have so many.  Instead I would add a recipe showing how to modify the current behavior to the documentation.

**Comment by apc** [comment]
OK, this is a first try. I'm sure there's a more elegant way to do this, but the following seems to work fine when used with `bibtex-actions`: 

```
(defun bibtex-completion-move-pdf-to-library (keys)
  "Add a PDF to the library for the first entry in KEYS.
The PDF can be added either from an open buffer, a file, or a
URL. If the PDF is a file, it will be moved to the library from
its original location."
  (let* ((key (car keys))
         (source (char-to-string
                  (read-char-choice "Add pdf from [b]uffer, [f]ile, or [u]rl? " '(?b ?f ?u))))
         (buffer (when (string= source "b")
                   (read-buffer-to-switch "Add pdf buffer: ")))
         (file (when (string= source "f")
                 (expand-file-name (read-file-name "Add pdf file: " nil nil t))))
         (url (when (string= source "u")
                (read-string "Add pdf URL: ")))
         (path (-flatten (list bibtex-completion-library-path)))
         (path (if (cdr path)
                   (completing-read "Add pdf to: " path nil t)
                 (car path)))
         (pdf (expand-file-name (completing-read "Rename pdf to: "
                                                 (--map (s-concat key it)
                                                        (-flatten bibtex-completion-pdf-extension))
                                                 nil nil key)
                                path)))
    (cond
     (buffer
      (with-current-buffer buffer
        (write-file pdf t)))
     (file
      (rename-file file pdf nil))
     (url
      (url-copy-file url pdf 1)))))

(defun bibtex-actions-move-pdf-to-library (keys)
 "Add PDF associated with the KEYS to library.
The PDF can be added either from an open buffer, a file, or a
URL. If the PDF is a file, it will be moved to the library from
its original location."
  (interactive (list (bibtex-actions-read)))
  (bibtex-completion-move-pdf-to-library keys))

(define-key bibtex-actions-map (kbd "m") 'bibtex-actions-move-pdf-to-library)

```

Any suggestions would be welcome—I'm very much a rookie here!

**Comment by apc** [comment]
OK, this may be a simpler way of doing things, though it would modify `bibtex-actions-add-pdf-to-library`, rather than adding the option to move rather than copy: 

```
(defun my-copy-as-rename (orig &rest args)
  (cl-letf (((symbol-function #'copy-file) #'rename-file))
    (apply orig args)))

(advice-add 'bibtex-completion-add-pdf-to-library :around #'my-copy-as-rename)
```

**Comment by apc** [comment]
Last try, adding an boolean that would determine whether or not the advice does anything: 

```elisp
(defcustom bibtex-completion-add-pdf-and-move nil
    "If non-nil, adding PDF file to library will move file from the original location."
    :group 'bibtex-completion
    :type 'boolean)

  (defun bibtex-completion-advice-copy-as-rename (orig &rest args)
    (if bibtex-completion-add-pdf-and-move
        (cl-letf (((symbol-function #'copy-file) #'rename-file))
      (apply orig args))
    (apply orig args)))

  (advice-add 'bibtex-completion-add-pdf-to-library :around #'bibtex-completion-advice-copy-as-rename)
```

**Comment by tmalsburg** [comment]
I like the solution using `advice-add`, neat.  And thanks for sharing!
