### ISSUE TITLE
Add org-cite citation command function

### ISSUE THREAD

**Issue by bdarcus** [tmalsburg/helm-bibtex#373]
Just FYI, looks like `org-cite` (native org citation support) will be merged soon.

https://lists.gnu.org/archive/html/emacs-orgmode/2021-04/msg00790.html

I've implemented it on a branch of bibtex-actions, but it makes more sense here.

https://github.com/bdarcus/bibtex-actions/pull/113

I'll wait a bit to merge it/or submit a PR.

**Comment by tmalsburg** [comment]
Woah, that looks cool.  Wasn't aware of this effort.  (No time to read mailing lists recently.)

We should definitely update the default citation functions.  The current default citation function (ebib-links?) are pretty outdated and I doubt that anyone is seriously using it.  I may be wrong though and that's why I hesitated to change it so far.  But with a standard org citation format it's a nobrainer.

**Comment by bdarcus** [comment]
> We should definitely update the default citation functions. The current default citation function (ebib-links?) are pretty outdated and I doubt that anyone is seriously using it. I may be wrong though and that's why I hesitated to change it so far. But with a standard org citation format it's a nobrainer.

Probably the obvious approach is to keep the current one, add the new one and then (probably not until `org-cite` is merged to master, and released as part of Org 9.5) make that default?

**Comment by tmalsburg** [comment]
Yes, that's a good plan.

**Comment by bdarcus** [comment]
FYI, I just committed an org-cite "follow processor".

https://github.com/bdarcus/bibtex-actions/commit/f5ac2b0ee67da189307a3496b95ee237e6726f98

As you'll see, it should be trivial to add one for `bibtex-completion`, which then would bind `bibtex-completion-at-point` to `org-open-at-point`.

**Comment by tmalsburg** [comment]
Relevant discussion: https://github.com/jkitchin/org-ref/issues/885#issuecomment-880294348

**Comment by tmalsburg** [comment]
A first baby step: a4e8b49

I decided to follow an approach that relies more on Emacs' text editing capabilities.  So there's no UI that prompts users for pre- and suffixes or citation styles.  The user can easily add them by hand.  Plus we can add a wrapper for oc-bibtex' UI later if we want as a separate citation function.

Other plans:
- Extend `helm-bibtex-with-local-bibliography` such that it uses the org file's bibliography (if any).
- Add a follow processor that opens the entry in helm-bibtex so that users have quick access to helm-actions.
- Similar for ivy-bibtex.
My understanding is that this should give us basic but more or less complete integration with oc-bibtex.  Am I missing something?

**Comment by bdarcus** [comment]
> * Do I need an insert processor?  This would override org's insert UI (if I understand correctly) but is that desirable?

I think the UX is better, but probably a matter of personal preference.

You can experiment with the one included in oc-basic to get a sense. Would just allow you to replace that UI, partially (as I have), or fully (as John).

> * What's the activate-processor doing?

John probably understands better than I, but see the gif of the csl-activate processor I link to above to get a sense.

**Comment by bdarcus** [comment]
@tmalsburg  - I took a look at ivy-bibtex and helm-bibtex; what you need in both to create insert processors for org-cite is a function in each that opens the browsing interface, but returns a single key string, or a list of keys. I don't see that ATM.

Let me know if you have any questions.

**Comment by tmalsburg** [comment]
Okay, I'm looking at oc-basic.el to figure out what needs to be done:

``` elisp
;;; Register processor
(org-cite-register-processor 'basic
  :activate #'org-cite-basic-activate
  :export-citation #'org-cite-basic-export-citation
  :export-bibliography #'org-cite-basic-export-bibliography
  :follow #'org-cite-basic-goto
  :insert (org-cite-make-insert-processor #'org-cite-basic--complete-key
                                          #'org-cite-basic--complete-style)
  :cite-styles
  '((("author" "a") ("caps" "c"))
    (("noauthor" "na") ("bare" "b"))
    (("nocite" "n"))
    (("note" "ft") ("bare-caps" "bc") ("caps" "c"))
    (("numeric" "nb"))
    (("text" "t") ("bare-caps" "bc") ("caps" "c"))
    (("nil") ("bare" "b") ("bare-caps" "bc") ("caps" "c"))))
```

My initial sense is that we need to do the following:

- helm/ivy-bibtex need to offer an insert processor.
- helm/ivy-bibtex need to offer a follow processor that open the search with the reference pre-selected (to give users quick access to actions).
- The slots for `:activate`, `:export-citation` , `:export-bibliography` can be recycled from the basic processor.

Not sure about the `:cite-style` property.  Is that specific to pandoc and/or the latex citation package used?  If yes, there won’t be a single default that will make the majority of users happy.

Either way, offering an insert and follow processor should be fairly easy.

**Comment by tmalsburg** [comment]
One problem: The bibliography configured in helm-bibtex is not necessarily the same as the one references in the org file. I guess we need to extend `helm-bibtex-with-local-bibliography` to work with local org bibliographies.

**Comment by tmalsburg** [comment]
How can I activate and use a processor after registering it with `org-cite-register-processor`?  I created a first sketch but it doesn't do anything.

**Comment by bdarcus** [comment]
I'll reply to your other questions in a subsequent comment, or edit this one. But in the meantime ...

> One problem: The bibliography configured in helm-bibtex is not necessarily the same as the one references in the org file. I guess we need to extend helm-bibtex-with-local-bibliography to work with local org bibliographies.

I was wondering about that too. Could you add that to bibtex-completions?

> How can I activate and use a processor after registering it with org-cite-register-processor? I created a first sketch but it doesn't do anything.

That merely makes that set of processors available.

To use, you do:

```elisp
(setq org-cite-follow-processor 'helm-bibtex)
```

**Comment by tmalsburg** [comment]
> > One problem: The bibliography configured in helm-bibtex is not necessarily the same as the one references in the org file. I guess we need to extend helm-bibtex-with-local-bibliography to work with local org bibliographies.
> 
> I was wondering about that too. Could you add that to bibtex-completions?

Yes, we already have `bibtex-completion-find-local-bibliography` which looks for the local bibliography in LaTeX documents but it can be extended to handle org files as well.

> To use, you do:
>
> (setq org-cite-follow-processor 'helm-bibtex)

Still doesn't work.  In fact the citation isn't even clickable. (It just looks clickable because it's underlined.)

Unrelated: Is anyone working on making the bibtex parser in oc.el faster?  It takes about 100 times longer to parse my bib than parsebib. I see there are provisions in the code for a cache but it doesn't appear to be working, so Emacs freezes for 30s every time I insert a key.

**Comment by bdarcus** [comment]
> Still doesn't work. In fact the citation isn't even clickable. (It just looks clickable because it's underlined.)

I take it by what you say below, the `oc-basic` insert processor does work for you?

What happens when you run `org-cite-insert` outside of a citation?

> Unrelated: Is anyone working on making the bibtex parser in oc.el faster?

IDK, but have noticed that.

**Comment by tmalsburg** [comment]
> I take it by what you say below, the oc-basic insert processor does work for you?

I can create new citations with the basic processor and add keys to existing citations, but I can't follow them.  After restarting Emacs, the citations are clickable (and I do get the little popup with the paper's title!) but nothing happens when I click.  Hm ...

**Comment by tmalsburg** [comment]
> I take it by what you say below, the oc-basic insert processor does work for you?

I can create new citations with the basic processor and add keys to existing citations, but I can't follow them.  After restarting Emacs, the citations are clickable (and I do get the little popup with the paper's title!) but nothing happens when I click.  Hm ...

**Comment by bdarcus** [comment]
Oh, I'm sorry; not had my morning coffee yet!

You're talking about follow. Have you tried `org-open-at-point` while on a citation?

**Comment by bdarcus** [comment]
I think, though am not sure, to make the citation links clickable such that they run `org-open-at-point`, they would need to be in an activate processor.

cc @jkitchin @andras-simonyi

**Comment by bdarcus** [comment]
> My initial sense is that we need to do the following:
> 
> * helm/ivy-bibtex need to offer an insert processor.

Yes.

> * helm/ivy-bibtex need to offer a follow processor that open the search with the reference pre-selected (to give users quick access to actions).

As I said on the other thread, I don't think that's necessary; just run the actions directly from point.

That's what I and @jkitchin, at least, are doing. I think opening the browsing UI should be one option there.

> * The slots for `:activate`, `:export-citation` , `:export-bibliography` can be recycled from the basic processor.

Correct, or any other processor.
 
> Not sure about the `:cite-style` property. Is that specific to pandoc and/or the latex citation package used? If yes, there won’t be a single default that will make the majority of users happy.

You don't need that; it's only for export processors, to expose what they can consume.

See my processor, for example:

https://github.com/bdarcus/bibtex-actions/blob/ae0ecf0d731b80d0bde3ee7b1c37666fcc582036/oc-bibtex-actions.el#L256

I'd actually encourage you to try this, just so you understand how modular all of this is.

```elisp
(org-cite-register-processor 'oc-bibtex-actions
  :insert (org-cite-make-insert-processor
           #'helm-bibtex-oc-insert
           #'oc-bibtex-actions-select-style)
  :follow #'oc-bibtex-actions-follow)
```
 
> Either way, offering an insert and follow processor should be fairly easy.

Yes.

**Comment by tmalsburg** [comment]
> You're talking about follow. Have you tried org-open-at-point while on a citation?

Ah, that works. Thanks. But clicking with the mouse doesn't do anything, which is counter-intuitive.

**Comment by tmalsburg** [comment]
> As I said on the other thread, I don't think that's necessary; just run the actions directly from point.

Not sure I understand: If there are multiple keys in the citation, that would execute the action for all of them, no? Firing up a helm-search, would allow users to execute functions on all or on individual entries in that citation.  Seem more flexible and also recycles and existing and familiar UI. 

> So just include what you actually provide code for.

Thanks. I was wondering about that.

> You don't need that; it's only for export processors, to expose what they can consume.

I'm relieved to hear :)

> But I'm still not sure whether or not that's a great idea.

I have to think about it. It's not immediately clear that this would simplify things sufficiently because (I think) my processor is going to contain some helm/ivy-specific code, so the potential overlap is perhaps not that big?  Not sure.

**Comment by bdarcus** [comment]
> Not sure I understand: If there are multiple keys in the citation, that would execute the action for all of them, no? Firing up a helm-search, would allow users to execute functions on all or on individual entries in that citation. Seem more flexible and also recycles and existing and familiar UI.

Ah, good point.

If point is on a citation-reference, then run directly (for example, open a menu to choose the action); if on the citation prefix, open helm?

John and I were discussing this recently on the other thread.

> I have to think about it. It's not immediately clear that this would simplify things sufficiently because (I think) my processor is going to contain some helm/ivy-specific code, so the potential overlap is perhaps not that big? Not sure.

I'm not either; think about it.

You can obviously reuse code freely across our projects. If you find doing so seems like a hassle, and think it might be confusing to users, maybe there's merit?

**Comment by jkitchin** [comment]
> > You're talking about follow. Have you tried org-open-at-point while on a citation?
> 
> Ah, that works. Thanks. But clicking with the mouse doesn't do anything, which is counter-intuitive.

For me, with the 'basic activate and follow processor, clicking on citation-reference opens the bibtex entry.

**Comment by bdarcus** [comment]
> For me, with the 'basic activate and follow processor, clicking on citation-reference opens the bibtex entry.

Maybe there's an org variable that governs this behavior? I can't find one ATM.

**Comment by tmalsburg** [comment]
> It's weird, because for me, I can click on links, but not on citations.

Same.

**Comment by bdarcus** [comment]
> > > You're talking about follow. Have you tried org-open-at-point while on a citation?
> > 
> > 
> > Ah, that works. Thanks. But clicking with the mouse doesn't do anything, which is counter-intuitive.
> 
> For me, with the 'basic activate and follow processor, clicking on citation-reference opens the bibtex entry.

Are you doing anything in your code so that you get the click access to your hydra?

I want that for my embark/which-key solution, but don't want to write my own activate processor.

**Comment by jkitchin** [comment]
I did add mouse-1 to the keymap that is added at activation. The activate processor in org-ref-cite is very easy to customize now.

**Comment by ms2d** [comment]
Here is a slight variation. This code overrides  @tmalsburg's [earlier improvement](https://github.com/tmalsburg/helm-bibtex/commit/a0d32ab16748b7b0c43d6421f1b497b7caf8e590) to add back the optional  prefix (and/or suffix).

The key benefit is that you can use this to add an `org-mode` styled citation with completion, that includes an optional locator. For example:

    [cite:@zipf1946wg, p. 51]

Here is the code:

     (defun ms2/bibtex-completion-format-citation-org-cite (keys)
        "This overrides bibtex-completion-format-citation-org-cite, adding functionality from bibtex-completion-format-citation-pandoc-citeproc."
        (let* ((prenote  (if bibtex-completion-cite-prompt-for-optional-arguments (read-from-minibuffer "Prenote: ") ""))
               (postnote (if bibtex-completion-cite-prompt-for-optional-arguments (read-from-minibuffer "Postnote: ") ""))
               (prenote  (if (string= "" prenote)  "" (concat prenote  " ")))
               (postnote (if (string= "" postnote) "" (concat ", " postnote))))
          (format "[%s%s%s]" prenote (s-join "; " (--map (concat "cite:@" it) keys)) postnote)))

      ;; apply new citation format
      (with-eval-after-load "helm-bibtex"
        (setq bibtex-completion-format-citation-functions
  	    '((org-mode . ms2/bibtex-completion-format-citation-org-cite))))

I have also found these references useful in working with the new `org-cite` format:

- [Introducing Citations (tecosaur 2021)](https://blog.tecosaur.com/tmio/2021-07-31-citations.html)
- [Earlier discussion on Github](https://github.com/tmalsburg/helm-bibtex/commit/a0d32ab16748b7b0c43d6421f1b497b7caf8e590)
