### ISSUE TITLE
[newbie] Symbol’s function definition is void: helm-bibtex-edit-notes

### ISSUE THREAD

**Issue by Elwro** [tmalsburg/helm-bibtex#377]
I have installed, via MELPA, bibtex-completion, helm, helm-bibtex, helm-org (and, fwiw, org-ref, org-noter, and org-roam). My ultimate goal is to work using org-ref with separate notes per each paper in my bibliography, which would be found using helm-bibtex. However, it turns out I have encountered a more basic problem already using helm-bibtex. I wanted to create an example note for one of my documents. I run 'M-x helm-bibtex', it loads the bibliography file and displays the entries. None of them show as having a PDF, but that's, I guess, to be expected, since I'm using Mendeley (and when citing from org-ref can find the PDFs without any problems). I choose an entry and select 'edit notes'. What I'm getting is:

``` elisp
helm-execute-selection-action-1: Symbol’s function definition is void: helm-bibtex-edit-notes
```

The following is in my .emacs:
``` elisp
(setq

 bibtex-completion-notes-path "/home/leszek/Dropbox/TeX-inne/org/"

 bibtex-completion-bibliography "/home/leszek/Documents/library.bib"

 bibtex-completion-pdf-field "file"

 bibtex-completion-notes-template-multiple-files

 (concat
  "#+TITLE: ${title}\n"
  "#+ROAM_KEY: cite:${=key=}\n"
  "* TODO Notes\n"
  ":PROPERTIES:\n"
  ":Custom_ID: ${=key=}\n"
  ":NOTER_DOCUMENT: %(orb-process-file-field \"${=key=}\")\n"
  ":AUTHOR: ${author-abbrev}\n"
  ":JOURNAL: ${journaltitle}\n"
  ":DATE: ${date}\n"
  ":YEAR: ${year}\n"
  ":DOI: ${doi}\n"
  ":URL: ${url}\n"
  ":END:\n\n"
  )

 )
```

Could you suggest any hint as to what I'm doing wrong? Thanks in advance!

**Comment by tmalsburg** [comment]
Mendeley should work and your config looks okay at first glance.  Could you please given an example .bib-entry?  I'd like to see what's in the `file` field.

Re `helm-bibtex-edit-notes` not sure what's going on because this function is defined in the package.  I suspect that this is interference from org-ref or org-roam which modify helm-bibtex for their purposes.  Could you try it with an unmodified helm-bibtex (i.e. without org-roam, org-ref installed).

**Comment by Elwro** [comment]
Thank you very much! Indeed, when I removed org-ref and org-roam, and stripped my .emacs from their remnants, things started working properly! PDFs are seen on the list and visited correctly. Notes are created (and seen on the list). However, something must be wrong with my note template setup since some of the fields are not populated. Example:

@article{skyrms1997structure,
abstract = {SKIPPED},
author = {Skyrms, Brian},
file = {:home/leszek/.local/share/data/Mendeley Ltd./Mendeley Desktop/Downloaded/Skyrms - 1997 - The structure of radical probabilism.pdf:pdf},
journal = {Erkenntnis},
pages = {285--297},
title = {{The structure of radical probabilism}},
volume = {45},
year = {1997}
}

gives the following note:

#+TITLE: The structure of radical probabilism
#+ROAM_KEY: cite:skyrms1997structure
* TODO Notes
:PROPERTIES:
:Custom_ID: skyrms1997structure
:NOTER_DOCUMENT: %(orb-process-file-field "skyrms1997structure")
:AUTHOR: 
:JOURNAL: 
:DATE: 
:YEAR: 1997
:DOI: 
:URL: 
:END:

I see I must've used a note template created for someone using org-roam-bibtex (which I'm not using); I guess I should write one myself from scratch. However, could you give me some hint as to how to make it use the values of the keys of the bibtex entries (like 'journal')? 

I of course fully understand if you don't have time for things like this... Again, thank you very much for the answer! I've been using Emacs+AucTeX for many years, but I'm only now taking my first steps exploring the newer options, including helm-bibtex... I guess I will first take some time familiarizing myself with it before I install org-ref, org-noter, org-roam, and try to make them all talk to each other :-)

**Comment by Elwro** [comment]
Well, I did my reading. Inside `bibtex-completion.el` I found the definition of `bibtex-completion-notes-template-multiple-files`, and it is clearly stated there that 

> '${field-name}' can be used to insert the value
> of a BibTeX field into the template."

So, eh, instead of `${author-abbrev}` and `${journaltitle}` I should've just used `${author}` and `${journal}`. Duh. Works perfectly. Thank you again for your time!

**Comment by tmalsburg** [comment]
Glad you could figure it out. :)
