### ISSUE TITLE
What's the differences between helm-bibtex and company-reftex?

### ISSUE THREAD

**Issue by hongyi-zhao** [tmalsburg/helm-bibtex#378]
I noticed the [company-reftex](https://github.com/TheBB/company-reftex) package which is a `RefTeX` backends for company-mode. But it seems that `helm-bibtex` also has the similar feature.

What's the differences between `helm-bibtex` and `company-reftex` in this sense?

Regards,
HY

**Comment by tmalsburg** [comment]
I didn't know company-reftex but from a quick look at its GitHub page, it seems that it's more narrow in scope. Specifically, company-reftex seems to focus on completing BibTeX keys when authoring LaTeX documents, but helm-bibtex in addition has some features that you'd expect in a more general bibliography manager, such as note-taking, access to PDFs, searching in online data bases and so on.  helm-bibtex is also integrated with org-roam and org-ref.  What's better for you depends on your use case.

**Comment by hongyi-zhao** [comment]
I'm currently mainly use auctex. I'm not sure whether it can co-operate with it.

**Comment by tmalsburg** [comment]
What do you mean by "it"?  helm-bibtex or company-reftex?  helm-bibtex should work.  Just try it.

**Comment by hongyi-zhao** [comment]
I mean using helm-bibtex with auctex.

**Comment by tmalsburg** [comment]
As I said, it should work, just try it. Setting up helm-bibtex, should take <3min.

**Comment by hongyi-zhao** [comment]
Thank you. I'll give it a try.
