### ISSUE TITLE
Syntax of JabRef comment field is markdown format

### ISSUE THREAD

**Issue by hwiorn** [tmalsburg/helm-bibtex#380]
[JabRef](jabref.org) comment field is Markdown format default. It supports limited latex, but LaTeX formatter seems not supported well like Zotero. So I'm trying to convert this comment field to org-mode using helm-bibtex and pandoc.

```bibtex
@Book{sonkeZetelkasten,
  author   = {Sönke Ahrens},
  title    = {How to Take Smart Notes: One Simple Technique to Boost Writing, Learning and Thinking – for Students, Academics and Nonfiction Book Writers},
  isbn     = {978-1542866507},
  comment = {# Annotation
## Test1
Hello world

this is test
## Test 2
Test strings
strings text

Ha
### test 2-1
## Test 3},
}

```

But `helm-bibtex` can't handle multi-line syntax. All spaces of comment field have gone after `bibtex-completion-get-entry` called.

```lisp
(bibtex-completion-get-value  "comment" (bibtex-completion-get-entry "syonkeJetelkaseuten") "")
```
> "# Annotation ## Test1 Hello world this is test ## Test 2 Test strings strings text Ha ### test 2-1 ## Test 3"

Is there an option to handle value without `s-collapse-whitepase`?

**Comment by tmalsburg** [comment]
If you'd just like to write a script for converting your entries, you may be better off using the package for parsing  directly.  [Parsebib](https://github.com/joostkremers/parsebib) gives you the raw BibTeX entries without any preprocessing.

**Comment by hwiorn** [comment]
Thank you for your reply. I'll check both Parsebib and bibtex-completion-candidates with assoc-string.
