### ISSUE TITLE
`ivy-bibtex` under new org-mode without option for inserting citation

### ISSUE THREAD

**Issue by ebouna** [tmalsburg/helm-bibtex#387]
Under the bleeding edge version of Org-mode (installed on Ubuntu), when calling ivy-bibtex (via `M-x ivy-bibtex`) and then the options (via `M-o`), ivy-bibtex, seems to lack the sub-option `insert citation`. All other sub-options appear in the usual way. 
Perhaps you can give me some advice on how to make `insert citation` available. 
Note that even with `(setq ivy-bibtex-default-action 'ivy-bibtex-insert-citation)`, I cannot insert a proper citation using ivy-bibtex. This creates either a broken (red) citation or inserts the mere citekey. 

I'm using the following configuration ofr bibtex-completion:

``` elisp
;;========Bibtex-completion config=================
(use-package org-cite
  :load-path "~/elisp/org-mode/lisp"
  :config
  (require 'oc-csl))
  
(use-package citeproc)
  
;;===minimal config===
(setq bibtex-completion-bibliography '("~/elisp/org-ref-cite/org-ref-cite.bib"))

;;===format of citations===
(setq bibtex-completion-format-citation-functions
  '((org-mode      . bibtex-completion-format-citation-org-cite)
    (latex-mode    . bibtex-completion-format-citation-cite)
    (markdown-mode . bibtex-completion-format-citation-pandoc-citeproc)
    (default       . bibtex-completion-format-citation-default)))


;;===Helm config=== cf. http://tuhdo.github.io/helm-intro.html
(require 'helm-config)
(helm-mode 1)


;;===Ivy config: Activating ivy-mode===
(ivy-mode 1)

(setq ivy-use-virtual-buffers t)
(setq ivy-count-format "(%d/%d) ")
```

**Comment by tmalsburg** [comment]
> Not sure why it's not displayed, though.

I experimented a bit and it appears that ivy is just showing the last 8 actions in the list. Anything before that is cut off (in this case "Open PDF file (if present)", "Open URL or DOI in browser", "Insert citation").  I think this is an ivy problem.

**Comment by ebouna** [comment]
Many thanks for your help, @tmalsburg!
