### ISSUE TITLE
support note = "\url{FOO}"

### ISSUE THREAD

**Issue by malb** [tmalsburg/helm-bibtex#39]
It would be nice if helm-bibtex would also understand entries which store their URL in the note field as "\url{FOO}". crypto.bib from http://cryptobib.di.ens.fr/ does that, for example.

**Comment by tmalsburg** [comment]
Hi, I agree that it would be good to be able to open those URLs, too.  However, as far as I know it's fairly standard to store URLs in BibTeX `url` field.  Also, the note field may contain other URLs apart from the URL of the journal article and that may lead to confusion. I think it makes more sense to direct this issue to the maintainers of the crypto bibliography.  It would be fairly easy for them to move the URLs to the `url` field.

**Comment by malb** [comment]
Fair enough. I'll ask the maintainers.

**Comment by tmalsburg** [comment]
Great, thank you.
