### ISSUE TITLE
Fallback options not showing

### ISSUE THREAD

**Issue by DiogoFerrari** [tmalsburg/helm-bibtex#397]
I have a large list of actions on ivy-set-actions (+15), but only 12 are visible upon using alt+o when selecting the reference using ivy-bibtex. Is it possible to show all options and split the columns into two?

PS: In helm it works fine, but I prefer to use ivy.

**Comment by tmalsburg** [comment]
I think this may be a question for the ivy developers because there is no code in ivy-bibtex that limits the number of actions to 12.
