### ISSUE TITLE
Can not find find pdf for bib entries with Polish characters in bib keys

### ISSUE THREAD

**Issue by nujabse** [tmalsburg/helm-bibtex#398]
When I try to open one bib entry with pdf attached, I get a warning: `No PDF(s) found for this entry: woińska13_magnet_inter_ensem_cubic_nanop`. However, the other bib entries can open the corresponding pdf files just fine. I guess maybe it is the Polish characters in this special bib key that is causing the trouble?

The bib entry is:
```
@article{woińska13_magnet_inter_ensem_cubic_nanop,
  author          = {Magdalena Woińska and Jacek Szczytko and Andrzej Majhofer
                  and Jacek Gosk and Konrad Dziatkowski and Andrzej Twardowski},
  title           = {Magnetic Interactions in an Ensemble of Cubic
                  Nanoparticles: a Monte Carlo Study},
  journal         = {Physical Review B},
  volume          = 88,
  number          = 14,
  pages           = 144421,
  year            = 2013,
  doi             = {10.1103/physrevb.88.144421},
  url             = {https://doi.org/10.1103/physrevb.88.144421},
}
```
The corresponding pdf file name is: `woińska13_magnet_inter_ensem_cubic_nanop.pdf`
When I try to directly open the corresponding pdf file using `helm-bibtex`, it warns that that "No PDF(s) found for this entry". However, when I remove the `ń` special character both in the bib key and the attached pdf file, it can be opened without problem.

**Comment by tmalsburg** [comment]
I tried to replicate this but couldn't.  Works fine with the Polish character.  I suspect that your file name is using a different character encoding than the .bib file.  This way, file name and bib key look the same but are in fact different.

**Comment by nujabse** [comment]
Ah, I see, when I rename the pdf file name to copied bib key value manually using `mv` command, works without problem. Looks like a character encoding problem. Thank you for your kind help!
