### ISSUE TITLE
bibtex-completion-edit-notes fails if set as default action

### ISSUE THREAD

**Issue by issey173** [tmalsburg/helm-bibtex#400]
_Disclaimer: I am quite new to the whole emacs world. I might be missing something obvious, apologies for that_

I am trying to set the action "Edit notes" as the default. Following the instructions in the [official doc](https://github.com/tmalsburg/helm-bibtex#change-the-available-actions) I've done:

``` elisp
  (helm-delete-action-from-source "Edit notes" helm-source-bibtex)
  (helm-add-action-to-source "Edit notes" 'bibtex-completion-edit-notes helm-source-bibtex 0)
```
and then reload the config. These two lines are inside my `:config` within `use-package helm-bibtex`.

When I call `helm-bibtex` the default action is now "Edit notes" as it should be, but when I run it I get the following message:
_bibtex-completion-edit-notes: Wrong type argument: listp, "zhangVariationalReasoningQuestion2018"_

I've tried to go over the backtrace using debug-mode but I don't see any further info.
Funny thing is, if I try to set it back as action number 7 (f8), it won't work again. Only restarting the whole emacs server seems to put it back to normal.

Any help would be much appreciated! This is an amazing package and I'm just trying to optimize my workflow with it

I'm using:
- Doom emacs (emacs 27.2)
- emacs-daemon & emacsclient
- mac 12.0 monterey

**Comment by tmalsburg** [comment]
`bibtex-completion-edit-notes` is the "raw" version of the action that is not adapted to work with helm.  I think you need to use `helm-bibtex-edit-notes` instead.  Could you please try that and report back?  Thank you.

**Comment by issey173** [comment]
Thank you very much! It is indeed as you said. Substituting `bibtex-completion-edit-notes` by `helm-bibtex-edit-notes` made it work. Closing the issue!

**Comment by tmalsburg** [comment]
Great. Thanks for the update.
