### ISSUE TITLE
Is it possible to change the format of author name?

### ISSUE THREAD

**Issue by quarkquartet** [tmalsburg/helm-bibtex#404]
For example, for every configure code that I need the string `${author}`, use "First Last" instead of "Last, First". Is this possible?

**Comment by tmalsburg** [comment]
There is not way to configure this, but you can overwrite the function `bibtex-completion-apa-format-authors` with something that suits your needs.  The `apa` in this and other functions stands for the APA style guide by the American Psychological Association.  The original idea was that there would also be functions for other style guides but most people actually seem to be okay with the current format.
