### ISSUE TITLE
Changing default action breaks the new default action

### ISSUE THREAD

**Issue by joshbarrass** [tmalsburg/helm-bibtex#405]
I have tried following the steps in [this section](https://github.com/tmalsburg/helm-bibtex#change-the-available-actions) of the documentation to make inserting a citation the default action. I added the following to my config:

```
  (helm-delete-action-from-source "Insert citation" helm-source-bibtex)
  (helm-add-action-to-source "Insert citation" 'bibtex-completion-insert-citation helm-source-bibtex 0)
```

This does seem to change the default action, as I am prompted for the cite command etc., but breaks the action; rather than inserting the citation, I instead just get the error `s-join: Wrong type argument: sequencep, 115`

The issue persists even if I use the example exactly as given in the documentation, instead breaking the "Insert BibTeX key" action.

Without these lines in my config, the default action and both of these actions work as normal.

I am using version `20210725.1510` installed via melpa.

Any assistance I could get in fixing this would be greatly appreciated.

**Comment by tmalsburg** [comment]
Could you please try the following?:

``` elisp
  (helm-add-action-to-source "Insert citation" 'helm-bibtex-insert-citation helm-source-bibtex 0)
```

**Comment by tmalsburg** [comment]
Solves it for me, so closing.  But feel free to reopen if the problem persists.

**Comment by joshbarrass** [comment]
This also solves it for me :+1:
