### ISSUE TITLE
How to know which bib file is at point

### ISSUE THREAD

**Issue by AtomicNess123** [tmalsburg/helm-bibtex#406]
Suppose that I have set up a list of bibtex files like this:

```emacs-lisp
(setq bibtex-completion-bibliography
      '("/path/to/bibtex-file-1.bib"
        "/path/to/bibtex-file-2.bib"))
```

When doing helm-bibtex to search for an entry, are all entries of all files shown and how to know to which bibtex file that entry belong to? 

Thanks!

**Comment by tmalsburg** [comment]
Yes the entries form all files are shown in one list. I've also considered having separate helm sources for each file but that has some UI downsides.  I think the only way to find out from which file an entry comes is to select the action "Show entry" which shows the entry in its .bib file.  Not super great but tbh I need to know this so rarely that it's okay for me.  (My own system is to have three .bib files: One for preprints, one for my own publications, one for everything else.)  Hope this answers your question.
