### ISSUE TITLE
No Available actions on helm-bibtex

### ISSUE THREAD

**Issue by mynet1314** [tmalsburg/helm-bibtex#412]
Hi, I'm facing a problem with helm-bibtex:
    I could get a BibTex entries after I run `M-x helm-bibtex`, but it prompt "No Actions available" when I press `C-z`.
 
Screenshot:
<img width="1436" alt="Screen Shot 2022-10-19 at 14 56 44" src="https://user-images.githubusercontent.com/45286861/196618669-d78ddd3d-ad4e-404a-9f8e-bbd78916710d.png">

Thanks for any help.

**Comment by tmalsburg** [comment]
Please try `tab` instead of `C-z`.

**Comment by tmalsburg** [comment]
I couldn't try it with `C-z` because that key combination is used by my window manager.  However, when I rebind `helm-execute-persistent-action` to `TAB`, it works as expected. Could you please create a minimal reproducible example?

**Comment by mynet1314** [comment]
@tmalsburg Thanks for you reply.

My minimal configuration below:
```(require 'package)

(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("org" . "https://orgmode.org/elpa/")
                         ("elpa" . "https://elpa.gnu.org/packages/")))

(package-initialize)
(unless package-archive-contents
 (package-refresh-contents))

;; Initialize use-package on non-Linux platforms
(unless (package-installed-p 'use-package)
   (package-install 'use-package))

(require 'use-package)
(setq use-package-always-ensure t)


(use-package helm-bibtex
  :config
 (setq bibtex-completion-bibliography "/Users/hoo/Bib/hello.bib"
        bibtex-completion-pdf-field "File"
        bibtex-completion-additional-search-fields '(keywords))
  :bind
  ("C-c n B" . helm-bibtex))
```

**Comment by tmalsburg** [comment]
I get an error message when I run your code because (I think) use-package is not installed on my system. Is there an easy way to include it in your code? (Sorry, not time to investigate myself.)

**Comment by mynet1314** [comment]
@tmalsburg I think it might be some problems in environment. 

I've created a linux account for you on cloud to  investigate the problem:
```
ip: 120.24.62.193
username: helmbibtex
passwd: 1q2w3e
```

To see the problem:
1. run `emacs` command
2. `M-x helm-bibtex` 
3. press `TAB`

Could you please help me with that?

**Comment by tmalsburg** [comment]
`M-x helm-bibtex` throws an error:
```
Symbol’s function definition is void: helm-mode--in-file-completion-p
```
Could you please post a minimal config here on GitHub?  Thank you.

**Comment by tmalsburg** [comment]
I think helm is not correctly installed.

**Comment by boturon** [comment]
For me, it doesn't even open. It raises related errors on both Windows and Arch:

`helm-fuzzy-highlight-matches: Symbol’s function definition is void: helm-mode--in-file-completion-p`

and

`custom-initialize-reset: Symbol’s function definition is void: helm-mode--in-file-completion-p`

Possible tips:
- I use it alongside `org-roam` and `org-roam-bibtex`
- `helm-core` was recently updated

**Comment by tmalsburg** [comment]
See here #413 for a possible solution.

**Comment by mynet1314** [comment]
Thank you @tmalsburg @boturon, I'll try it, I will update the issue once I figure it out.

**Comment by mynet1314** [comment]
I just change to ivy-bibtex, and it just works.
