### ISSUE TITLE
Error custom-initialize-reset: Symbol’s function definition is void: helm-mode--in-file-completion-p

### ISSUE THREAD

**Issue by averter** [tmalsburg/helm-bibtex#413]
I use helm-bibtex mainly to visualize my references in combination with org-ref. Today I was not able to, because of the following error
`custom-initialize-reset: Symbol’s function definition is void: helm-mode--in-file-completion-p`.
I've used `toggle-debug-on-error` to try to obtain some more info, but it's not been easy as the debug buffer constantly disappeared (had to take a screenshot) 
![image](https://user-images.githubusercontent.com/16647523/196990921-5b8b2b55-900b-4ce6-874b-00760109ed9f.png)

All that is needed to reproduce is to call helm-bibtex, and I am using version 63c108a5efc130f037bc1c36cb3ee7d963567c12, emacs 27.1 on Linux Mint 21. Thank you in advance for any help.

**Comment by tmalsburg** [comment]
Someone else reported the same error, but it's not happening on my system.  We haven't changed anything recently that could explain this error.  I think the issue may perhaps be in helm?

**Comment by tmalsburg** [comment]
Please make sure that helm is correctly installed.

**Comment by averter** [comment]
@tmalsburg Thanks. It is working now, but I had to look at the package list and install "manually"  (by marking helm and helm-bibtex with "I" and then "x"). For some reason use-package is not doing what is supposed to do... Could it be because of my configuration? I am calling org-ref as follows
```` lisp
(use-package org-ref
  :ensure t :ensure helm :ensure ivy-bibtex :ensure helm-bibtex
  :bind (("\C-c«" . helm-bibtex)			     ; helm-bibtex
         ("\C-c )"  . org-ref-insert-link)
         ("\C-x c d" . doi-utils-add-bibtex-entry-from-doi)  ; find based on doi
         ("\C-x c n" . crossref-add-bibtex-entry))	     ; find based on name
   [other stuff]
   )
````
In any case, I'll close this issue.

**Comment by averter** [comment]
> > @tmalsburg Thanks. It is working now, but I had to look at the package list and install "manually" (by marking helm and helm-bibtex with "I" and then "x")
> 
> It also works for me whenever I reinstall it, but as soon as I restart emacs the error returns

I'm glad that you made this comment as when I restart indeed the error returned...something fishy is going on

**Comment by tmalsburg** [comment]
If it stops working after restarting, I strongly suspect that the root cause is not in this package. Seems more likely that it's in helm or in the package manager.

**Comment by averter** [comment]
@thierryvolpiatto could it be because the installation is via melpa instead of straight as suggested in helm's installation instructions? @boturon are you also installing via melpa, and can you also share your configuration so that we can try to reproduce the bug? thanks.

**Comment by thierryvolpiatto** [comment]
Averter ***@***.***> writes:

> @thierryvolpiatto could it be because the installation is via melpa
> instead of straight as suggested in helm's installation instructions?

No, it is because I use since recently helm-mode--in-file-completion-p
in helm-core and it is not yet required, I will fix this soon.  If you
start helm-mode in your config this should not happen.

-- 
Thierry
