### ISSUE TITLE
No available actions in ivy-bibtex

### ISSUE THREAD

**Issue by nilsleh** [tmalsburg/helm-bibtex#414]
This is pretty much the same issue as #412 but instead with ivy-bibtex. I can run `M-x ivy-bibtex` and see all available entries but if I press `TAB` it just autocomples the rest of the search prompt. If I press `TAB` another time it opens the pdf automatically in the browser, so I do not see any actions available. I don't know what else in my config would mess up the `TAB` keybinding. I don't know what the ivy-bibtex function is that I could rebind to a different key, because maybe then I can obtain actions that way? Thank you for any help.

**Comment by tmalsburg** [comment]
We haven't changed anything in ivy-bibtex in recent months.  So the cause for this issue must lie somewhere else.  Do you have org-ref or org-roam-bibtex installed?  In the past, these packages sometimes modified the behavior of helm-/ivy-bibtex.  There may also have been a change in ivy-bibtex itself.

> . If I press TAB another time it opens the pdf automatically in the browser, so I do not see any actions available.

I have to confess that I don't know for sure what the desired behavior is.  (I don't use ivy-bibtex myself and the code was contributed by someone else.)  However, I just checked the Ivy documentation and the behavior that you describe seems to be consistent with it.  See here: https://oremacs.com/swiper/

**Comment by tmalsburg** [comment]
Re #412, note that I'm not able to replicate that issue and I suspect that it's a problem with those users' configs, not a problem in helm-bibtex.

**Comment by nilsleh** [comment]
Thanks for your response, yes I also suspect it is something in my config because I am using ivy. I had not thought about going to the Ivy documentation that you pointed out, but I found there that there is a function `ivy-dispatching-done` which I remap to a different keybinding and then I can actually get to see the ivy-bibtex actions when calling that keybinding :) Thank you.

I am now running into another unexpected issue, because my hope was to use the `ivy-bibtex-add-pdf-to-library` action to save pdfs based on the citations I can search with ivy-bibtex. But there I encounter two unexpected things:
1. I have to manually specify a file or url in the prompt. I thought it would retrieve the necessary information from the citation itself  to make it faster and more convenient.
2. If I go with the url option and specify a url link, it retrieves a html document and not a pdf that can be opened

I don't know what I am doing wrong or if that is not the intention of that action, but is there a recommended way that would let me download the pdf to the `bibtex-completion-library-path` based on the bibtex citation. 

As a reference, the workflow I am hoping to achieve is:
1. save citations I encounter online to zotero
2. export the zotero collection to a .bib file which can be found by ivy-bibtex
3. use ivy-bibtex to search available citations, download pdf so I can view and take some notes on the article within emacs

So currently, only struggling with the download pdf step to make it convenient and fast.

**Comment by tmalsburg** [comment]
We currently have no code for downloading PDFs from online sources. You can create a separate feature request but this sounds like a difficult problem and I won't have the time to work on it.  (There are many sources that the code would have to check to find the PDF and then you might have to authenticate with the journal using university credentials or similar.  And so on.  Not trivial at all.  I personally search PDFs manually and directly save them to `bibtex-completion-library-path`.  Regarding `ivy-bibtex-add-pdf-to-library`, I agree that it's not terribly useful in the current form.  I think a user proposed it but personally I don't use it.  Candidate for removal perhaps.
