### ISSUE TITLE
unhelpful error if helm-bibtex-library-path is not set

### ISSUE THREAD

**Issue by chrisboo** [tmalsburg/helm-bibtex#42]
Hello,
I stumbled over an odd error in helm-bibtex today. If the variable `helm-bibtex-library-path` is not set, which is the default, one gets the error 

    f-absolute?: Wrong type argument: stringp, nil

when pressing `RET` over an entry. Obviously, this is not very telling (to me at least). Just setting the variable to `"~/"` fixes the issue, even though there are no pdf's to be found under that path. I think a good default value would be the folder of the bib file?
Cheers,
Christian

**Comment by tmalsburg** [comment]
Good point, thank you!

**Comment by tmalsburg** [comment]
This is fixed in recent versions of helm-bibtex.  Now you get "No PDF(s) found."
