### ISSUE TITLE
Symbol’s function definition is void: org-cite-register-processor

### ISSUE THREAD

**Issue by vsydorov** [tmalsburg/helm-bibtex#422]
helm-bibtex.el contains the call to org-cite-register-processor, which as been added with the 8a1249d commit.

org-cite is deprecated and is no longer the part of org-ref library. I suggest removing this call, since otherwise the helm-bibtex breaks with latest org-ref version.

**Comment by averter** [comment]
Similar to https://github.com/tmalsburg/helm-bibtex/issues/418 ?
This is a super annoying issue. Thumbs up to remove it.

**Comment by tmalsburg** [comment]
I don't understand this issue.  org-cite is part of org to my knowledge.  Helm-bibtex should not have any dependencies to org-ref.  If helm-bibtex breaks with org-ref installed, that's likely a problem in org-ref, not in helm-bibtex.  Please clarify.

**Comment by tmalsburg** [comment]
@averter, you write
>  This is a super annoying issue. Thumbs up to remove it.

But my understanding is that your issue (#418) was caused by an outdated version of org mode on your system.  Why should we remove support for org-cite in helm-bibtex?

**Comment by vsydorov** [comment]
Thank you, @tmalsburg, you have been very helpful. This has indeed been a problem of outdated org mode version and insufficient research on my part. Can I close the issue?

**Comment by averter** [comment]
I am experiencing several issues with the latest org-mode version, and have decided to revert back to 9.3. This is just my opinion, but, is there a way of having helm-bibtex not being so tightly integrated with org-mode, as this creates many dependency problems? Thanks

**Comment by tmalsburg** [comment]
@vsydorov thanks for the update. It's annoying that Emacs contains an old version of org mode and it's important to make sure that you're using the up-to-date version not Emacs's version. I've run into this issue as well.
