### ISSUE TITLE
Invalid image type 'svg'

### ISSUE THREAD

**Issue by rhaynes74** [tmalsburg/helm-bibtex#426]
Hi folks, I had to start with a fresh hard-drive, so I had to reinstall emacs etc (I am using spacemacs and emacs 28.2 from homebrew).  

I can access my global .bib file with helm-bibtex, if I choose a paper and do C-z I get the actions menu, if I press enter on the first item (open pdf) then nothing happens except a message in the status which says: "Invalid image type 'svg'" 

Suggestions?

**Comment by tmalsburg** [comment]
Without further information it's impossible for me to tell what's going on.  A minimal reproducible example would be helpful.  Have you googled the error message?  This turns up some pages which may be relevant.

**Comment by rhaynes74** [comment]
Hi - thanks for the reply.  This may or may not be related to a known emacs 28.2 bug related to svg.  I reinstalled emacs/spacemacs decided to cleanup my python installs and this fixed the issue.

Sincerely,

Dr. Ronald D. Haynes
Professor, Department of Mathematics and Statistics
Chair, MSc and Phd Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by tmalsburg** [comment]
Glad to hear that you could fix it.
