### ISSUE TITLE
 Symbol’s value as variable is void: browse-url-mosaic-program

### ISSUE THREAD

**Issue by eeenilsson** [tmalsburg/helm-bibtex#427]
When loading helm-bibtex after emacs update I get this error.

It seems Emacs removed Mosaic-support from it's sources: https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=3e39aa6cfa6822b535d597b3e59abfea38610a48

getting the same error with (require 'helm-net)

removing  (require 'helm-net) from helm-bibtex.el solved the error, but not sure if helm-net is needed (is it now included in helm?)

**Comment by tmalsburg** [comment]
I have an up-to-date development version of Emacs and don't get this error.  I think you may be using an outdated version of helm-net.el.  My version doesn't reference mosaic. Could you please check?

**Comment by eeenilsson** [comment]
Im using Emacs-ESS for windows. That might be the problem. Emacs version 28.1

**Comment by eeenilsson** [comment]
Updating emacs-helm solved this problem.

**Comment by tmalsburg** [comment]
Great, thanks for the update.
