### ISSUE TITLE
Inquiry about Automatic Updating of BibTeX Files from Online Databases in Helm-Bibtex.

### ISSUE THREAD

**Issue by hongyi-zhao** [tmalsburg/helm-bibtex#428]
Dear Developer,

I am writing to inquire about whether Helm-Bibtex has a feature that allows for automatic updating of BibTeX files from online databases. Specifically, I would like to know if there is a way to automate the process of fetching new citations from online databases and updating my BibTeX file accordingly.

If such a feature is available in Helm-Bibtex, could you kindly provide me with some guidance on how to use it for automatic updating?

Thank you in advance for your time and assistance.

Best regards,
Zhao

**Comment by tmalsburg** [comment]
Hi, helm-bibtex doesn't have such a feature.  The primary focus of helm-bibtex is to give users quick access to bibliographies produced with other software.
