### ISSUE TITLE
"Loading bibliography ..." information when "helm-bibtex-library-path" is set

### ISSUE THREAD

**Issue by tommyjiang** [tmalsburg/helm-bibtex#43]
Hi,

Thanks for this powerful extension of Emacs first. I would like to report an issue on my Mac as described in the title. 

I installed helm-bibtex via melpa with the newest version. My Emacs is Emacs 24.4 on Mac 10.10.2.

At first, I only have the following setting in my init.el:

`(setq helm-bibtex-bibliography '("~/Documents/Work/Papers/MPC.bib"))`

helm-bibtex works fine with this setting. However, if I add the following setting in init.el:

`(setq helm-bibtex-library-path '("~/Documents/Work/Papers/MPC"))`

Then when I ran `helm-bibtex` in Emacs, it will display "Loading bibliography ..." message in the echo area, which is similar to [Issue #38](https://github.com/tmalsburg/helm-bibtex/issues/38).

So now I would just try the management function with helm-bibtex. Could you please help me with this? Thanks in advance.

**Comment by tommyjiang** [comment]
Here is the result when I execute `helm-bibtex-candidates` in the \*scratch\* buffer:

```
Debugger entered--Lisp error: (wrong-type-argument stringp ("~/Documents/Work/Papers/MPC"))
  file-name-absolute-p(("~/Documents/Work/Papers/PDF"))
  f-absolute\?(("~/Documents/Work/Papers/PDF"))
  f-relative\?(("~/Documents/Work/Papers/PDF"))
  f-join(("~/Documents/Work/Papers/PDF") "MPLFC.pdf")
  helm-bibtex-prepare-entry((("year" . "2014") ("number" . "6") ("volumes" . "30") ("pages" . "\"1-9\"") ("journal" . "\"IEEE Transactions on Power Systems\"") ("title" . "\"Model Predictive Load Frequency Control\"") ("author" . "\"A. M. Ersdal and L. Imsland and K. Uhlen\"") ("=type=" . "article") ("=key=" . "MPLFC")) ("author" "title" "year" "crossref"))
  helm-bibtex-prepare-entries(((("year" . "2014") ("number" . "6") ("volumes" . "30") ("pages" . "\"1-9\"") ("journal" . "\"IEEE Transactions on Power Systems\"") ("title" . "\"Model Predictive Load Frequency Control\"") ("author" . "\"A. M. Ersdal and L. Imsland and K. Uhlen\"") ("=type=" . "article") ("=key=" . "MPLFC"))))
  helm-bibtex-candidates()
  eval((helm-bibtex-candidates) nil)
  eval-last-sexp-1(nil)
  eval-last-sexp(nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

**Comment by tommyjiang** [comment]
I think I have found the problem. I should use the following setting:

```
(setq helm-bibtex-library-path "~/Documents/Work/Papers/MPC")
```

**Comment by tmalsburg** [comment]
Glad to see that you could fix the problem.  I should probably add some instructions for debugging to the main page.

**Comment by tommyjiang** [comment]
Thanks @tmalsburg . My Emacs Lisp level is very poor, I just guess this from the error message that the parameter is not a “string”.
