### ISSUE TITLE
helm-bibtex-follow doesn't fail properly for non-existent keys

### ISSUE THREAD

**Issue by mpedramfar** [tmalsburg/helm-bibtex#440]
Example: 
Run `helm-bibtex-follow` on `[cite:@something]` in org-mode.
The result is that a list of actions are still shown even-though it doesn't make sense to take any action on it. It also raises the warning: 
`Bibtex-completion couldn't find entry with key "something".`

A possible solution: replace the current definition of `helm-bibtex-follow` with
```emacs-lisp
(defun helm-bibtex-follow (&optional citation args)
  (interactive)
  (let ((candidates (bibtex-completion-candidates))
        (key (if citation
                 (org-element-property :key citation)
               (bibtex-completion-key-at-point))))
    (unless (cl-find-if (lambda (cand)
                          (member (cons "=key=" key)
                                  (cdr cand)))
                        candidates)
      (user-error "Bibtex-completion couldn't find entry with key \"%s\"." key))
    (let ((item-info
           (format "%s\t\t%s"
                   (bibtex-completion-apa-get-value
                    "title" (bibtex-completion-get-entry key))
                   (bibtex-completion-apa-get-value
                    "author" (bibtex-completion-get-entry key)))))
      (helm :sources
            (helm-build-sync-source item-info
              :candidates helm-bibtex-follow-actions-alist
              :action (lambda (x) (funcall x (list key))))
            :full-frame helm-bibtex-follow-full-frame
            :buffer "*helm bibtex follow*"))))

```

**Comment by tmalsburg** [comment]
> The result is that a list of actions are still shown even-though it doesn't make sense to take any action on it.

Why do you think it doesn't make sense to present a list of possible actions?

**Comment by mpedramfar** [comment]
The default list of actions of `helm-bibtex-follow` are: 
- `bibtex-completion-open-pdf`
- `bibtex-completion-open-url-or-doi`
- `bibtex-completion-edit-notes`
- `bibtex-completion-show-entry`
- `bibtex-completion-add-pdf-to-library`

None of these make sense when there is no entry to take the action on.

**Comment by tmalsburg** [comment]
Sorry, I don't understand.  If you `helm-bibtex-follow` on `[cite:@something]`, then the entry on which these actions can be executed is `something`.

**Comment by mpedramfar** [comment]
I think I wasn't clear enough. I mean a setting where there is no entry with the key `something`. Here the word `something` is not a placeholder for a real key.

**Comment by tmalsburg** [comment]
Ah, I see.  I overlooked the info in the title, sorry.

Do I understand correctly that your code generates an error when the key doesn't exist?  If yes, that makes sense of course.  A PR would be welcome.

**Comment by mpedramfar** [comment]
Perfect. I made a pull request.

**Comment by tmalsburg** [comment]
Merged, thank you!
