### ISSUE TITLE
Unicode Support

### ISSUE THREAD

**Issue by malb** [tmalsburg/helm-bibtex#444]
Hi there,

I made a series of changes to `bibtex-completion` and `helm-bibtex` and this ticket is to check if you'd be interested in me doing a PR.

1. `parsebib` has unicode support built in, but it's not enabled. We could (optionally or unconditionally) enable it in `bibtex-completion.el`:
    ```elisp 
   collect (let* ((entry (parsebib-read-entry entry-type (point) ht-strings nil t))
    ```
2. This will cause some problems because `parsebib` then also propertizes the outputs (italics et al), so we could `flet` `parsebib--convert-tex-italics` and friends to not do that (or we remove the properties again)
 
3. Helm has diacritics support, which can be enabled to passing `:diacritics t` when building the source in `helm-bibtex.el`. This could be enabled conditionally.

This together seems to work well: I can search for e.g. Damien Stehlé's papers by typing "Stehle".

**Comment by tmalsburg** [comment]
Hi Martin, I've been using Unicode in my bibliography for many years and it's working without any issues.  Could you please explain what exactly is missing wrt Unicode?

Point 2: I don't understand the point about italics.  Are there titles that include italics? And is it necessary to display them in helm-bibtex?  I just checked and found zero instances of italics in my bibliography.  An example would be useful.

Re point 3: There is a defcustom for diacritics in helm (`helm-mode-ignore-diacritics`).  Is it a good idea to override the user's own setting?

**Comment by malb** [comment]
hey :) Yes, unicode in the bib file works well, but if the bib file has e.g. `\'e` or `{\e}` this doesn't get converted to `é` and this makes it harder to search. 

Re 2: parsebib chooses to translate `\emph{foo}` into a propertised string with italics if you enable the "parse latex to unicode" flag. This wouldn't be my choice, just something to keep in mind should we enable this flag.

Re 3: Uh, you're right, this isn't needed, sorry for that

So my question boils down to: do we want to add a defcusom `bibtex-completion-parse-latex-to-unicode` ?
