### ISSUE TITLE
New `parsebib.el` parser

### ISSUE THREAD

**Issue by joostkremers** [tmalsburg/helm-bibtex#452]
Hi @tmalsburg , `bibtex-completion.el` depends on `parsebib.el`, so I wanted to give you a heads-up: I've ripped out the pretty hairy regexp-based parser code and replaced it with a simple recursive descent parser. The new parser works well, and the tests included in `parsebib` all pass, but with this kind of thing there's always a risk of regressions, of course.

I haven't merged the new code yet, but once I do, you may get bug reports from users that are ultimately caused by `parsebib.el`. If that happens, just send them to me, or key me in in the discussion.

Some functions have also changed signature, especially `parsebib-read-entry`, which is used in `bibtex-completion.el`. You may want to consider using `parsebib-parse-bib-buffer` or `parsebib-collect-bib-entries` instead, which will get you all entries in a single function call.

If you have a `.bib` file that you would like to test the new code with before I do the merge, I'd be happy to do that, or if you prefer, you can check out the code [here](https://github.com/joostkremers/parsebib/tree/wip/rdp).

**Comment by chuxubank** [comment]
I just find a bug that `bibtex-completion-parse-strings` runs in infinite loop when use with new `parsebib` package.
I pin the `parsebib` to the latest release version (4.7) and it still works well.

So if we want fix it, we should do the change on `bibtex-completion` side, right?

**Comment by joostkremers** [comment]
> So if we want fix it, we should do the change on `bibtex-completion` side, right?

Depends. `bibtex-completion` needs an update in order to be compatible with the new `parsebib.el`. I submitted a PR, but it looks like it hasn't been merged yet. Keeping `parsebib` pinned on 4.7 is the best solution for now. I'm sure @tmalsburg will update `bibtex-completion` soon.

**Comment by tmalsburg** [comment]
Just merged the PR.  Thank you Joost!!

**Comment by lnguyen4** [comment]
Hi, I m having the issue that when I invoke `helm-bibtex` , it hangs and the mini-buffer says "Parsing bibliography file /home/directorty/myfile.bib". 

I got this issue last night and came here to notice there was an update on the dependency `parsebib` pacakge. So, I then downgraded the parsebib and the issue was gone. 

However, today I just updated the helm-bibtex momentarily ago, along with upgrading the parsebib package. But now the hanging issue appears again. It looks like it is looping or something and I had to invoke Ctrl-g to quit it. So, I decided to try again by downgrading the parsebib and keeping the updated helm-bibtex but the error showed up like `ignore-member-case: wrong type argument,...`.

I can provide further info but anything I can try? Thanks for helping.

**Comment by joostkremers** [comment]
I don't know about helm (I don't use it), but if `parsebib` is involved (which is definitely possible, even likely, I'd say), then I'd need to look at the `.bib` entry that causes the hang. If you're unable to determine that and are willing to share your `.bib` file or files, feel free to send them to my by e-mail. (You'll find my e-mail address on my profile page).

**Comment by gongzhitaao** [comment]
I'm having the same problem.

I reproduce in the following way:

1. Start emacs with necessary components only:

  ```sh
  emacs -Q \
    -l ~/.cache/emacs/straight/build/s/s.elc \
    -l ~/.cache/emacs/straight/build/dash/dash.elc \
    -l ~/.cache/emacs/straight/build/f/f.elc \
    -l ~/.cache/emacs/straight/build/biblio-core/biblio-core.elc \
    -L ~/.cache/emacs/straight/build/biblio/ \
    -l ~/.cache/emacs/straight/build/biblio/biblio.elc \
    -l ~/.cache/emacs/straight/build/parsebib/parsebib.elc \
    -L ~/.cache/emacs/straight/build/org/ \
    -l ~/.cache/emacs/straight/build/bibtex-completion/bibtex-completion.el \
    -L ~/.cache/emacs/straight/build/helm/ \
    -L ~/.cache/emacs/straight/build/helm-core/ \
    -L ~/.cache/emacs/straight/build/async/ \
    -l ~/.cache/emacs/straight/build/helm-bibtex/helm-bibtex.elc
  ```
2. Then `(setq bibtex-completion-bibliography "~/ref.bib")`
3. Have the following content in `"~/ref.bib"`

```bibtex
@Comment @Article{l2024-hire,
@Comment   author          = {{L}, Yashas Samaga B and {Yerram}, Varun and {You}, Chong and {Bhojanapalli}, Srinadh and {Kumar}, Sanjiv and {Jain},
@Comment                      Prateek and {Netrapalli}, Praneeth},
@Comment   title           = {{HiRE: High Recall Approximate Top-$k$ Estimation for Efficient Llm Inference}},
@Comment   journal         = {arXiv e-prints},
@Comment   year            = 2024,
@Comment   eid             = {arXiv:2402.09360},
@Comment   month           = feb,
@Comment   pages           = {arXiv:2402.09360},
@Comment   doi             = {10.48550/arXiv.2402.09360},
@Comment   eprint          = {2402.09360},
@Comment   primaryclass    = {cs.LG},
@Comment   archiveprefix   = {arXiv},
@Comment   timestamp       = {2024-11-14T11:08:04-0500}
@Comment }
```

4. `M-x helm-bibtex`, it shows "Parsing bibliography file ~/ref.bib ..."

**Comment by mbarton98** [comment]
I'm also having the same issue. I had pinned parsebib to 4.7, but this bibtex-completion update forced parsebib back to 6. I don't use helm, but org-ref has these as dependences. If you need help testing let me know...running Emacs on macos compiled from the master branch today.

**Comment by lnguyen4** [comment]
1. Hi, I tried my best to troubleshoot and here is my attempt. The hanging still happens with the `example.bib` containing only entry like this:

```
@article{shirani-mehr_disentangling_2018,
	title = {Disentangling {Bias} and {Variance} in {Election} {Polls}},
	volume = 113,
	issn = {0162-1459, 1537-274X},
	url = {https://www.tandfonline.com/doi/full/10.1080/01621459.2018.1448823},
	doi = {10.1080/01621459.2018.1448823},
	language = {en},
	number = 522,
	urldate = {2024-11-04},
	journal = {Journal of the American Statistical Association},
	author = {Shirani-Mehr, Houshmand and Rothschild, David and Goel, Sharad and Gelman, Andrew},
	month = apr,
	year = 2018,
	pages = {607--614},
}
```

1. Create the `example.bib` file above in the current home directory. 
2. Run `emacs -Q` on console.
3. On scratch buffer, copy this
```
(require 'package)
(setq package-load-list
      '((wfnames t)
	(async t)
	(helm-core t)
	(helm t)
	(biblio-core t)
	(biblio t)
	(f t)
	(dash t)
	(s t)
	(parsebib t)
	(bibtex-completion t)
	(helm-bibtex t)))
(package-initialize)

(setq bibtex-completion-bibliography "~/example.bib")
```
4. Run `M-x helm-bibtex`.
5. And the minibuffer hangs with `Parsing bibliography file ~/example.bib`

My emacs version is  `GNU Emacs 29.4 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.43, cairo version 1.18.2)`. Thanks.

**Comment by joostkremers** [comment]
Well, the problem is not with `parsebib` directly, because all of the sample `.bib` files I've received parse just fine on their own or when I open them in Ebib. I'll have to try and install `bibtex-completion` and see if I can replicate the problem.

**Comment by joostkremers** [comment]
I found the cause of the problem and created a PR to fix it. `bibtex-completion` uses the function `parsebib-find-next-item` to find the next BibTeX item after point, but it does not always read the item found. Previously, `parsebib-find-next-item` would position point right after the `@` sign that starts an entry, so this wasn't an issue. In the new `parsebib` version, `parsebib-find-next-item` puts point at the start of the line, i.e., *before* the `@` sign. As a result, if the item isn't read, the next call to `parsebib-find-next-item` finds the exact same item again. 

I hope @tmalsburg can merge this PR soon, and I sincerely hope I didn't overlook anything else...

**Comment by lnguyen4** [comment]
> I found the cause of the problem and created a PR to fix it. `bibtex-completion` uses the function `parsebib-find-next-item` to find the next BibTeX item after point, but it does not always read the item found. Previously, `parsebib-find-next-item` would position point right after the `@` sign that starts an entry, so this wasn't an issue. In the new `parsebib` version, `parsebib-find-next-item` puts point at the start of the line, i.e., _before_ the `@` sign. As a result, if the item isn't read, the next call to `parsebib-find-next-item` finds the exact same item again.
> 
> I hope @tmalsburg can merge this PR soon, and I sincerely hope I didn't overlook anything else...

I downloaded your PR and rename the original installed file to `bibtex-completion-backup.el`. With my minimal example above, I can confirm hanging no longer happens. However, when I tried to open the url link or open the pdf, by first hiting `TAB` and then select the first or second option, it has error saying : `parsebib--char: [Parsebib error]: "Expected [@], got 't' at position 2,8" `.

**Comment by joostkremers** [comment]
> However, when I tried to open the url link or open the pdf, by first hiting `TAB` and then select the first or second option, it has error saying : `parsebib--char: [Parsebib error]: "Expected [@], got 't' at position 2,8" `.

Hmm, that's a bit harder for me to debug, because I don't use helm. Position (2,8) would be the first `t` of the `title` field, but at this point parsebib shouldn't be looking for a new entry. Could you do `M-x toggle-debug-on-entry` and then perform the procedure you just described? You should get a `*Backtrace*` buffer: it would be helpful if you could post the contents of it here.

**Comment by tmalsburg** [comment]
#454 is merged. Thank you!

**Comment by joostkremers** [comment]
> #454 is merged. Thank you!

Don't thank me yet... There's still a bug that needs to be squashed. :disappointed:

**Comment by gongzhitaao** [comment]
It worked for me.

**Comment by lnguyen4** [comment]
> It worked for me.

Would you mind giving the versions of the packages you have on your system? There may be obsolete dependency packages on my end. I usually use melpa repos. What is your emacs version? thanks

**Comment by joostkremers** [comment]
Thanks @lnguyen4 , that was very helpful. I indeed found another bug that was introduced by the new `parsebib` version but had to be fixed in `bibtex-completion`. I created another PR.

The reason for these bugs is that `bibtex-completion` uses `parsebib`'s low-level API, which I made change to because I thought my own package Ebib was the only package using it... The low-level API depends on the buffer position of point, and I made some changes to where the various functions expect point to be. This obviously backfired...

I checked the places where `bibtex-completion` uses `parsebib`, and I *think* things are now correct. I just hope that I haven't overlooked something else...

My apologies for all the hassle this is causing and my thanks to all of you for your patients!

**Comment by lnguyen4** [comment]
> Thanks @lnguyen4 , that was very helpful. I indeed found another bug that was introduced by the new `parsebib` version but had to be fixed in `bibtex-completion`. I created another PR.
> 
> The reason for these bugs is that `bibtex-completion` uses `parsebib`'s low-level API, which I made change to because I thought my own package Ebib was the only package using it... The low-level API depends on the buffer position of point, and I made some changes to where the various functions expect point to be. This obviously backfired...
> 
> I checked the places where `bibtex-completion` uses `parsebib`, and I _think_ things are now correct. I just hope that I haven't overlooked something else...
> 
> My apologies for all the hassle this is causing and my thanks to all of you for your patience!

No problem. Emacs rules! :). And I updated the el file from your PR. It works like usual now. I can select all the actions on the entry and no error happens. Thanks a lot.

**Comment by lnguyen4** [comment]
> * emacs: `GNU Emacs 29.4 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.41, cairo version 1.18.0) of 2024-06-27, modified by Debian`
> 
>     * parsebib: 6.0
> 
>     * bibtex-completion: 1.0.0
> 
>     * helm-bibtex: 2.0.1

I see. My bibtex-completion is pretty recent. 

`bibtex-completion-20241115.847`
`helm-bibtex-20231009.1014`
`parsebib-20241112.2030`
`helm-20241112.620`
`helm-bibtex-20231009.1014`
`helm-core-20241109.438`

**Comment by joostkremers** [comment]
I'm closing this issue now, I think the most obvious bugs have been worked out. I will keep monitoring the issues in this repo, so if anything comes up, I'll be notified.
