### ISSUE TITLE
Parsing bibliography no longer terminates

### ISSUE THREAD

**Issue by malb** [tmalsburg/helm-bibtex#456]
Since the upgrade to the new parsebib version, I can no longer use `bibtex-completion` and friends. Here's a minimal failing example:

```elisp
(require 'helm-bibtex)
(setq bibtex-completion-bibliography '("PATH/abbrev3.bib" "PATH/crypto_crossref.bib"))
(bibtex-completion-candidates)
```

The two files are:
- [abbrev3](https://cryptobib.di.ens.fr/cryptobib/static/files/abbrev3.bib)
- [crypto_crossref.bib](https://cryptobib.di.ens.fr/cryptobib/static/files/crypto_crossref.bib)

The second is arguably a large file but FWIW it's the standard file everybody in my field uses.

I don't get an error message, it just runs "forever": I killed it after 10 minutes, previously it ran in less than a minute.

**Comment by malb** [comment]
I've reported the issue here https://github.com/joostkremers/parsebib/issues/34 too because it's not clear to me where the issue lies. Feel free to close this issue if you understand it's not helm-bibtex's "fault".

**Comment by joostkremers** [comment]
You can close this, as it's not related to helm-bibtex.
