### ISSUE TITLE
Debugger entered--Lisp error: (wrong-type-argument keymapp nil)

### ISSUE THREAD

**Issue by icymist** [tmalsburg/helm-bibtex#49]
I get the following error message.

Debugger entered--Lisp error: (wrong-type-argument keymapp nil)
  define-key(nil [menu-bar Tools Helm Tools] ("Tools" keymap "Tools"))

The full debug backtrace is at https://gist.github.com/icymist/58c10c770dbd6a0cf51f#file-wrong-type-argument-keymapp-nil

I can still use the package though.

I am on Emacs 24.9. All packages updated to latest MELPA.

Let me know if I can help further.

**Comment by tmalsburg** [comment]
Hm, I can't reproduce this in the current development version of Emacs.  I don't pass a keymap to `easy-menu-add-item` but according to the documentation that's ok.

Do you get the error when you run `emacs -Q` and eval the file helm-bibtex.el?

**Comment by icymist** [comment]
It is pretty strange.

This does not give an error.
01:00 $ mv .emacs newemacs.el
01:00 $ /Applications/Emacs\ 2.app/Contents/MacOS/Emacs -no-site-file --debug-init -l ./newemacs.el

But, this does.
01:01 $ mv newemacs.el .emacs.el
01:01 $ /Applications/Emacs\ 2.app/Contents/MacOS/Emacs -no-site-file --debug-init -l ./.emacs.el

Also, it gives an error if I rename the file .emacs, or init.el.

I am on OSX Yosemite. And it happens both with 24.4 Emacs and 24.5 Emacs.

The minimal emacs with which I can reproduce this issue is:
(require 'package)
(setq package-list '(use-package))
(add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/"))
(add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/") t)
(package-initialize)
(require 'use-package)
(setq use-package-verbose t)
(use-package helm-bibtex
  :init
  (setq helm-bibtex-bibliography '("~/work/mypapers/mynewrefs.bib")
        helm-bibtex-library-path '("~/work/papers")
        helm-bibtex-pdf-open-function 'helm-open-file-with-default-tool
        )
  )

**Comment by tmalsburg** [comment]
`-no-site-file` is not the same as `-Q`.  Is it possible that there are compiled versions of those files (.elc)?

**Comment by icymist** [comment]
The issued is solved. I didn't use (require 'helm-config). The error does not appear anymore after I use it.

Thanks for looking though.

**Comment by tmalsburg** [comment]
Thanks for the update.  Perhaps, we should `(require helm-config)` in `helm-bibtex` then.
