### ISSUE TITLE
Possibility of star system

### ISSUE THREAD

**Issue by llcc** [tmalsburg/helm-bibtex#52]
Hi @tmalsburg 

Is it possible to give a star function to `helm-bibtex`, then it can be easier to find some important bibliographies marked before? or think in another way, like i can add priority to any single org-mode headline in org-mode, then let `helm-bibtex` recognize it? Does this can come true?

**Comment by tmalsburg** [comment]
This feature would require that helm-bibtex can store information in the bibliography but there is currently no infrastructure for that.  However, you could use a "star" tag and search for that.  See [http://article.gmane.org/gmane.emacs.orgmode/98435](here) for a description of tags.

**Comment by llcc** [comment]
I also implemented it according what you said above.
