### ISSUE TITLE
insert formatted references "leaves out" authors

### ISSUE THREAD

**Issue by zeltak** [tmalsburg/helm-bibtex#54]
Hi Titus

As requested im posting the issue on github. i have put an example below of a .bib entry i have

```
@article{abby-2015-prenat-early,
  author =	 {Abby F. Fleisch, Heike Luttmann-Gibson, Wei Perng,
                  Sheryl L. Rifas-Shiman, Brent A. Coull,
                  Petros Koutrakis, Joel D. Schwartz, Antonella
                  Zanobetti, Christos S.  Mantzoros, Matthew
                  W. Gillman, , Diane R. Gold, , Emily Oken, },
  title =	 {Prenatal and Early Life Exposure To Traffic
                  Pollution and Cardiometabolic Health in Childhood},
  journal =	 {},
  year =	 {2105},
  pubstate =	 {prep},
  tags =	 { },
}
```
and how org inserts the formatted references into emacs (only the 1st author is present as you can see:

```
- Abby F. Fleisch, H. L. (2015). Prenatal and early life exposure to
  traffic pollution and cardiometabolic health in childhood. , (), .
```

Maybe its my entry that isnt properly formatted (i use org-ref-clean for that)? 

thx

Z

**Comment by tmalsburg** [comment]
> Maybe its my entry that isnt properly formatted (i use org-ref-clean for that)?

Yes, the formatting is the problem.  In the author field, commas are used to separate last name from first name but to separate authors.  Example: `LastName1, FirstName1 and LastName2, FirstName2 and ...`
