### ISSUE TITLE
File mode specification error

### ISSUE THREAD

**Issue by jmburgos** [tmalsburg/helm-bibtex#55]
Hi Titus, 

I am having an issue with a few items in my bibliography.  I insert a citation, using the helm-bibtex function, but when I click on the link (to open the pdf, for example) I get the following in the message buffer:

File mode specification error: (invalid-function dbus-ignore-errors)
(No changes need to be saved)
File mode specification error: (invalid-function dbus-ignore-errors)
progn: Wrong type argument: stringp, nil
(No changes need to be saved)
File mode specification error: (invalid-function dbus-ignore-errors)
!!! No entry found !!!

This happens only with some references.  Here is the bibtex entry for two of them, in case it is of any use:

@Techreport{Cameron2011,
  Title                    = {EUSeaMap - Preparatory Action for development and assessment of a European broad-scale seabed habitat map final report},
  Author                   = {Cameron, A., and Askew, N.},
  Year                     = {2011},
  Note                     = {Available at http://jncc.gov.uk/euseamap},
  File                     = {:Cameron2011.pdf:PDF},
  Timestamp                = {2013.09.09}
}

@Techreport{EUSeaMap,
  Title                    = {Technical Appendix No. 2: Wave base data and thresholds},
  Author                   = {EUSeaMap},
  File                     = {:EUSeaMap.pdf:PDF},
  Owner                    = {julian},
  Timestamp                = {2015.05.22}
}

Let me know if you need any other information

All the best,

Julian

**Comment by tmalsburg** [comment]
Hi Julian, helm-bibtex is not responsible for opening links, so the error must be happening somewhere else.  What kind of document are you editing?  Is it an org-mode file or latex?  Are you using using org-ref?  It would also help to see the link that you're clicking on.

**Comment by jmburgos** [comment]
Hi Titus,
It is an org-mode file.  I can reproduce the error with a blank org-mode file where I use helm-bibtex to enter one of the problematic citations, so the only entry in the file is this:

autocite:Cameron2011

Then if I click on the citation, I get the error I mentioned.  And yes, I am using org-ref.

**Comment by tmalsburg** [comment]
Ah, in this case you have to talk to John Kitchin, the developer of org-ref.  org-ref modifies the behavior of helm-bibtex with respect to how citations are generated.  Vanilla helm-bibtex generates a different style of citations which look like this:

     [[/path/to/pdfs/Cameron2011.pdf]]

**Comment by jmburgos** [comment]
Ah, you are right... the change in the citation link happens in org-ref.  Thanks!
