### ISSUE TITLE
Highlighted and clickable pandoc citations

### ISSUE THREAD

**Issue by stvharman** [tmalsburg/helm-bibtex#58]
Hello, 

First of all sorry about my lack of emacs knowledge to achieve what I'm asking here.

Would there be any way of making an inserted pandoc citation a link highlighted and clickable?

As you know a typical pandoc citation is like this [@mycitation]

I would like @mycitation to become an active link in emacs. When clicked, it should take the person to the related entry in helm-bibtex.

Thanks in advance,

--
Steve

**Comment by tmalsburg** [comment]
You might want to check [org-ref](https://www.youtube.com/watch?v=JyvpSVl4_dg) which has a similar feature and which works with helm-bibtex.

**Comment by stvharman** [comment]
Thanks for the link. I haven't seen org-ref. but How is it different from helm-bibtex? It seems very similar. I would like to avoid depending on another layer. Honestly, I can't see the delta. I think helm-bibtex, as the primary package working with different file types could provide this functionality. But as I said, I don't know emacs.. maybe there is a reason why you say so.

**Comment by tmalsburg** [comment]
Org-ref uses helm-bibtex but adds more features like the one you were asking for.  Therefore it doesn't make sense to add things like that in helm-bibtex because we would duplicate the work.  Also, there is really no downside to installing org-ref in addition to helm-bibtex.
