### ISSUE TITLE
Request for new action: insert link to pdf and title

### ISSUE THREAD

**Issue by jmburgos** [tmalsburg/helm-bibtex#60]
Hi Titus,
Sorry if this is a very personalized request.  When I was using RefTex, I had customized an "citation" option that inserted an org link to the pdf and the title of the selected reference.  I used this quite a bit to prepare lists of bilbiography to read for particular projects.  When using this option, I would get something like this:

** [[/home/julian/Documents/Refs/Lurton2015.pdf][Lurton2015]] Backscatter measurements by seafloor-mapping sonars 

It seems that it should be relatively simple to create a new function to do this.  But my emacs lisp knowledge is very limited.  I started with this:

(defun helm-bibtex-insert-link-to-pdf-and-title (_)
  "Insert link to pdf and title at point."
  (let ((keys (helm-marked-candidates :with-wildcard t)))
    (with-helm-current-buffer
      (insert
        (concat "**[[" 
                helm-bibtex-library-path 
                (funcall 'helm-bibtex-format-citation-default keys)
                 ".pdf]["
                (funcall 'helm-bibtex-format-citation-default keys)
                "]]"
)))))

But obviously does not work (I get a "Wrong type argument: characterp" error), and I am not sure how to get the title in.  Whenever you have the chance, could you give me a hand?
Many thanks,

Julian

**Comment by tmalsburg** [comment]
Wouldn't it be better to generate a link of the following form?:

    ** [[/home/julian/Documents/Refs/Lurton2015.pdf][Backscatter measurements by seafloor-mapping sonars]] 

Or do you really need to see the Bibtex-key?

The code for the citation format above is:

    (defun helm-bibtex-format-citation-my-org-link-to-PDF (keys)
      "Formatter for org-links to PDF.  Uses first matching PDF if
    several are available.  Entries for which no PDF is available are
    omitted."
      (s-join ", " (-non-nil
                    (--map (when (cdr it)
                               (format "[[%s][%s]]"
                                       (car it)
                                       (helm-bibtex-get-value "title" (cdr it))))
                           (--map (cons (helm-bibtex-find-pdf it)
                                        (helm-bibtex-get-entry it)) keys)))))
    
    (setq helm-bibtex-format-citation-functions
      '((org-mode      . helm-bibtex-format-citation-my-org-link-to-PDF)
        (latex-mode    . helm-bibtex-format-citation-cite)
        (markdown-mode . helm-bibtex-format-citation-pandoc-citeproc)
        (default       . helm-bibtex-format-citation-default)))

**Comment by jmburgos** [comment]
Thanks Titus!  The Bibtex key would be useful because it gives me the first author and year of publication.  Could you add it?

**Comment by tmalsburg** [comment]
Here ya go:

``` elisp
(defun helm-bibtex-format-citation-my-org-link-to-PDF (keys)
  "Formatter for org-links to PDF.  Uses first matching PDF if
several are available.  Entries for which no PDF is available are
omitted."
  (s-join ", " (-non-nil
                (--map (when (cdr it)
                         (format "[[%s][%s]] %s"
                                 (car it)
                                 (helm-bibtex-get-value "=key=" (cdr it))
                                 (helm-bibtex-get-value "title" (cdr it))))
                       (--map (cons (helm-bibtex-find-pdf it)
                                    (helm-bibtex-get-entry it)) keys)))))
```

**Comment by jmburgos** [comment]
Thanks again!  One last question.  I am using org-ref, which sets the value of  
 ((org-mode . helm-bibtex-format-org-ref) )
    (setq helm-bibtex-format-citation-functions

**Comment by jmburgos** [comment]
Thanks again!  One last question.  I would like to have this as an action, rather than the default citation format in org mode (because most of the time I use LaTex citations in org-mode).  In other words, I would like to call helm-bibtex, select a reference, press TAB, and see "Insert link to pdf and title" as one of the possible actions.  That is why I was trying to make a function similar to  helm-bibtex-insert-key.   I suspect  cannot just modify helm-source bibtex as below, calling helm-bibtex-format-citation-my-org-link-to-PDF as one of the actions, right?

(defvar helm-source-bibtex
  '((name                                      . "BibTeX entries")
    (init                                      . helm-bibtex-init)
    (candidates                                . helm-bibtex-candidates)
    (filtered-candidate-transformer            . helm-bibtex-candidates-formatter)
    (action . (("Open PDF file (if present)"   . helm-bibtex-open-pdf)
               ("Insert link to pdf and title" . Helm-bibtex-format-citation-my-org-link-to-PDF) ; NEW ACTION 
               ("Open URL or DOI in browser"   . helm-bibtex-open-url-or-doi)
               ("Insert citation"              . helm-bibtex-insert-citation)
               ("Insert reference"             . helm-bibtex-insert-reference)
               ("Insert BibTeX key"            . helm-bibtex-insert-key)
               ("Insert BibTeX entry"          . helm-bibtex-insert-bibtex)
               ("Attach PDF to email"          . helm-bibtex-add-PDF-attachment)
               ("Edit notes"                   . helm-bibtex-edit-notes)
               ("Show entry"                   . helm-bibtex-show-entry))))
  "Source for searching in BibTeX files.")

**Comment by tmalsburg** [comment]
Hi Julian, sorry I don't have time to deal with this.  You have to create a new function similar to `helm-bibtex-insert-citation` and add it as an action to the source.  Perhaps a good opportunity to get your feet wet.  Basic Elisp knowledge will allow you to get much more out of Emacs, so it should be worth your time.

**Comment by jmburgos** [comment]
Ok, fair enough. :)  I will dive into this.  Many thanks for your help!
