### ISSUE TITLE
Helm-bibtex always shows fallback option

### ISSUE THREAD

**Issue by swarnendubiswas** [tmalsburg/helm-bibtex#61]
Hi,

I have this issue where invoking helm-bibtex always shows only the fallback options, instead of bibtex entries. I looked at earlier reported issues, and reinstalled parsebib and helm-bibtex, but that does not solve the problem. Here is my initialization snippet:

  (use-package helm-bibtex
    :ensure t
    :commands helm-bibtex
    :config (setq helm-bibtex-bibliography '("~/workspace/bib/plass.bib")))

**Comment by tmalsburg** [comment]
I'm not familiar with use-package but I suspect that your helm setup is not correct.  Please follow the install instructions given [here](https://github.com/emacs-helm/helm#install-from-emacs-packaging-system).

**Comment by swarnendubiswas** [comment]
Hmm, so I tried with a clean .emacs.d, installed helm, just used (require 'helm-config), then autoloaded helm-bibtex, and set helm-bibtex-bibliography to my .bib file. 

Invoking helm-bibtex after that still leads me to the fallback page. 

I have Emacs 24.5.

**Comment by tmalsburg** [comment]
One possibility is that your BibTeX file contains syntax errors.  Unfortunately, Helm doesn't relay error messages at that stage.  Please execute the following elisp and see what result you get:

    (helm-bibtex-candidates)

**Comment by swarnendubiswas** [comment]
`(helm-bibtex-candidates)` gives 
```
Loading bibliography ...
nil
```.

**Comment by tmalsburg** [comment]
This tells us that parsing of the bibliography fails.  Could you please show me the output of this command:

    (file-attributes helm-bibtex-bibliography 'string)

**Comment by swarnendubiswas** [comment]
This is also nil.

**Comment by tmalsburg** [comment]
This means that the path to your bibliography is incorrect.  The file that you specified does not exist.

**Comment by swarnendubiswas** [comment]
I get what you are saying often happens, but thankfully that doesn't seem to be the problem here.

![screenshot-1](https://cloud.githubusercontent.com/assets/7343807/10560750/5b3705de-74e2-11e5-9eb4-5c15d8bd1279.png)

**Comment by tmalsburg** [comment]
Oh, I see that `helm-bibtex-bibliography` is a list in your case.  So can you try this:

    (file-attributes "~/workspace/bib/plass.bib" 'string)

and if this gives nil please also try

    (file-attributes "/home/biswass/workspace/bib/plass.bib" 'string)

If these commands return file information instead of `nil`, the most likely explanation is that your bibtex file contains syntax errors.

**Comment by swarnendubiswas** [comment]
The first command gives 
`(nil 1 "biswass" "biswass" (22069 7254 580450 175000) (22069 7235 431395 281000) (22069 7235 431395 281000) 264553 "-rw-r--r--" t 1515049 64770)`

**Comment by tmalsburg** [comment]
This suggests that your BibTeX file has syntax errors.  See [this page](http://tex.stackexchange.com/questions/173621/how-to-validate-check-a-biblatex-bib-file) for some ways to check BibTeX.

**Comment by swarnendubiswas** [comment]
Right, I used JabRef to check for errors, and after that helm-bibtex seems to work. Will probably test on a couple of other machines and will confirm after a few days. Thanks for the tip.

**Comment by tmalsburg** [comment]
Glad to hear that it's working now.  Unfortunately, the parser used in helm-bibtex doesn't produce any helpful error messages when the file has syntax errors.
