### ISSUE TITLE
Add doi to formatted reference in APA style

### ISSUE THREAD

**Issue by cpaulik** [tmalsburg/helm-bibtex#65]
I think it would be a good feature to add the doi to `helm-bibtex-apa-format-reference`. According to [this site](https://www.library.cornell.edu/research/citation/apa) it should come in last place.

**Comment by tmalsburg** [comment]
Added in 76536e4f903ec2336fa6baaca3981a24b604db85.

**Comment by tmalsburg** [comment]
I prefixed the DOI with `http://dx.doi.org/` such that emacs interprets it as a link in org files and in emails.

**Comment by cpaulik** [comment]
Thank you.
