### ISSUE TITLE
Support for PDFs specified in the `File` field

### ISSUE THREAD

**Issue by tmalsburg** [tmalsburg/helm-bibtex#71]
There has been discussion about this every now and then (#53, #63, #69) and I'd like to resolve this now.  Everyone interested in this, please check the feature branch [file-field](https://github.com/tmalsburg/helm-bibtex/tree/file-field).

One open question is what formats for the path specification we should support.  The format generated by JabRef (and perhaps Mendeley) apparently is `File = {:/home/ramon/a_directory/some_file_123.pdf:PDF}`.   Are there other formats like bare paths or just bare file names?  I don't use the `File` field, so I need input from affected users.

@rdiaz02  @mclearc @mwlodarczak

**Comment by scottmartincampbell** [comment]
I use a file = {/home/scott/a_directory/file.pdf} to work with ebib. It also allows separators for multiple files. The default is ";", but I use ":".

**Comment by tmalsburg** [comment]
@scottmartincampbell, the code in the branch should work for you, except for the cases with multiple files.  The problem with those is that other people use `:` as part of the file names, so splitting the value using `:` is not going to work for them.

**Comment by mwlodarczak** [comment]
On 11/11/2015 07:10 PM, Titus von der Malsburg wrote:
> One open question is what formats for the path specification we
> should support.  The format generated by JabRef (and perhaps
> Mendeley) apparently is `File =
> {:/home/ramon/a_directory/some_file_123.pdf:PDF}`.   Are there other
> formats like bare paths or just bare file names?  I don't use the
> `File` field, so I need input from affected users.

BibDesk is very popular on the Mac so it would be good to know what
format it uses.

**Comment by tmalsburg** [comment]
@mwlodarczak, thanks for pointing that out. Unfortunately, I don't have a Mac and can't check.

**Comment by mwlodarczak** [comment]
On 11/11/2015 09:06 PM, Titus von der Malsburg wrote:
> @mwlodarczak, thanks for pointing that out. Unfortunately, I don't
> have a Mac and can't check.

(Un)fortunately, neither do I.

**Comment by rdiaz02** [comment]
JabRef, Zotero (via Better BibTex ---BBT) and Mendeley produce something like this (this is from Zotero):

`file = {citeulike7040306-ejnkzuyv.pdf:/home/ramon/Zotero-data/storage/A6WEKQCF/citeulike7040306-ejnkzuyv.pdf:application/pdf}`

**Details for a single file from JabRef and Zotero and Mendeley**
   - The field name can be `file` (if coming from Zotero with BBT or from Mendeley) or `File` (JabRef)
   - The structure is: short name of file, a colon, a path (often the full path), a colon, the file type. We always have the two colons (`:`) per entry, but some content can be missing. In particular, for new entries in both Mendeley and JabRef the short name can be missing so the above would be `{:/home/ramon/Zotero-data/storage/A6WEKQCF/citeulike7040306-ejnkzuyv.pdf:pdf}`.
   - The file type from Zotero + BBT is the same as returned, for instance, by `xdg-mime query filetype`, so we see "application/pdf". However, Mendeley will just give "pdf". JabRef, as far as I can tell, can give either one of them (it preserves whatever you imported) and also "PDF" (for newly added files).


**Details for multiple files**
   - Entries for different files are separated by a semicolon (`;`). The entry for each file is as above. 
   - An example from Zotero + BBT that shows two pdfs and one html (note there is no file type explicitly given for the html): `file = {emacs-xtra.pdf:/home/ramon/Zotero-data/storage/3CK264D2/emacs-xtra.pdf:application/pdf;emacs.pdf:/home/ramon/Zotero-data/storage/4WNZK447/emacs.pdf:application/pdf;GNU Emacs manual - GNU Project - Free Software Foundation (FSF):/home/ramon/Zotero-data/storage/C9GCWNFP/emacs.html:}`

**Caveat**
This I have just checked in a system running Linux. No idea what happens in other systems (e.g., how is file type reported, for instance ---but I guess that does not matter).

**Comment by tmalsburg** [comment]
@rdiaz02, thank you very much for this summary.  It's not clear how this format deals with file names that include colons and/or semicolons (these file names break the format) but I suppose these are rare enough that we can ignore them for now.

**Comment by scottmartincampbell** [comment]
I'd say ignoring for now is okay. I've imported thousands of entries from Zotero, and from what I can tell, file names with a colon are escaped, as in ```\:```. Or perhaps it was the Biblatex exporter I used. 

In any case, when that situation comes up (or I add a new entry with a colon in the file name) I just fix things manually by renaming the file and field by hand.

**Comment by tmalsburg** [comment]
Just pushed a new version to the branch file-field.  This code now supports the format described by @rdiaz02 (including multiple PDFs).  But bare paths to PDFs work as well.  For this to work, you have to set:

``` elisp
    (setq helm-bibtex-pdf-field "file")
```

If no PDF is found  using the information in the file field, helm-bibtex falls back to the searching the library path for files named `<bibtex-key>.pdf`.

Bug reports, success stories, and suggestions for improvements are welcome.

**Comment by tmalsburg** [comment]
I should say that this code is only in the file-field branch.  I will merge into master once I have confirmation that it works as expected.

**Comment by rdiaz02** [comment]
In some limited testing (sorry, swamped by teaching) it works fine. it deals with entries with a single file and with entries with multiple files, where all of the files are opened. Neat!

**Comment by tmalsburg** [comment]
Thanks, Ramon.  I will merge then.

**Comment by rdiaz02** [comment]
I forgot to add that it also works with files that have spaces in the names, which is nice.

**Comment by Titan-C** [comment]
This is not working with my bibtex database generated by Mendeley, despite the statement in https://github.com/tmalsburg/helm-bibtex/blob/master/helm-bibtex.el#L454-L456
Mendeley does not save the leading / in the file field.
I'm using emacs 24.5.1 on arch-linux

I made it work after a lot of trial and error, and without elisp knowledge than this work with:
```lisp
else
  collect (concat "/" path)))))))
```

**Comment by tmalsburg** [comment]
Thanks for reporting.  I had a work-around for Mendeley but it was buggy and also unnecessary.  Please try the latest version (acb1923d5ff6838f3693ce6bfc3792556762b45f).

**Comment by Titan-C** [comment]
Thank you. I does work now.

**Comment by Titan-C** [comment]
I'm sorry to bug this issue again. But dealing with Mendeley generated bibtex file stopped working for me, not sure which package update is responsible. Again doing `concat "/" path` fixes the issue

**Comment by tmalsburg** [comment]
I suspect that you are using an outdated version.  The relevant code hasn't changed recently and it is working correctly on my machine.  Perhaps you have an outdated .elc file somewhere?

**Comment by averter** [comment]
Sorry to revisit this but I am also experiencing some problems with this feature. My helm-bibtex is version 20190214.1609 and helm-bibtex keeps trying to find a bibtex-key.pdf file instead of using the `file` field; `output is no pdf found for bibtex-key`
I am using Zotero, okular and this is my helm-bibtex configuration: 

  ;; Helm bibtex 
  (setq helm-bibtex-bibliography '("~/Documents/mytestfile.bib"))
  (setq helm-bibtex-pdf-field "file")  ;; bibtex-completion-pdf-field "file"
  (setq bibtex-completion-pdf-symbol "⌘")
  (setq bibtex-completion-notes-symbol "✎")
  (setq bibtex-completion-pdf-open-function
	(lambda (fpath)
	  (start-process "okular" "*helm-bibtex-okular*" "/usr/bin/okular" fpath)))

I am new to helm-bibtex so apologies for any obvious error. Thank you in advance for your help

**Comment by tmalsburg** [comment]
Could you please supply an example BibTeX entry?

**Comment by averter** [comment]
Here is an example (I've just edited the username)

```
@article{papadimitriou_entropy-based_2000,
  title = {Entropy-{{Based Optimal Sensor Location}} for {{Structural Model Updating}}},
  volume = {6},
  doi = {10.1177/107754630000600508},
  number = {5},
  journal = {Journal of Vibration and Control},
  author = {Papadimitriou, Costas and Beck, James L. and Au, Siu-Kui},
  year = {2000},
  pages = {781-800},
  file = {/home/myusername/Zotero/storage/FPCQBHU8/Papadimitrou-2000_01-entropy_based_optimal_sensor.pdf;/home/myusername/Zotero/storage/LPL3LUK4/Papadimitrou-2000_01-entropy_based_optimal_sensor.pdf}
}

```

**Comment by averter** [comment]
My query was misdirected. I thought it was a problem with helm, while in reality a `org-ref-open-pdf-at-point` function was being called. This [post](https://github.com/jkitchin/org-ref/issues/485) solved the issue for me. Thanks for your help @tmalsburg

**Comment by tmalsburg** [comment]
Oops, this got buried in my to-do list.  Thanks for the feedback.

**Comment by nimafazeli** [comment]
I would like to bump this up and signal that helm-bibtex does not locate the pdf files in the file field by mendeley on Windows. 
Instead of the pdf I get a `dired` buffer asking me to locate the file manually.

Here are my settings in the `dotspacemacs/user-config` :

```
        bibtex-completion-bibliography '("~/Dropbox/mylibrary/references.bib"
                                         "~/Dropbox/mylibrary/mendeleyBib/library.bib"

        bibtex-completion-library-path '("~/Documents/Mendeley Desktop"
                                         "~/Dropbox/mylibrary/papers" )
        bibtex-completion-pdf-field "file"
        bibtex-completion-notes-path "~/Dropbox/mylibrary/literature.org"

```
I tried to set the pdf-field variable with `file` and `nil` both of them leading to the same result.

Here is an example of the bibfile generated by mendeley on Windows:

```
@article{Laffont1986a,
author = {Laffont, Jean-Jacques and Tirole, Jean},
title = {{Using Cost Observations to Regulate Firms}},
file = {:C\:/Users/nima/Documents/Mendeley Desktop/Laffont, Tirole - 1986.pdf:pdf},
journal = {Journal of Political Economy},
mendeley-tags = {IO,Industrial Organization,Regulation,classic,procurement,regulation,seminal},
month = {jun},
number = {3},
pages = {614--641},
volume = {94},
year = {1986}
}
```
I am on "GNU Emacs 28.2 (build 2, x86_64-w64-mingw32) of 2022-09-13" with Spacemacs and bibtex layer installed.
Let me know if you require any other info.
