### ISSUE TITLE
Code for changing helm-bibtex-default-cite-command

### ISSUE THREAD

**Issue by drgibbon** [tmalsburg/helm-bibtex#75]
I know this is a simple question, but I can't work out how to actually set "helm-bibtex-default-cite-command" to something other than the default. I'd like to change the default "cite" to "parencite", so I tried ```(setq helm-bibtex-default-cite-command "parencite")```
but it didn't work.

**Comment by tmalsburg** [comment]
Just saw that threre is a mistake in the documentation.  The name of the variable is `helm-bibtex-cite-default-command`.  Sorry about that.

**Comment by tmalsburg** [comment]
Fixed in 9f6e554c9b6369c02a894cd4cfd80df712a67988.
