### ISSUE TITLE
How to clear cached candidates?

### ISSUE THREAD

**Issue by sewkokot** [tmalsburg/helm-bibtex#78]
First thank you for this very useful bibtex tool. So far I have used the standard AucTeX and reftex facilities to insert citations, but helm-bibtex is far more superior :) 

Back to my question:
sometimes I add pdf files to bib entries and want to see the updated state after re-issue of helm-bibtex. However helm-bibtex reads candidates from cache so the pdf file icon is missing. How to force invalidating of cache or regenerating it?

**Comment by tmalsburg** [comment]
Yes, this is suboptimal.  We could check whether the notes and PDFs have changed everytime a search is started but that would be expensive and defy the purpose of caching.  Perhaps there is a clever heuristic to decide whether it's time to reread the bibliography.  I'll think about it.

For the time being, there are two things you can do to trigger a reread:

* Modify the bibtex-file.
* `(setq helm-bibtex-bibliography-hash "")`

**Comment by sewkokot** [comment]
What about prefix arg for helm-bibtex forcing the clearing of the cache on demand?
For example projectile-find-file uses such approach:

```
(defun projectile-find-file (&optional arg)
  "Jump to a project's file using completion.
With a prefix ARG invalidates the cache first."
  (interactive "P")
  (projectile-maybe-invalidate-cache arg)
  (let ((file (projectile-completing-read "Find file: "
                                          (projectile-current-project-files))))
    (find-file (expand-file-name file (projectile-project-root)))
    (run-hooks 'projectile-find-file-hook)))
```

**Comment by tmalsburg** [comment]
Does this mean that users are prompted for ARG every time they `M-x helm-bibtex`.  Wouldn't that be a little annoying given that you don't want to invalidate the cache in the vast majority of cases?

**Comment by sewkokot** [comment]
No, ARG would be optional. Then C-u before M-x or keybinding would force invalidating the cache.

**Comment by sewkokot** [comment]
helm-projectile function has something similar. So what do you think on following modification of helm-bibtex function?

```
(defun helm-bibtex (&optional arg)
  "Search BibTeX entries.

With a prefix ARG invalidates the cache first."
  (interactive "P")
  (when arg
	(setq helm-bibtex-bibliography-hash ""))
  (helm :sources '(helm-source-bibtex helm-source-fallback-options)
        :full-frame helm-bibtex-full-frame
        :candidate-number-limit 500))
```

**Comment by tmalsburg** [comment]
This would be a viable solution.  Ideally, however, the user shouldn't have to worry about the cache.  I think it's possible to detect an outdated cache without wasting too much cycles using the following sheme:

1. Compare last-modification dates of the directories for PDFs with stored last-modification dates.
2. If unchanged, done, else go through the entries in `helm-bibtex-cached-candidates` and update PDFs.

This does not require parsing of the BibTeX files and should therefore be reasonably fast.  Notes would be handled the same way.  Would this work, or am I missing something?

**Comment by sewkokot** [comment]
At a glance your algorithm is definitly better to cope with the cache automatically. I'm not an expert however to tell if it would work on all OSs. Tomorrow I will do more testing...

**Comment by sewkokot** [comment]
I thought about your solution and the code should also take into account the removal or addition of pdf/note directories after the last cache being made, in this case the last modification dates would require being stored in an association list. For now I would stay with the prefix arg "C-u", unless me, you or somebody else finds time to write a reliable code the automatic detection of an outdated cache.

**Comment by tmalsburg** [comment]
Ok! Do you want to make a PR?

**Comment by sewkokot** [comment]
This would be my first PR (I need to read the docs to do it properly), so unless you wait until tomorrow, you can insert this small modification yourself if you wish. Thank you!
