### ISSUE TITLE
Search notes support

### ISSUE THREAD

**Issue by jagrg** [tmalsburg/helm-bibtex#81]
The idea of editing and creating notes is nice, but I would also like the ability to search the content of notes. The function below works well as a fallback option, but I think it would be more useful if I could bind it to a keystroke directly. Do you know how I can do this? Or maybe you have a better idea.

``` elisp
(defun helm-bibtex-search-notes ()
  "Search notes file."
  (let ((input (format "%s" helm-pattern)))
    (when (f-file? helm-bibtex-notes-path)
      (find-file helm-bibtex-notes-path)
      (occur input)
      (other-window 1))))
```

**Comment by tmalsburg** [comment]
Perhaps you can add helm-swoop or helm-occur as another source below the source showing the BibTeX matches?

**Comment by jagrg** [comment]
Can you be more specific.

**Comment by tmalsburg** [comment]
You can combine several sources in one helm command.  See helm-for-files for an example.  You could do the same with helm-bibtex and helm-swoop for example.

**Comment by jagrg** [comment]
The following is close enough. I'll give it a try. It makes sense to do this from helm-bibtex though. At least in theory.

```emacs-lisp
(defun helm-bibtex-search-notes (candidate)
  "Search notes file."
  (if (boundp 'helm-bibtex-notes-template-one-file)
      (progn
	(find-file helm-bibtex-notes-path)
	(goto-char (point-min))
	(helm-swoop :$query helm-pattern))))

(helm-delete-action-from-source "Search my notes" helm-source-bibtex)
(helm-add-action-to-source "Search my notes" 'helm-bibtex-search-notes helm-source-bibtex 10)
```

**Comment by tmalsburg** [comment]
This is not what I meant.  I was thinking of something like the below:

``` elisp
(defun helm-bibtex (&optional arg)
  "Search BibTeX entries.

With a prefix ARG the cache is invalidated and the bibliography
reread."
  (interactive "P")
  (when arg
    (setq helm-bibtex-bibliography-hash ""))
  (helm :sources '(helm-source-bibtex helm-swoop-in-notes helm-source-fallback-options)
        :full-frame helm-bibtex-full-frame
        :candidate-number-limit 500))
```

This code doesn’t work because `helm-swoop-in-notes` does not exist, but if you could come up with a variant of helm-swoop that uses a pre-defined file (the notes file), this would be a much nicer solution because it would give you notes results along with results form the BibTeX file.

**Comment by jagrg** [comment]
Thanks for the explanation. This what I tried:

```emacs-lisp
(defun my-search-notes-function (candidate)
  "Search notes file."
  (if (f-file? helm-bibtex-notes-path)
      (progn
        (find-file helm-bibtex-notes-path)
        (goto-char (point-min))
        (helm-swoop :$query  helm-pattern))))

(helm :sources `((name                             . "Search notes")
		 (init                             . helm-bibtex-init)
		 (candidates                       . helm-bibtex-candidates)
		 (filtered-candidate-transformer   . helm-bibtex-candidates-formatter)
		 (action . (("Search my notes"     . my-search-notes-function)))))
```

The problem is that if the search query is not found in any of the entries we are left with the fallback option. The question then is how do we check if the query exists in the notes file? So that typing "oranges and apples" would narrow to the entries that actually contain those terms?

We also only need to display entries with notes and not the full bibliography. Maybe a single candidate (ie Search notes) would suffice.

**Comment by jagrg** [comment]
I had this idea of using `helm-org-in-buffer-headings` for the purpose of searching helm-bibtex notes. It also has a fallback of its own which is nice. I'm assuming you use top level headlines for notes. If not, you need to change min and max-depth. The command you want to use is `helm-bitex-show-notes`.

https://gist.github.com/jagrg/39d68432c783df50d199

**Comment by chrikoehn** [comment]
Hi, I'd also like to be able to search notes. Has there been any progress on this? I tried some of the above suggestions but they did not work as I would like them to work (and one did not work, probably an error on my side). @jagrg , your latest function `helm-bibtex-show-notes` works well but I'd like to be able to find something outside of the headings and I would like to always see a publication's basic information together with the part of the note that is matching. Is this behaviour different from what you would consider as ideal behaviour (maybe `helm-bibtex-show-notes` is already all you want?)?

**Comment by tmalsburg** [comment]
Showing publication information side-by-side with matching text in notes is, I think, not achievable with a quick hack but requires substantial work.  It sounds useful but I won't have time to work on that. However, I still think that it would be easy to combine helm-bibtex with a helm-swoop on the notes file, and this would give us something that is almost as useful as what you ideally want to have.

**Comment by jagrg** [comment]
TBH I don't know how this could be useful. What I do now is I type the notes symbol (`*` in my case) to get a list of all entries with notes followed by space and some keyword (org-ref has a nice function to add/delete keywords from helm-bibtex) which could also be in the title. This is usually enough for me, and if I need to do a more extensive search, I can always do it from the notes file. You might also try `helm-org-rifle`, which shows the results as well as the the heading title.
