### ISSUE TITLE
Invalid use of `\' in replacement text

### ISSUE THREAD

**Issue by jlapeyre** [tmalsburg/helm-bibtex#83]
If there is a ``\`` in the title of a bibtex entry, then trying to create a notes entry results in

```
Invalid use of `\' in replacement text
```

in the minibuffer, and no entry.  An example is
```
title = {Title $\phi$},
```

Using ``helm-bibtex-20151222.2252``

**Comment by tmalsburg** [comment]
A good old-fashioned bug.  Thanks for reporting.  I'll look into it.

**Comment by tmalsburg** [comment]
Fixed.  Thanks for reporting.
