### ISSUE TITLE
Does not handle comments

### ISSUE THREAD

**Issue by sachdevaprash** [tmalsburg/helm-bibtex#85]
The helm-bibtex command fails to handle comments in bibtex file. A simple example is as follows:

    @inproceedings{zhang11musicACThand,
      author = {Ada Zhang and Mark Malhotra and Yoky Matsuoka},
      title = {Musical piano performance by the ACT Hand},
      DATE_ADDED =   {Tue Dec 29 19:26:04 2015},
      booktitle = {2011 IEEE International Conference on Robotics and Automation},
      year = {2011},
      month = {5},
      pages = {nil},
      doi = {10.1109/icra.2011.5980342},
      url = {http://dx.doi.org/10.1109/icra.2011.5980342},
    }

    @Comment KAPANDJI

    @book{kapandji,
        author = {Kapandji, Ibranim A.},
        publisher = {Churchill Livingstone},
        title = {{The Physiology of the Joints, Volume 1: Upper Limb}},
        volume = {1},
        year = {2007},
    }

**Comment by tmalsburg** [comment]
To my knowledge the correct syntax for comments is this:

    @comment{ KAPANDJI }

If you use this syntax, helm-bibtex works as expected.

**Comment by sachdevaprash** [comment]
I see. It's interesting then that both texlive and my text editor accept the format without braces.
Maybe it might be worth it to accept the loose definition in such a case and accept this format of comments, since I don't see much value in helm-bibtex not processing this. And it should probably be an easier grammar to just ignore everything after "@comment"

Either way, I appreciate the response. Thanks. Also, thanks for all the work on this. Very useful stuff.

**Comment by tmalsburg** [comment]
Many bibtex parsers are permissive because there is so much broken bibtex out there.  The parser that we are using is [parsebib](https://github.com/joostkremers/parsebib).  Perhaps you want to raise the issue there.

**Comment by sachdevaprash** [comment]
Thanks. I see what you mean. I can't find a decent grammar anywhere either.
