### ISSUE TITLE
Multiple PDFs or other file types

### ISSUE THREAD

**Issue by ericdanan** [tmalsburg/helm-bibtex#88]
Hello,

Two related suggestions:
1. Handling several PDFs for a given entry. E.g. for a book there could be key-chap1.pdf, key-chap2.pdf... I don't know if this makes sense, but perhaps helm-bibtex-find-pdf-in-library could check for the regexp key*.pdf? And helm-bibtex-open-pdf could start a helm session to choose the file to open? There are other places where the function helm-bibtex-find-pdf-in-library is used, so perhaps this would create complications...
2. Handling other file types than PDF. E.g. DJVU Perhaps using a custom variable to specify which file extensions to search/open?

I am not really fluent in elisp (or any programming language), but if you think this is worth it I can at least try to do something.

In any case, thank you very much for this very useful package.

Eric

**Comment by tmalsburg** [comment]
I like feature requests like that.  Both features are already present.  If you want multiple PDFs, just separate them using semicolons.  Regarding DJVU, helm-bibtex doesn't really care about file types, it just tells Emacs to open the thing whatever it may be.

**Comment by ericdanan** [comment]
I apologize for not being clear. I didn't mention that I don't store the
file path in the bibtex entry but simply have the files in my library path.
Then if I have an entry with key Doe99 in my bibtex file and two files
Doe99-chap1.pdf and Doe-chap2.pdf, helm-bibtex will not spot them.
Similarly if I have a file Doe99.djvu.

If I enter the (absolute) file path in the bibtex entry, then the djvu
problem is solved indeed. But the multiple files issue will remain because
helm-bibtex will always open the first file. My suggestions were about
having helm-bibtex offering to choose which file to open, and have this to
work even if the files are simply in the library path and not in the bibtex
entry (assuming that the file names begin with the bibtex key and have
extension pdf or djvu, say).

Sorry again if I completely misunderstood something.

**Comment by tmalsburg** [comment]
I see.  I don't use multiple PDFs for single entries, so this feature has very low priority for me.  Also there is a risk that it would slow down initial loading of the library, which I would like to avoid.  Some people use helm-bibtex with truely gigantic bibliographies (e.g., crypto.bib) and the recent chances to PDF detection have already slowed down loading quite a bit.  So the bar is high for an implementation of this feature and the utility (in my personal opinion) low.  Perhaps it is easier if you switch to using the `file` field or if you concatenate the chapter PDFs into one book PDF.

Regarding DJVU, have a look at [this section](https://github.com/tmalsburg/helm-bibtex#different-naming-schemes-for-pdf-files) in the documentation.

**Comment by ericdanan** [comment]
I understand that loading fast is more important, so I'll just concatenate
the pdfs.

It does not seem too complicated to modify helm-bibtex-find-pdf-in-library
to look for "djvu" in addition to "pdf". But again I guess that would
increase loading time, so I'll just convert my DJVUs to PDFs (they will get
bigger but I don't have many of them).

This way my life will also be easier with org-ref, which seems to assume
the default helm-bibtex naming scheme (key.pdf).

Thank you for your answers.

**Comment by tmalsburg** [comment]
Why don't you use the file field?  It allows you to keep chapters separate and you can continue using your DJVU files.  Perhaps, Zotero or JabRef can help generating the file field in a way that doesn't cause too much work.

**Comment by ericdanan** [comment]
The file field would allow me to keep multiple and/or non pdf files indeed,
but somehow I don't find it very convenient to use this field.

One reason is that I prefer not to have this field when I share bibtex
entries with other persons (it is not really part of the reference per se
and they may have different files). In helm-bibtex I can take care of this
simply by putting the file field in the "no-export" fields, but in other
packages like org-ref and reftex it seems that I would have to modify some
hard-coded functions to obtain the same result.

Also, as you say, I would have to resort to an external tool (or create a
function of mine) to easily add files to an entry. And if I'm correct,
helm-bibtex needs the absolute path in the file field, which is not very
flexible if I reorganize my files some day. It is perhaps not so difficult
to deal with all that, but since few files are concerned for me I find it
simpler to stick to the one-entry-one-pdf scheme.

**Comment by tmalsburg** [comment]
I see.  I'll leave this issue open because your feature request is a good one. If someone is willing to write the code I would consider including it (if it doesn't slow down helm-bibtex too much).  Not sure if I will find the time to work on it myself.

**Comment by ericdanan** [comment]
I tried to think (with my limited understanding of elisp) about how to implement this. It seems to me that the loading time issue is that, currently, whenever we call helm-bibtex the function helm-bibtex-find-pdf-in-library is called once per entry (assuming there is no file field in the bibtex entries), and if we are to modify this function we don't want to make it slower.

The simplest solution I can think of would be to put all attachments (PDF or other file types) in a subdirectory of the library path named "key". Then in helm-bibtex-find-pdf-in-library we can simply replace "(-first f-file? .... (s-concat ket ".pdf"))" with "(-first f-dir? ... key)" (and perhaps redefine helm-bibtex-open-pdf to simply call helm-find-files starting in the key subdirectory). It seems to me that this should not affect loading time, but it is very rigid in tems of file organization.

If we want something more flexible in terms of file organization and able to deal with multiple attachments per entry, I guess helm-bibtex-find-pdf-in-library can no longer rely on a call to f-file? because it is not clear which path to check. Then perhaps we could use a custom variable to build a regex for a given key, and have helm-bibtex-find-pdf-in-library check whether this regex matches any file in the library path (we can get this list with directory-files, and perhaps we can even store the list of matches with each entry in order to use it later in helm-bibtex-open-pdf). In that case we could save some time by storing this list of files in a variable once in helm-bibtex instead of once per entry in helm-bibtex-find-pdf-in-library (additionally, we could perhaps only update this variable when the bibliography hash changes). Do you think this regex matching would be slower than the current call to f-file? or would potentially create other issues?

**Comment by tmalsburg** [comment]
Not sure I completely understand your proposal.  Storing the paths for later uses (e.g., in `helm-bibtex-open-pdf`) is not necessary because later uses usually only effect one entry or a small number of entries and are therefore not problematic.  The only problem is the initial loading of the full list of entries.

In general, I think your feature request is reasonable.  However, I also think it affects only a small number of users and I'm not one of them.  For this reason it is unlikely that I will be able to invest time in this.  Again, since other file types and multiple entries work just fine with the `file` field, I recommend, that you consider using that in the meantime.  Sorry, if this is an unsatisfying answer.  But I will continue thinking about this as there have been related feature request recently (e.g., #90 and #91).

**Comment by ericdanan** [comment]
Sure, I understand.

About storing the paths to the PDFs, I understand there is no speed problem with helm-bibtex-open pdf. I was just thinking that once we check for a match it would perhaps be costless to store the list of matches, but perhaps it is not costless after all since we can save time by stopping at the first match instead of looking for all of them.

**Comment by ericdanan** [comment]
Closed by #213
