### ISSUE TITLE
translating citekeys to make filenames from elisp hook?

### ISSUE THREAD

**Issue by jowens** [tmalsburg/helm-bibtex#91]
One helm-bibtex feature that seems awesome is to be able to open a paper PDF if it's named the same as the citekey. My citekey format is Author:YYYY:ABC (this is the "graphbib" citekey format and also essentially what the ACM digital library now does, except ACM puts some numbers afterwards as well).

Unfortunately colons and the Mac file system do not like each other. Filenames in OS X can't have colons.

It would be desirable if I could do some sort of translation within helm-bibtex, that I could add a function hook that took a filename (citekey.pdf, e.g. "Author:2016:ABC.pdf") and returned a transformed filename (say, my citekey where all colons were replaced with forward-slashes, e.g. "Author/2016/ABC.pdf"). Colons appear pretty commonly within citekeys, so I'd bet this would be useful for many users ... ?

(We're making progress on the Papers side for compatibility with Papers, btw, thanks @extracts.)

**Comment by tmalsburg** [comment]
But slashes in filenames won't work either because they are interpreted as directory separators.  So `ABC.pdf` would be the filename and helm-bibtex would try to find that file in the directory `.../Author/2016`.  Or is this intended?

What do you lose if you simply remove colons from BibTeX keys in your bibliography?  As far as I can tell this should not introduce any ambiguity.  Note that bibtex.el also has facilities for auto-generating the BibTeX keys from the contents of the entry (see `bibtex-clean-entry`).  So it should be fairly easy to establish consistent naming of keys without colons.  (I think [org-ref](https://github.com/jkitchin/org-ref) has facilities for batch cleaning of BibTeX entries, too.)

**Comment by jowens** [comment]
I am not an expert on the Colon-Slash Debate of 2016, but do note that I *can* have slashes in filenames on OS X. I agree this is likely confusing, and thus maybe using underscores instead of slashes would make more sense (Author_2016_ABC.pdf). Hence the request for support for a user-defined function. :)

At any rate, I would prefer not to revise a colon-using citekey algorithm that I've used for a decade+ and that's also in active use by graphbib, ACM, etc., as well as my research group (and is used in dozens of academic papers, reports, proposals, etc. that we've written that are in source control where we cut and paste cites etc. from them).

**Comment by tmalsburg** [comment]
Apple [advises against using slashes](https://support.apple.com/en-us/HT202808):

> You should avoid using colons and slashes in the names of files and
> folders because some operating systems and drive formats use these
> characters as directory separators. Consider substituting an
> underline (_) or dash (-) where would normally like to use a slash
> or colon in a filename.

So, yes, using underscores is better.

**Comment by tmalsburg** [comment]
Changing `helm-bibtex-find-pdf-in-library` to do the translation of keys is easy.  Below is the a version in which I used `s-replace` to change the key.

``` elisp
(defun helm-bibtex-find-pdf-in-library (key-or-entry)
  "Searches the directories in `helm-bibtex-library-path' for a
PDF whose names is composed of the BibTeX key plus \".pdf\".  The
path of the first matching PDF is returned."
  (let* ((key (if (stringp key-or-entry)
                  key-or-entry
                (helm-bibtex-get-value "=key=" key-or-entry)))
         (key (s-replace ":" "_" key))
         (path (-first 'f-file?
                       (--map (f-join it (s-concat key ".pdf"))
                              (-flatten (list helm-bibtex-library-path))))))
    (when path (list path))))
```

Perhaps, you can play with it and see how it works.  Later we can make this configurable for people who need different transformations.

**Comment by jowens** [comment]
I like your style. `s-replace` seems like exactly what I need here. I'll aim for this strategy once I get all the directories set up. Carry on!
