### ISSUE TITLE
Prompt for pre- and postnotes in pandoc citations (like in LaTeX citations)

### ISSUE THREAD

**Issue by tillheilmann** [tmalsburg/helm-bibtex#96]
I regularly have to add a "cf." or "see" and page numbers to my pandoc citations. Why not support it out of the box (like for LaTeX)? I guess something like `[/prenote/ /citekey/, /postnote/]` would be right for most people.

**Comment by jagrg** [comment]
What you describe has been implemented already AFAICT. If you call helm-bibtex and choose the "Insert Citation" action, helm-bibtex prompts for pre and post notes by default. Otherwise it might be the case that you are using an older version, or that you have `helm-bibtex-cite-prompt-for-optional-arguments` set to nil.

**Comment by tillheilmann** [comment]
helm-bibtex only prompts for pre- and postnotes when it calls `helm-bibtex-format-citation-cite`, i.e. when you insert a citation into a buffer with major mode latex-mode. When you work with a pandoc document (major mode markdown-mode), `helm-bibtex-format-citation-pandoc-citeproc` is used, which does not prompt for pre- and postnotes. (I have version 20160210.1438 installed and `helm-bibtex-cite-prompt-for-optional-arguments` is not disabled. )

**Comment by jagrg** [comment]
You're right. This feature wasn't added to `helm-bibtex-format-citation-pandoc-citeproc`. I'm not too familiar with pandoc citations though. Could you maybe describe what the syntax for pre and postnotes looks like?

**Comment by tillheilmann** [comment]
As I said: "[/prenote/ /citekey/, /postnote/]", so something like `[CITEKEY, 12]` or `[cf. CITEKEY, 23]` or `[see CITEKEY]`.

**Comment by tmalsburg** [comment]
Till, personally, I don't use pandoc citeproc, but I'd be happy to include a citation function that supports pre- and postnotes for pandoc.  You can use `helm-bibtex-format-citation-cite` as a template for writing such a function.  Should be relatively straightforward.

**Comment by tillheilmann** [comment]
I will try that. (Unfortunately, my knowledge of elisp barely exceeds copy-paste-mangle-code-trial-and-error, so it might take some time and produce questionable results.)

**Comment by jagrg** [comment]
@tillheilmann let me know if this works for you:

```elisp
(defun helm-bibtex-format-citation-cite-pandoc-citeproc (keys)
  "Formatter for pandoc-citeproc citations."
  (let ((prenote  (if helm-bibtex-cite-prompt-for-optional-arguments (read-from-minibuffer "Prenote: ") ""))
	(postnote (if helm-bibtex-cite-prompt-for-optional-arguments (read-from-minibuffer "Postnote: ") "")))
    (if (and (string= "" prenote) (string= "" postnote))
	(format "[%s]" (s-join "; " (--map (concat "@" it) keys)))
      (if (string= "" prenote)
	  (format "[%s %s]" (s-join "; " (--map (concat "@" it) keys)) postnote)
	(format "[%s %s %s]" prenote (s-join "; " (--map (concat "@" it) keys)) postnote)))))
```

**Comment by tillheilmann** [comment]
No, that doesn't work. This does (see below), but it is probably ugly.

```
(defun helm-bibtex-format-citation-pandoc-citeproc (keys)
  "Formatter for pandoc-citeproc citations."
  (let ((prenote  (if helm-bibtex-cite-prompt-for-optional-arguments (read-from-minibuffer "Prenote: ") ""))
	(postnote (if helm-bibtex-cite-prompt-for-optional-arguments (read-from-minibuffer "Postnote: ") "")))
    (if (and (string= "" prenote) (string= "" postnote))
	(format "[%s]" (s-join "; " (--map (concat "@" it) keys)))
      (
       if (string= "" prenote)
       	  (format "[%s%s]" (s-join "; " (--map (concat "@" it) keys)) (concat ", " postnote))
       	(if (string= "" postnote)
	    (format "[%s%s]" (concat prenote " ") (s-join "; " (--map (concat "@" it) keys)))
	  (format "[%s%s%s]" (concat prenote " ") (s-join "; " (--map (concat "@" it) keys)) (concat ", " postnote)))))))
```

**Comment by tmalsburg** [comment]
Great. I'll make some cosmetic changes and will merge it later today.  Thanks everyone for your contributions.

**Comment by tmalsburg** [comment]
Could you please test the version below:

``` elisp
(defun helm-bibtex-format-citation-pandoc-citeproc (keys)
  "Formatter for pandoc-citeproc citations."
  (let* ((prenote  (if helm-bibtex-cite-prompt-for-optional-arguments (read-from-minibuffer "Prenote: ") ""))
         (postnote (if helm-bibtex-cite-prompt-for-optional-arguments (read-from-minibuffer "Postnote: ") ""))
         (prenote  (if (string= "" prenote)  "" (concat prenote  " ")))
         (postnote (if (string= "" postnote) "" (concat ", " postnote))))
    (format "[%s%s%s]" prenote (s-join "; " (--map (concat "@" it) keys)) postnote)))
```

Results of my tests:

With `(setq helm-bibtex-cite-prompt-for-optional-arguments t)`:

``` markdown
[test @Christianson2016, test]
[test @Christianson2016]
[@Christianson2016, test]
[@Christianson2016]
[test @Christianson2016; @Cohen2012, sdg]
```

With `(setq helm-bibtex-cite-prompt-for-optional-arguments nil)`:

``` markdown
[@Christianson2016]
[@Christianson2016; @Cohen2012]
```

Do these citations look correct?

**Comment by tillheilmann** [comment]
It works just like I (and, presumably, pandoc/markdown) expect it. When multiple keys are given pre- and postnotes should probably be input and formatted separately for every key. Since I hardly ever do that it's good enough for me, though. Thanks!

**Comment by tmalsburg** [comment]
Ok, added in bddd4c82337072dad326e7dea6507eb3ec01e320.

If you want pre- and postnotes for each citation separately you have to use the insert citation repeatedly.  This is consistent with how citations work in LaTeX documents.
