### ISSUE TITLE
Include new function as option

### ISSUE THREAD

**Issue by DiogoFerrari** [tmalsburg/helm-bibtex#97]
I store pdfs in one folder and annotated version of the pdfs in another folder. I would like to open the annotated pdfs from helm in the same way I open original pdfs. The different in the name of the files is just that I add " - annotated" after the bibtex key in the name of the file. Would you have a clue about how I can do it to extend bibtex functionalities.

**Comment by tmalsburg** [comment]
If you simply want to open the annotated file instead of the vanilla PDF, you can simply modify `helm-bibtex-find-pdf-in-library`.  You have to replace `(s-concat key ".pdf")` by `s-concat key " - annotated.pdf")`.  If you want the ability to open either of the two versions, that would be a bit more effort.  One solution that might be close enough: Use the `file` field (see [here](https://github.com/tmalsburg/helm-bibtex#pdf-files)) which allows you to associate several PDFs with one entry.  When you choose the open PDF action, all PDFs are opened (the annotated and the vanilla PDF).

**Comment by DiogoFerrari** [comment]
Great. The ad-hoc solution I adopted was to create another function helm-bibtex-find-pdf-in-library-annotated incorporating the @tmalsburg's suggestion, and I also modified the function helm-bibtex-find-pdf as below so that it first open the annotated if it finds it, otherwise it tries to find the original pdf. I put the path for both folders (vanilla pdf and annotated ones) as below. Ideally, I would prefer to have an option popping out so that I can choose which one to open, but this will do for now. If someone knows a quick modification to include "open the annotated pdf" as option, I would appreciate to adopt that.
(setq helm-bibtex-library-path '("~/path/to/pdf/" "~/path/to/pdf-annotated/"))

(defun helm-bibtex-find-pdf (key-or-entry)
 ...
  (or
   (helm-bibtex-find-pdf-in-library-annotated key-or-entry) ;; this line was included 
   (helm-bibtex-find-pdf-in-field key-or-entry)
      (helm-bibtex-find-pdf-in-library key-or-entry)))

**Comment by jagrg** [comment]
@DiogoFerrari If you just want a very simple way of opening your annotated PDFs, you could try something like this:

```elisp
(defun helm-bibtex-open-annotated-pdf (key)
  (let ((pdf (car (helm-bibtex-find-pdf-in-library (s-concat key "-annotated")))))
    (when pdf
      (browse-url pdf))))   
```
You will need to rename the annotated version to: `key-annotated.pdf` and add the function to the list of actions:

```
(helm-delete-action-from-source "Open annotated PDF (if present)" helm-source-bibtex)
(helm-add-action-to-source "Open annotated PDF (if present)" 'helm-bibtex-open-annotated-pdf helm-source-bibtex 0)
```

**Comment by DiogoFerrari** [comment]
It works great. Thanks

**Comment by tmalsburg** [comment]
Awesome, this was easier than expected thanks to `helm-add-action-to-source`.

One suggestion: instead of `browse-url`, I recommend using `helm-bibtex-pdf-open-function` (which is `find-file` by default).

**Comment by tmalsburg** [comment]
This solution could also be used for opening supplements.  Neat.  I think I'll add a section to the documentation.

**Comment by tmalsburg** [comment]
Added a message in case there is no annotated PDF:

``` elisp
(defun helm-bibtex-open-annotated-pdf (key)
  (let ((pdf (car (helm-bibtex-find-pdf-in-library (s-concat key "-annotated")))))
    (if pdf
        (helm-bibtex-pdf-open-function pdf)
      (message "No annotated PDF found."))))
```

See https://github.com/tmalsburg/helm-bibtex#action-for-opening-annotated-pdfs
